### ISSUE TITLE
MagiskSU Canary is gone after rebooting after installing riru core

### ISSUE THREAD

**Issue by X1nto** [RikkaApps/Riru#100]
Installing riru-core on latest magisk canary causes magisk to be completely gone after reboot, when reflashing it says that boot image is already patched and only thing to do is flash uninstaller and magisk canary again. I thought this was an issue with my ROM, I contacted maintainer and sent him logcat. As he explains it "Riru tries to remove hook from the process on the boot". I'm attaching the same logcat [here](https://drive.google.com/file/d/10Nb9T4UyWRzBTWq5In9EM6ax2EUmCOUW/view?usp=drivesdk)

**Comment by RikkaW** [comment]
Riru removes `jniRegisterNativeMethods` "hook" in every app process. It's not related to your situation.

**Comment by X1nto** [comment]
Thanks for answering, I'll try to contact my maintainer again and will update the issue

**Comment by RikkaW** [comment]
From my experience, if something blocks the "boot process" of Magisk (e.g., post-fs-data script runs forever), Magisk will appear "gone". This should be a direction worth investigating.

**Comment by X1nto** [comment]
Update regarding issue: Looks like problem was with magisk itself and it only occured on certain modules. Looks like it got fixed
