### ISSUE TITLE
How To Slove sdcard write Permission When I Wirte Riru Module

### ISSUE THREAD

**Issue by yhnu** [RikkaApps/Riru#101]
![image](https://user-images.githubusercontent.com/23090916/81493567-da831580-92d3-11ea-8b03-cb8f0f380018.png)

-[13: Permission denied]

**Comment by RikkaW** [comment]
What's your target process? Was storage permission granted to the target app?

**Comment by yhnu** [comment]
![image](https://user-images.githubusercontent.com/23090916/81496181-4b342d00-92e8-11ea-8280-ee766ed2e23a.png)

target process is 17198, and granted the storage premission

**Comment by yhnu** [comment]
![image](https://user-images.githubusercontent.com/23090916/81496398-132de980-92ea-11ea-8741-12668efc9080.png)
the detail info and code.
![image](https://user-images.githubusercontent.com/23090916/81496415-2771e680-92ea-11ea-8a1b-f2bbe1bce0f2.png)

**Comment by RikkaW** [comment]
The zygote process has no permission of `/sdcard` because of SELinux.
To access files in `/data/misc` in the app process, you should check both permission and SELinux context.
