### ISSUE TITLE
Riru not found in memory.

### ISSUE THREAD

**Issue by zeromentu** [RikkaApps/Riru#103]
I already uninstalled and rebooted several times, uninstalled edxposed and I always got that error, I don't know what files should I give you
Hope you can help me

**Comment by qounik** [comment]
Same, Just Installed for Storage Isolation but It says not found, Installed Riru app says not found in Memory.
[magisk_log_20200530_141003.log](https://github.com/RikkaApps/Riru/files/4705310/magisk_log_20200530_141003.log)

**Comment by qounik** [comment]
Same, Just Installed for Storage Isolation but It says not found, Installed Riru app says not found in Memory.
[magisk_log_20200530_141003.log](https://github.com/RikkaApps/Riru/files/4705310/magisk_log_20200530_141003.log)

**Comment by qounik** [comment]
Tired older version, no luck

**Comment by RikkaW** [comment]
Starting v21.1, the random name is used. However, the app is not updated (it detects old name), so it's normal that "Riru not found in memory".

**Comment by bengalih** [comment]
How to tell if Riru is installed then?
EdXposed gives me error that it is not Active, and their advice is to troubleshoot Riru because of error.
What is strange is all my EdXposed module appears to be active.
