### ISSUE TITLE
Riru core 21.2 causes safety net both to fail

### ISSUE THREAD

**Issue by leroy1985** [RikkaApps/Riru#104]
Soon as riru core is disabled it passes

**Comment by DrSaad77** [comment]
agreed and it is also missing around a lot off things!!
1. When you do a simple reboot, it stuck on power off splash logo for few minutes, before it turn off the phone.
2. safety net fail as you mentioned
3. Some wake looks of the phone are affected, like Easy screen turn on when you put the hand simple above sensor....
CF: https://www.samsung.com/au/support/mobile-devices/using-easy-mode/
