### ISSUE TITLE
[疑问] [位置报告器]

### ISSUE THREAD

**Issue by 8lexliu** [RikkaApps/Riru#107]
你好，十分感谢你开发优秀的 Magisk 的模块。最近在升级 Android 11 Beta 2 (Build: RPB2.200611.009) 后，发现你编写的 [riru_location_report_enabler](https://github.com/Magisk-Modules-Repo/riru_location_report_enabler) 不能在该版本正常工作了，因为原 Repo 已经封存了，所以想了解下该模块还会更新吗？再次感谢你开发的优秀模块。

**Comment by RikkaW** [comment]
以后再说
