### ISSUE TITLE
显示:Riru: hook removed

### ISSUE THREAD

**Issue by jayjd** [RikkaApps/Riru#109]
V/Riru: hook removed
V/Riru: e31e: forkAndSpecializePost
打开软件提示这个 要怎么处理啊

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru/blob/222491e3c33f73a9453db904e1bbc59467883b47/module/src/main/cpp/main.cpp#L313-L321
与使用者无关的（

**Comment by jayjd** [comment]
@RikkaW 啥原因啊
