### ISSUE TITLE
Riru and EdXposed Cause ANR error (App Not Responding) on Stbemu app

### ISSUE THREAD

**Issue by mondev2020** [RikkaApps/Riru#111]
Riru and EdXposed Cause ANR error (App Not Responding) on Stbemu apps (in all STB apps like [STBemu](https://play.google.com/store/apps/details?id=com.mvas.stb.emu.free&hl=fr), [Ksport STB](https://play.google.com/store/apps/details?id=com.ksport.stb.pro&hl=fr), [MY TV STB](https://play.google.com/store/apps/details?id=com.mytv.stb.emu.tu&hl=fr) ...etc).

- I'am on Android Pi.e,
- I'am using Magisk.
- Riru and EdXposed are working properly.
- But cause ANR error on STB apps, and it is impossible to start these apps !

When I uninstall Riru and EdXposed from Magisk, all STBemu application rework again.

==> The issue is from Riru and EdXposed modules

**Comment by RikkaW** [comment]
This should be a problem related to EdXposed only 😶.
