### ISSUE TITLE
Hi Riru chan ^w^

### ISSUE THREAD

**Issue by bolbolfolfol** [RikkaApps/Riru#114]
This is about riru core and EdXposed-SandHook
i want to install them as system files and not as magisk module
any idea how ???

**Comment by RikkaW** [comment]
In short, follow the installation script to copy files.

But this is highly not recommended since, without Magisk, there is no reliable way to run scripts on boot. Riru itself does not require the scripts when "installed as system files" for now, but it may be different in the future.
