### ISSUE TITLE
Android pie 数据boom

### ISSUE THREAD

**Issue by E7KMbb** [RikkaApps/Riru#12]
在Android pie中使用，/system/lib64/中的libmemtrack.so会替换原本的系统libmemtrack.so导致数据无法使用

**Comment by RikkaW** [comment]
Riru 是通过替换 libmemtrack.so 实现，lib 和 lib64 里的都会被替换
根据你的描述，只删 lib64 的就没有问题，说明是某个使用的模块有问题的可能性更大
所以在不使用任何模块的情况下会有问题吗

另外，问题是什么

**Comment by E7KMbb** [comment]
谢谢，问题解决了，单独刷入Riru，未修改内容，数据没有问题，似乎和需要riru的模块一起刷入时，才会产生问题
