### ISSUE TITLE
v22的新方法使模块的加载过晚

### ISSUE THREAD

**Issue by canyie** [RikkaApps/Riru#121]
修改public.libraries.txt确实可以注入zygote，但是在这个文件里的库实际上是在 `Runtime::Create()` 走完之后才加载的，这会导致一些函数hook不到了（比如Android 10 中的`OatFileManager.SetOnlyUseSystemOatFiles()`）
同时部分模块很依赖以前的行为（zygote刚启动就被加载），比如以前模块被加载时libart.so还没被加载，edxp通过hook dlopen()/梦境hook JNI_CreateJavaVM() 感知libart.so加载等

**Comment by RikkaW** [comment]
因为只要内存中存在被 Magisk 修改的文件就一定会被发现（参见 [vvb2060/MagiskDetector](https://github.com/vvb2060/MagiskDetector/blob/master/README_ZH.md#%E6%A3%80%E6%B5%8Bmagisk%E6%A8%A1%E5%9D%97)），所以必须使用一种不修改已有的文件的方法，改 public.libraries.txt 看起来是最简单可靠的了（

说的那些是一定不可能绕过的 吗（

**Comment by canyie** [comment]
@RikkaW  有些函数必须要hook掉，如果hook时机太晚会有很严重的问题

我这也有另外一个办法（https://github.com/canyie/NbInjection ），会比改public.libraries.txt里的库早一点被加载，不过magisk hide不会对被更改过的系统属性进行隐藏，要自己处理，就又变成打地鼠了（虽然我还是觉得这样比替换原有so库好）

**Comment by RikkaW** [comment]
小声透露一下 Magisk （比较远的）未来有将类似 Riru 的功能内置，并且那边的计划是只允许进入应用进程后再运行模块代码，也不允许修改 nativeFork... 什么的的参数（

Riru 这边想想现在还是先用这个 native bridge 的方法（因为会被系统 dlopen，所以对于不是 X86 的只要提供一个唯一内容就是再 dlopen 真正干活的部分好像没什么问题？），<del>不过还是早点向很远的未来做准备吧（</del>

**Comment by canyie** [comment]
修改native bridge来注入有很多坑，可以看[这里](https://blog.canyie.top/2020/08/18/nbinjection/)；另外我对magisk未来的那个内置功能挺感兴趣的，能透露一下更多信息吗（

**Comment by RikkaW** [comment]
那些坑似乎都解决好了（

对于更多信息，也不知道更多（

**Comment by user1121114685** [comment]
> 那些坑似乎都解决好了（
> 
> 对于更多信息，也不知道更多（

请问有没有API文档供查看？只能看到一个api更改日志，网上也未找到更多关于riru的模块教程，请大佬指点一二，感谢。
