### ISSUE TITLE
能否在没有Magisk模块的情况下安装Riru？

### ISSUE THREAD

**Issue by nukemiko** [RikkaApps/Riru#124]
我无法在android-x86上安装Magisk但是又需要使用存储空间隔离中的增强模式，所以能否在没Magisk的情况下安装Riru？如果可以，如何操作？

**Comment by RikkaW** [comment]
1. 你需要有可靠的开机时运行一些东西的手段（Android 世界的开机启动太晚了）
2. 如果你不了解 Magisk 模块如何工作和模块安装脚本做了什么，非常不建议自己瞎玩

**Comment by nukemiko** [comment]
可以把启动命令加入/etc/init.sh，估计是android-x86独有特性

在 2020-11-03 00:18:29，Rikka <notifications@github.com> 写道：


你需要有可靠的开机时运行一些东西的手段（Android 世界的开机启动太晚了）
如果你不了解 Magisk 模块如何工作和模块安装脚本做了什么，非常不建议自己瞎玩
