### ISSUE TITLE
各位好，我想问一个新手关心的问题，如何构建一个自己的Riru模块。

### ISSUE THREAD

**Issue by user1121114685** [RikkaApps/Riru#128]
## 未找到详细的API文档    
可能有文档的，但是我没找到。我来来回回翻了很多次。也在google上搜索过。不过没参考意义了！只有一篇。[我找到的教程](https://blog.xhyeax.com/2019/11/06/assemble-own-riru-module/),除此之外未找到相关api文档，并未发现开发者交流的地方。    
## 
还望大佬们指点一下。

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru-ModuleTemplate
