### ISSUE TITLE
雷电模拟器7.1.2

### ISSUE THREAD

**Issue by makegame007** [RikkaApps/Riru#130]
**Describe the bug:**
armeabi-v7a/libmemtrack.so, 替换系统的/system/lib/libmemtrack.so, 然后运行APP，出现如下错误。
是本来就不支持X86吗？
![image](https://user-images.githubusercontent.com/16770604/99647826-41586700-2a8d-11eb-825c-9bfbe4e36823.png)

**Comment by makegame007** [comment]
11-19 17:16:48.956: D/WifiStateMachine(1444): --------- beginning of crash
11-19 17:17:30.421: A/libc(2403): CANNOT LINK EXECUTABLE "app_process": "/system/lib/libmemtrack.so" has unexpected e_machine: 40
11-19 17:17:30.421: A/libc(2403): Fatal signal 6 (SIGABRT), code -6 in tid 2403 (app_process)
11-19 17:17:30.432: W/(1192): debuggerd: handling request: pid=2403 uid=0 gid=0 tid=2403
11-19 17:17:30.496: A/DEBUG(2404): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-19 17:17:30.496: A/DEBUG(2404): Build fingerprint: 'google/android_x86/x86:7.1.2/N2G48C/4565141:/release-keys'
11-19 17:17:30.496: A/DEBUG(2404): Revision: '0'
11-19 17:17:30.496: A/DEBUG(2404): ABI: 'x86'
11-19 17:17:30.496: A/DEBUG(2404): pid: 2403, tid: 2403, name: app_process  >>> app_process <<<
11-19 17:17:30.496: A/DEBUG(2404): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-19 17:17:30.496: A/DEBUG(2404):     eax 00000000  ebx 00000963  ecx 00000963  edx 00000006
11-19 17:17:30.496: A/DEBUG(2404):     esi c7ffe98c  edi c7ffe934
11-19 17:17:30.496: A/DEBUG(2404):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
11-19 17:17:30.496: A/DEBUG(2404):     eip c7f29c10  ebp cfffe668  esp cfffe60c  flags 00000296
11-19 17:17:30.504: A/DEBUG(2404): backtrace:
11-19 17:17:30.504: A/DEBUG(2404):     #00 pc 00000c10  [vdso:c7f29000] (__kernel_vsyscall+16)
11-19 17:17:30.504: A/DEBUG(2404):     #01 pc 0009366c  /system/bin/linker (__dl_tgkill+28)
11-19 17:17:30.504: A/DEBUG(2404):     #02 pc 000925e5  /system/bin/linker (__dl_pthread_kill+85)
11-19 17:17:30.504: A/DEBUG(2404):     #03 pc 00082efa  /system/bin/linker (__dl_raise+42)
11-19 17:17:30.504: A/DEBUG(2404):     #04 pc 000801d6  /system/bin/linker (__dl_abort+86)
11-19 17:17:30.504: A/DEBUG(2404):     #05 pc 00082858  /system/bin/linker (__dl___libc_fatal+40)
11-19 17:17:30.504: A/DEBUG(2404):     #06 pc 000102c7  /system/bin/linker (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockj+5127)
11-19 17:17:30.504: A/DEBUG(2404):     #07 pc 0000edf6  /system/bin/linker (__dl___linker_init+630)
11-19 17:17:30.504: A/DEBUG(2404):     #08 pc 0001abe3  /system/bin/linker (__dl__start+35)
11-19 17:17:30.504: A/DEBUG(2404):     #09 pc 00000005  <unknown>
11-19 17:17:30.511: W/NativeCrashListener(1444): Couldn't find ProcessRecord for pid 2403
11-19 17:17:30.514: W/(1192): debuggerd: resuming target 2403
11-19 17:17:30.514: E/(1192): debuggerd: failed to send signal 18 to target: No such process
11-19 17:17:30.514: I/BootReceiver(1444): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
11-19 17:17:48.911: W/AudioTrack(1444): AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz

**Comment by RikkaW** [comment]
v22 早就不用 libmemtrack 了

**Comment by makegame007** [comment]
riru能支持模拟器吗？

**Comment by makegame007** [comment]
我用的是去年的一个版本

**Comment by RikkaW** [comment]
开发过程中一直一直有使用 x86 的模拟器

以及
> armeabi-v7a/libmemtrack.so, 替换系统的/system/lib/libmemtrack.so

不是应该用 x86 的换 吗（
