### ISSUE TITLE
Riru v22 error

### ISSUE THREAD

**Issue by acestars** [RikkaApps/Riru#131]
Attached logcat.
Magisk Canary 1469b82a (21101)
Magisk Manager 1469b82a (315)
Lineage OS 16.0 / Android 9
Xiaomi Redmi Note 2

[riru_22_log.txt](https://github.com/RikkaApps/Riru/files/5581055/riru_22_log.txt)

**Comment by RikkaW** [comment]
Debug version? Try to add `multiDexEnabled false`.

**Comment by acestars** [comment]
Im sorry what do you mean with debug version? which app? and where should i put multiDexEnabled false?
Actually i cannot reproduce the error again. Riru v22 just doesnt work. I cannot find any error again in logcat. The riru app says something like this.
![image](https://user-images.githubusercontent.com/637192/100241053-dcf24780-2f65-11eb-804d-be0ea63822e5.png)

**Comment by RikkaW** [comment]
Please try [v22.1](https://github.com/RikkaApps/Riru/releases/tag/v22.1).

**Comment by acestars** [comment]
I already tried v22.3 from magisk repository but cant make it works. I rebooted the phone several times but still cant get any usefull logcat from riru.

but there's something like this, idk if this can tell anything
`
11-26 06:28:40.581   315   315 E rirud   : setsockcreatecon failed with 2: No such file or directory
11-26 06:28:40.581   315   315 I rirud   : socket rirud created
`

[riru_22_3_log1.txt](https://github.com/RikkaApps/Riru/files/5599679/riru_22_3_log1.txt)
[riru_22_3_log2.txt](https://github.com/RikkaApps/Riru/files/5599678/riru_22_3_log2.txt)
[riru_22_3_log3.txt](https://github.com/RikkaApps/Riru/files/5599680/riru_22_3_log3.txt)

**Comment by duracellh** [comment]
Did the name change? That looks like the modules are looking for a a different named riru (riru-core vs riru)

**Comment by RikkaW** [comment]
Looks like your device has super old kernel which does not have `/proc/thread-self`.
Try [v22.4](https://github.com/RikkaApps/Riru/releases/tag/v22.4).

**Comment by acestars** [comment]
Im sorry still doesnt work.  Here the logcat and list of /proc

[procs.txt](https://github.com/RikkaApps/Riru/files/5601927/procs.txt)
[riru_22_3_log4.txt](https://github.com/RikkaApps/Riru/files/5601928/riru_22_3_log4.txt)

**Comment by RikkaW** [comment]
It seems `ro.dalvik.vm.native.bridge` is reset by "ace-tweaks-pie" module.

**Comment by acestars** [comment]
Attached the result of riru app after i removed the prop. Is it works now?

![image](https://user-images.githubusercontent.com/637192/100352375-7893be80-301f-11eb-8043-b289d5feb259.png)

**Comment by RikkaW** [comment]
Yes
