### ISSUE TITLE
Riru V22 hiding mechanism not working

### ISSUE THREAD

**Issue by slimshouki** [RikkaApps/Riru#132]
After struggling flashing riru v22 with the release EdXposed-YAHFA-v0.5.1.4-release mentioned in this [Fix #643 #648](https://github.com/ElderDrivers/EdXposed/issues/643) thanks to @yujincheng08 in order to be able to avoid bootloop. I found out that hiding mechanism is not working since a particular app (com.fawry.myfawry) banking app from play store is exposing the existence of riru core without root. I am confirming that hiding mechanism is enabled as shown in attached screenshot
![Screenshot_2020-11-23-18-38-11-204_moe riru manager](https://user-images.githubusercontent.com/74891073/99989273-19ce0b00-2dbb-11eb-9b32-86756ace5532.jpg)

**Comment by RikkaW** [comment]
Have you tested enable Riru itself only ?

**Comment by yujincheng08** [comment]
Try to disable edxp first.

**Comment by slimshouki** [comment]
@yujincheng08 disabled edxposed
@RikkaW riru alone not detected. Edxposed framework alone not detected. Both riru and framework enabled then its detected.

**Comment by slimshouki** [comment]
![Uploading Screenshot_2020-11-23-19-12-04-074_com.fawry.myfawry.jpg…]()

**Comment by yujincheng08** [comment]
Then this is edxp's problem.

**Comment by slimshouki** [comment]
@yujincheng08 I flashed your modded framework along with your mentioned edxposed manager (scope module) and then turned on app list and hide edxposed manager in settings then added concerned app to blacklist but it stills detects hooks.

**Comment by slimshouki** [comment]
@yujincheng08 
Would you give a try with this invincible app? Never saw such a fortress anti root/xposed app.

**Comment by yujincheng08** [comment]
@slimshouki not working for me.

**Comment by slimshouki** [comment]
@yujincheng08 not working means app is not opening or not installing or the app popped up "application is hooked"

**Comment by klever1988** [comment]
@slimshouki how to get that log which was shown in your first post?

**Comment by slimshouki** [comment]
> @slimshouki how to get that log which was shown in your first post?

There 's a riru app bundled with riru 22 which makes all these necessary checks
