### ISSUE TITLE
Riru v22.0 doesn't work (Galaxy S10)

### ISSUE THREAD

**Issue by dr4go** [RikkaApps/Riru#133]
Hello Rikka,

finally found the time to create this ticket - thanks for the hint on the Telegram channel. The situation is simple: I'm on the latest firmware available (Android 10) on my Samsung Galaxy S10 (G973F), without twrp, encryption still active, patched with the newest Magisk Canary available.

While everything seems to work, Riru does not seem to be running on the phone while with Riru v21.3 everything is working fine. I even removed every content in /data/adb/riru just to have a clean start.

What information do you need / how can I assist what's wrong with it? I've attached everything, that came to my mind, which could be helpful...

Thanks in advance,
dr4go

Attachments:
1) ![Screenshot_20201123-232144](https://user-images.githubusercontent.com/597874/100022848-2c106f00-2de4-11eb-943d-202508559a4d.jpg)
2) ![Screenshot_20201123-232053_Riru](https://user-images.githubusercontent.com/597874/100022908-49453d80-2de4-11eb-82a1-8122d393b47f.jpg)
3) ![Screenshot_20201123-232236_MiXplorer](https://user-images.githubusercontent.com/597874/100022930-55c99600-2de4-11eb-8d0f-8c8f01f64290.jpg)
4) ![Screenshot_20201123-232246_MiXplorer](https://user-images.githubusercontent.com/597874/100022954-624dee80-2de4-11eb-87db-36a9e9051bfd.jpg)
5) [magisk_log_20201123_232106.log](https://github.com/RikkaApps/Riru/files/5586144/magisk_log_20201123_232106.log)

**Comment by RikkaW** [comment]
Looks like SELinux rules from Riru are not working. Check the kernel log if there is `magiskinit: Loading custom sepolicy patch: .magisk/mirror/persist/magisk/riru-core/sepolicy.rule` at the beginning.

By the way, I'll try a new way which does not require SELinux rules patch.

**Comment by rypz79** [comment]
In my SM-N975F (N10+) v22.0 doesn't support EdXposed v0.4.6.4(4563)(SandHook) module.
SELinux is permissive.
[magisk_log_20201124_080434.log](https://github.com/RikkaApps/Riru/files/5587760/magisk_log_20201124_080434.log)

**Comment by lukjod** [comment]
same story with s10+ on Magisk 21.1 (21100) and twrp, must go back to riru 21.3 for exposed fremework to load and work

**Comment by fusionneur** [comment]
Edxposed Yahfa fails on riru 22. Had to rollback..

**Comment by LoreBadTime** [comment]
Same issue here edxposed fail to load,i am in magisk 20.4

**Comment by dr4go** [comment]
I always find it very funny when people simply spam every bug report with unrelated bugs / reports. Nevertheless... back to topic...

I managed to grab a kernel log (but it was present in a previous last_kmsg with a grep riru). After that I wanted to provide you or John a clean log, rebooted the phone and I can't get any related selinux error message in the kernel logs since then... It's very strange...

The previous cat /proc/last_kmsg | grep riru:
[riru_kmsg.txt](https://github.com/RikkaApps/Riru/files/5596245/riru_kmsg.txt)

So your assessment seems to be correct, that it should indeed be selinux related. Although there is no magiskinit related riru selinux message...

**Comment by RikkaW** [comment]
@dr4go No `magiskinit: Loading custom sepolicy patch: ..../riru-core/sepolicy.rule`, my guess should be correct.

Please try [v22.1](https://github.com/RikkaApps/Riru/releases/tag/v22.1) which does not require SELinux rule patch.

**Comment by rypz79** [comment]
> @dr4go No `magiskinit: Loading custom sepolicy patch: ..../riru-core/sepolicy.rule`, my guess should be correct.
> 
> Please try [v22.1](https://github.com/RikkaApps/Riru/releases/tag/v22.1) which does not require SELinux rule patch.

Still Doesn't support EdXposed FW module v0.4.6.4(SandHook)
[magisk_log_20201125_174825.log](https://github.com/RikkaApps/Riru/files/5597772/magisk_log_20201125_174825.log)
[20201125174958_TeMeFI_Logcat_Last_KMsg.log](https://github.com/RikkaApps/Riru/files/5597774/20201125174958_TeMeFI_Logcat_Last_KMsg.log)

**Comment by dr4go** [comment]
Already wanted to mention, that v22.2 didn't work, got the logs and everything, but unfortunately wasn't able to comment it until now. Then I realized, that you've already fixed the remaining problems.

Thanks a lot for your efforts. And because a picture says more than words: 
![Screenshot_20201125-201158_Riru](https://user-images.githubusercontent.com/597874/100276850-7b7ca980-2f62-11eb-9210-9357dbe79bd8.jpg)
