### ISSUE TITLE
"Riru - Core is missing" after upgrade to Riru 22. Impossible to run or reinstall EdXposed from Magisk Repo.

### ISSUE THREAD

**Issue by eierfrucht** [RikkaApps/Riru#135]
**Describe the bug:**

After upgrading to Riru 22, a previously working copy of EdXposed 4.6.4 (YAHFA) no longer loads at boot: https://i.postimg.cc/TYkr4nMG/iunkkf-TVVso-1.jpg

When I try to reinstall EdXposed from Magisk Repo, installation fails at 'Riru Core is Missing': https://i.postimg.cc/ZqNpng9K/216w-VTu-Yp40-1.jpg

**Device information:**
 - Device: Huawei Honor 8 Pro (DUK-L09)
 - OS: EMUI 9.1.0.215

**Additional context**

Due to Magisk 20.4, I manually rebooted the device more than just twice, as demanded by Riru 22 install log. Storage Isolation is still fully functional (upgraded to latest module & app) so Riru 22 is basically working for stuff other than EdXposed.

**Comment by asdfugil** [comment]
same here

**Comment by Xelibix** [comment]
I have the same error here.
I rebooted 3 time but i cant install edxposed.
When i flash with v21.3 (https://github.com/RikkaApps/Riru/releases/tag/v21.3) it's working again. 
But it's probably a "stupid_question" to ask why very good module suddenly not working ;)

Device: Google pixel 3 (blueline)
OS: PixelDust
