### ISSUE TITLE
cannot install riru

### ISSUE THREAD

**Issue by kourindoupota** [RikkaApps/Riru#136]
[magisk_install_log_2020-11-25T23:48:35Z.log](https://github.com/RikkaApps/Riru/files/5597766/magisk_install_log_2020-11-25T23.48.35Z.log)

**Comment by WankkoRee** [comment]
+1

**Comment by RikkaW** [comment]
Try v22.2 (44)

**Comment by wzgrx** [comment]
> Try v22.2 (44)

22.2也是安装不了

**Comment by MikuDroid** [comment]
![Screenshot_20201125-234815](https://user-images.githubusercontent.com/22476406/100257682-c73a4d80-2f78-11eb-96c5-2166edb8c48a.jpg)
Iirc only 22.2 acted like this. Before i updated it works fine. Android 10, magisk 21.1
