### ISSUE TITLE
Riru edxposed failing

### ISSUE THREAD

**Issue by bloodpop** [RikkaApps/Riru#137]
**Describe the bug:**
Riru edxposed fails to recognize riru as riru - core and module never activates. Upon reinstalling riru edxposed, installation fails as " 'riru - core' is not installed on device"

**Device information:**
 - Device: Samsung Galaxy S7 Edge
 - OS: Android 8.0.0

**Comment by steven7851** [comment]
Why ask edxposed at riru? Go to [edxposed](https://github.com/ElderDrivers/EdXposed/issues) and see the pinned issues.
