### ISSUE TITLE
Riru 22.4

### ISSUE THREAD

**Issue by AdelSol75** [RikkaApps/Riru#138]
It does not activate: One + 6T with OOS 10.3.6, magisk 21.1, EdXposed YAHFA 4.6.4 updating from Riru 21.3 because with a clean installation with Riru 22.4 it would not let me install EdExposed, the module does not activate and I do not have Exposed running. I have tried restarting the smartphone many times and without solution

**Comment by suhancz** [comment]
Same issue, a bit more details: EdXposed depends on `Riru - Core`, while this package identifies as `Riru`. I assume other modules might suffer from the same symptoms.
```
- Copying zip to temp directory
 - Installing Riru_-_EdXposed-v0.4.6.4_(4563)_(YAHFA)(4563).zip
 - Device is system-as-root
 Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
 inflating: module.prop
 *****************
 Riru - EdXposed
 *****************
 Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
 inflating: customize.sh
 *******************
 Powered by Magisk
 *******************
 - EdXposed Version v0.4.6.4 (4563) (YAHFA)
 - Android sdk: 28
 - Magisk version: 20400
 ******************************
 ! Requirement module 'Riru - Core' is not installed
 ! You can download from 'Magisk Manager' or https://github.com/RikkaApps/Riru/releases 
******************************
 ! Installation failed
```

**Comment by Crescendo-BLYAT** [comment]
use this build https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/36467617/artifacts

**Comment by SkyNinja** [comment]
Riru 22 made major changes that edXposed needs to be updated for the stable version is still out of date. Cresendo-BYLAT's link provides the same canary builds as the edXposed manager's canary tab.
