### ISSUE TITLE
Riru Not Installing

### ISSUE THREAD

**Issue by twistedh** [RikkaApps/Riru#140]
After updating the core, my phone no longer detects riru no matter the version. Manual flash through TWRP gives error 217. When installed through magisk, it shows it worked then disappears after reboot. EDxposed shows Riru core not installed also.

**Device information:**
 - Device: N986U1 Note Ultra 20
 - OS: Android 10 (samsung)

**Comment by RikkaW** [comment]
https://github.com/ElderDrivers/EdXposed/issues/665
🙃
