### ISSUE TITLE
Riru core not installed v22.4

### ISSUE THREAD

**Issue by MikeM4t3** [RikkaApps/Riru#141]
Riru core broke after update, says it is installed... Used riru app checker and says installed. 

Tried installing Edxposed (latest version) through TWRP and magisk (latest version) and says Riru core isn't installed. 

Both core and Edxposed worked on riru core V21.3.

**Device information:**
 - Device: Sony Xperia XZ Premium 
 - OS: Android 10 Carbon rom (latest version)

**Comment by SkyNinja** [comment]
#138 
#137 
#135
