### ISSUE TITLE
"Riru - Core" not installed requirement check

### ISSUE THREAD

**Issue by gabefair** [RikkaApps/Riru#144]
**Describe the bug:**
Hello,

It seems that a recent name change might have introduced a bug. (or its just me being dumb).
When I try to install the framework via Magisk, I am told:
`Requirement module 'Riru - Core' is not installed` however based on your app, I do have the latest version (22.4--46, API 9) installed. I am installed the core through Magisk as per your instructions. 

EDIT: Now that I think about it, this bug could be caused by me using the "hide Magisk by renaming app feature". What do you think?
EDIT-EDIT: No, using the default magisk app and package locations did not fix this issue.

**Device information:**
 - Device: Samsung Galaxy S6 SM-G920F (zeroflte)
 - OS: Android 9

**Additional context**

![Screenshot_20201127-133241](https://user-images.githubusercontent.com/2096785/100454910-cb0ac480-308b-11eb-8d5d-84b4fdca127d.png)
![Screenshot_20201127-133252](https://user-images.githubusercontent.com/2096785/100454944-e1188500-308b-11eb-996e-e428f30165b0.png)

**Comment by AndroSteph** [comment]
Same problem for me, back to "Riru (Riru - Core) v21.3" and my "EdXposed v0.4.6.4 (4563)" works again.

As I need "EdXposed" for example for my "AFWall+" I stay in this configuration.

Thank you for reporting this problem here (my English is really not good and I would have had a hard time to do it).

**Comment by Crescendo-BLYAT** [comment]
use EdXposed Canary for Riru v22.4

**Comment by AndroSteph** [comment]
Thanks for your advice, I will try.
