### ISSUE TITLE
HIDE MECHANISM NOT WORKING !

### ISSUE THREAD

**Issue by Cougar16** [RikkaApps/Riru#145]
Hi , 
The files /data/adb/riru/disable & /data/adb/riru/enable_hide not founds in this directory /data/adb/riru/ ?! 
When I run Riru Status app , it show me "Hide is disabled" what should I do in this case to enable it ?
I tried to add Exposed Manager to black list but something prevent this operation ! 

*Os : Android 10
*Device : Doogee S88 Pro

Thanks to reply me :)
Best regards to you :)
![Screenshot_20201127-143836](https://user-images.githubusercontent.com/66981233/100455028-4ab18700-30be-11eb-9a32-fe80ea317c32.png)
![Screenshot_20201127-141817](https://user-images.githubusercontent.com/66981233/100455033-4c7b4a80-30be-11eb-9bfb-0a171e3ab6b4.png)

**Comment by RikkaW** [comment]
> When the file /data/adb/riru/enable_hide exists, the hide mechanism will be enabled
> https://github.com/RikkaApps/Riru#config

And as you mentioned "E______", you will get these labels 🙃
