### ISSUE TITLE
Which version do i need?

### ISSUE THREAD

**Issue by cnoevl21** [RikkaApps/Riru#147]
im on a moto g power, stock rom, android 10. ive got magisk installed. i want to install edxposed but cant and ive been told its because riru has been updated and i need and older version still called 'riru-core' to get edxposed to work. How far back do i need to go? riru 21.3? riru 21.0? older version? 
And how would i flash this older version? can i get to an older version thru magisk manager? do i need twrp? or would it be done in fastboot?

**Comment by Sfeeen** [comment]
Over here you can find differend versions of Riru-core: https://github.com/RikkaApps/Riru/releases
I also have some problems now (I see a magisk crash after riru-core exec and edxposed manager says that it is not installed). version 19.3 seems better for me since I don't  see any crash in the log.
