### ISSUE TITLE
Riru new versions don't work on my Xperia 5 ii

### ISSUE THREAD

**Issue by flyl0-x** [RikkaApps/Riru#150]
as the title says, the latest version of Riru core doesn't work for me. 21.3 works fine anyway but all versions of Riru after this one don't work.
No bootloops, no lags, All modules and framework are disabled.

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru/releases/download/v22.0/riru-v22.0.r195.d4fdb20.apk
What it says?

**Comment by dariusz-goc** [comment]
I have the same problem on Oreo (Xiaomi Mi6). 21.3 works fine. I tried all versions above up to 23 pre-release and they all give me that riru is not installed or enabled.
![Screenshot_Nova_Launcher_20201130-174246](https://user-images.githubusercontent.com/12624870/100642851-9c197a80-3339-11eb-901d-de03686fb115.png)

**Comment by RikkaW** [comment]
@dariusz-goc What Riru app v23 says? (https://github.com/RikkaApps/Riru/releases/download/v23.0/riru-v23.0.r235.d313e94.apk)

**Comment by flyl0-x** [comment]
> https://github.com/RikkaApps/Riru/releases/download/v23.0/riru-v23.0.r235.d313e94.apk
> What it says?

Riru not installed or not enabled.

Property "ro.dalvik.vm.native.bridge" is not "libriruloader.so".

Make sure you are not using other module which changes this property.

A typical example is, some "optimize" modules changes this property. Since changing this property is meaningless for "optimization", their quality is very questionable. In fact, changing properties for optimization is a joke.

File contents:
/data/adb/riru/dev_random: 8BuN1Zv
/dev/riru_8BuN1Zv not exist
ro.dalvik.vm.native.bridge=0

**Comment by RikkaW** [comment]
@flyl0-x Are you using such modules as it said?

**Comment by flyl0-x** [comment]
@RikkaW !

Here are all the modules I have on magisk:

[Screenshot_20201201-041003.png](https://user-images.githubusercontent.com/25420668/100692456-2a6a1c80-338b-11eb-897e-fd16911f8770.png)


And the ones from edxposed :

![Screenshot_20201201-041152.png](https://user-images.githubusercontent.com/25420668/100692535-5c7b7e80-338b-11eb-8d6f-1df2354d90b7.png)

**Comment by RikkaW** [comment]
@flyl0-x A screenshot shows Riru 21.3? What?

**Comment by flyl0-x** [comment]
Yeah that's the only version that it works

**Comment by RikkaW** [comment]
I highly doubt that you are this kind of person, using new Ritu + old E_____ then starting to shout "oh it's not working". Stop waste other people's time pls.
