### ISSUE TITLE
MIUI12 magisk + riru 22.4 + riru edxposed 0.4.6.4 不生效

### ISSUE THREAD

**Issue by firemen20** [RikkaApps/Riru#151]
**MIUI12 magisk + riru 22.4 + riru edxposed 0.4.6.4 不生效:**
 退回上一个版本 21+ 0.4.5 正常！

**Device information:k30 5g**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 11]

**Additional context**

**Comment by RikkaW** [comment]
ElderDrivers/EdXposed#665 💩
