### ISSUE TITLE
I highly doubt that you are this kind of person, using new Ritu + old E_____ then starting to shout "oh it's not working". Stop waste other people's time pls.

### ISSUE THREAD

**Issue by flyl0-x** [RikkaApps/Riru#153]
I highly doubt that you are this kind of person, using new Ritu + old E_____ then starting to shout "oh it's not working". Stop waste other people's time pls.

_Originally posted by @RikkaW in https://github.com/RikkaApps/Riru/issues/150#issuecomment-736206477_

Bruh are you dumb or something? You're disrespectful for nothing.
I said in my comment that, I'm on 21.3 because your shitty Riru core don't work with the latest updates... Do you really read the comments?

**Comment by Howard20181** [comment]
![IMG_20201201_125426.jpg](https://user-images.githubusercontent.com/40033067/100698833-11e40d00-335f-11eb-9260-96b4b8d550c3.jpg)![Screenshot_2020-12-01-12-54-46-018_org.meowcat.edxposed.manager.jpg](https://user-images.githubusercontent.com/40033067/100698838-16102a80-335f-11eb-87d9-e3300ff3ddbd.jpg)

**Comment by RikkaW** [comment]
What I want is the output of Riru app with the latest version of Riru.
With old Riru, of course it will say "not installed" 🙃.
From your screenshot, E______ is the only Riru module you are using, ElderDrivers/EdXposed#665 💩.
