### ISSUE TITLE
Riru App 23 reports versions 22-23 as not working or not installed. Riru modules (updated for 22+) don't work.

### ISSUE THREAD

**Issue by dariusz-goc** [RikkaApps/Riru#154]
Riru App 23 reports versions 22-23 as not working or not installed. Riru modules (updated for 22+) don't work. I'm using Android Oreo 8.1 (Resurrection Remix, Lineage OS based on Xiaomi Mi6). Riru 21.3 works fine. I tried all versions from riru 22 to 23 pre-release and they all give me that riru is not installed or enabled.
![Screenshot_Nova_Launcher_20201130-174246](https://user-images.githubusercontent.com/12624870/100642851-9c197a80-3339-11eb-901d-de03686fb115.png)

_Originally posted by @dariusz-goc in https://github.com/RikkaApps/Riru/issues/150#issuecomment-735928049_

**Comment by dariusz-goc** [comment]
https://github.com/RikkaApps/Riru/issues/150#issuecomment-736176517

@RikkaW This screenshot is from app v23. This state is with all updated to the latest versions.

**Comment by RikkaW** [comment]
Make sure you are using Riru v23 + Riru app from v23 release first 🙂

**Comment by RikkaW** [comment]
Please provide boot log (in short, start `adb logcat` during boot progress)

**Comment by dariusz-goc** [comment]
Do I need debug version of riru?

**Comment by RikkaW** [comment]
Not necessary.

**Comment by dariusz-goc** [comment]
Ok, this log is with Riru v23 - release (latest). Now the com.android.phone is crashing and device reboots indefinitely.
[riru23-release-bootloop.txt](https://github.com/RikkaApps/Riru/files/5644626/riru23-release-bootloop.txt)

**Comment by RikkaW** [comment]
> tzdata file "/system/usr/share/zoneinfo/tzdata" was present but invalid!

This is the root reason. I don't think it is related to Riru.

**Comment by dariusz-goc** [comment]
Ok, I did update the tz magisk module in the meantime, thank you for helping me troubleshoot this. I will delete this module and update the log.

**Comment by dariusz-goc** [comment]
[riru23-release.txt](https://github.com/RikkaApps/Riru/files/5645035/riru23-release.txt)

Ok, this log is with Riru v23 - release (latest), the state in the latest app is as in the first screenshot in the first comment of this issue, which is:

Riru not installed or not enabled.
File contents:
/data/adb/riru/dev_random: sUGAS2s
/dev/riru_sUGAS2s not exist

**Comment by RikkaW** [comment]
From your log, Magisk modules are loaded after the zygote is started. Older versions of Riru restart zygote even for the first time, so it "works".

This is highly possible a long existed Magisk problem, something is blocking the whole process. Without full logcat (your log is not early enough) and kernal log, I can't make a conclusion.

**Comment by dariusz-goc** [comment]
I made this log with a phone connected to a pc, I restarted the phone and immediately entered the command to take a log, it showed "waiting for device" and the log starts from the moment my computer connected to the phone. Is there any other way to take logs? How to take kernel logs?

**Comment by dariusz-goc** [comment]
Hi, I can see you've added zygote restart workaround in v51, however I'm happy to tell you that magisk canary just updated to 21102 and it fixed the execution cue! I tested Riru v50 (without zygote restart) and now it's working fine for the latest magisk, so you can disable that workaround for magisk >= 21102 👍 Hopefully that will make the restart a bit quicker :)

**Comment by CNoob4ever** [comment]
Riru is not loaded.

04-23 15:22:04.640   840   840 I Magisk  : Magisk c4e8dda3(22102) daemon started
04-23 15:22:04.640   840   840 W Magisk  : Can't switch cgroup
04-23 15:22:04.641   840   840 I Magisk  : * Device API level: 27
04-23 15:22:04.650   840   842 E Magisk  : mount (null)->/ failed with 16: Device or resource busy
04-23 15:22:04.652   840   842 D Magisk  : resetprop: getprop [ro.crypto.state]: [unsupported]
04-23 15:22:04.652   840   842 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
04-23 15:22:04.652   840   842 I Magisk  : ** post-fs-data mode running
04-23 15:22:04.652   840   842 I Magisk  : * Mounting mirrors
04-23 15:22:04.652   840   842 I Magisk  : mount: /sbin/.magisk/mirror/data
04-23 15:22:04.652   840   842 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
04-23 15:22:04.652   840   842 I Magisk  : mount: /sbin/.magisk/mirror/system
04-23 15:22:04.652   840   842 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
04-23 15:22:04.653   840   842 I Magisk  : mount: /sbin/.magisk/mirror/system
04-23 15:22:04.653   840   842 E Magisk  : mount /sbin/.magisk/block/data->/sbin/.magisk/mirror/data failed with 16: Device or resource busy
04-23 15:22:04.653   840   842 I Magisk  : mount: /sbin/.magisk/mirror/data
04-23 15:22:04.653   840   842 I Magisk  : link: /sbin/.magisk/mirror/vendor
04-23 15:22:04.653   840   842 I Magisk  : * Initializing Magisk environment
04-23 15:22:04.677   840   842 D Magisk  : resetprop: read prop from [/data/property/persist.sys.safemode]
04-23 15:22:04.677   840   842 D Magisk  : resetprop: getprop (persist) [persist.sys.safemode]: [0]
04-23 15:22:05.056   840   842 I Magisk  : * Running post-fs-data.d scripts
04-23 15:22:05.062   840   842 D Magisk  : magiskdb: query magiskhide=[0]
04-23 15:22:05.063   840   842 D Magisk  : bind_mnt: /sbin/.magisk/modules <- /sbin/.magisk/mirror/data/adb/modules
04-23 15:22:05.063   840   842 E Magisk  : open: /sys/fs/selinux/context failed with 2: No such file or directory
04-23 15:22:05.068   840   842 I Magisk  : * Running module post-fs-data scripts
04-23 15:22:05.072   847   847 I Magisk  : riru-core: exec [post-fs-data.sh]
04-23 15:22:05.111   849   849 I rirud   : backup original native bridge 0
04-23 15:22:05.136   849   849 I rirud   : Magisk version is 22102
04-23 15:22:05.157   849   849 I rirud   : Magisk tmpfs path is /sbin
04-23 15:22:05.159   853   853 E rirud   : setsockcreatecon failed with 22: Invalid argument
04-23 15:22:05.159   853   853 I rirud   : socket rirud created
04-23 15:22:05.159   847   847 I Magisk  : riru_edxposed: exec [post-fs-data.sh]
04-23 15:22:06.243   840   842 I Magisk  : * Loading modules
04-23 15:22:06.243   840   842 I Magisk  : riru-core: loading [system.prop]
04-23 15:22:06.243   840   842 D Magisk  : resetprop: Parse prop file [/data/adb/modules/riru-core/system.prop]
04-23 15:22:06.244   840   842 D Magisk  : resetprop: delete prop [ro.dalvik.vm.native.bridge]
04-23 15:22:06.244   840   842 D Magisk  : resetprop: create prop [ro.dalvik.vm.native.bridge]: [libriruloader.so] by modifying prop data structure
04-23 15:22:06.244   840   842 I Magisk  : riru-core: loading mount files
04-23 15:22:06.244   840   842 I Magisk  : riru_edxposed: loading [system.prop]
04-23 15:22:06.244   840   842 D Magisk  : resetprop: Parse prop file [/data/adb/modules/riru_edxposed/system.prop]
04-23 15:22:06.244   840   842 D Magisk  : resetprop: create prop [dalvik.vm.dex2oat-flags]: [--inline-max-code-units=0] by modifying prop data structure
04-23 15:22:06.244   840   842 I Magisk  : riru_edxposed: loading mount files
04-23 15:22:06.928   840   991 I Magisk  : ** late_start service mode running
04-23 15:22:06.928   840   991 I Magisk  : * Running service.d scripts
04-23 15:22:06.929   840   991 I Magisk  : * Running module service scripts
04-23 15:22:06.929   840   991 I Magisk  : riru-core: exec [service.sh]
04-23 15:22:06.932   931   931 I zygote  : option[51]=-XX:NativeBridge=libriruloader.so
04-23 15:22:07.139   840  1010 D Magisk  : su: request from pid=[997], client=[10]
04-23 15:22:07.139   840  1010 D Magisk  : su: request from uid=[0]
04-23 15:22:07.139   840  1010 D Magisk  : magiskdb: query magiskhide=[0]
04-23 15:22:07.141   840  1010 D Magisk  : su: waiting child pid=[1011]
04-23 15:22:07.158  1011  1011 D Magisk  : su: fork handler
04-23 15:22:07.165  1011  1011 D Magisk  : su: use namespace of pid=[997]
04-23 15:22:07.994  1015  1015 W rirud_java: Could not reserve sentinel fault page
04-23 15:22:08.217  1015  1015 I rirud_java: The ClassLoaderContext is a special shared library.
04-23 15:22:08.217  1015  1015 W rirud_java: Failed to find OatDexFile for DexFile /data/adb/modules/riru-core/rirud.dex (canonical path /data/adb/modules/riru-core/rirud.dex) in OatFile /data/adb/modules/riru-core/oat/arm/rirud.odex
04-23 15:22:08.277  1015  1015 D AndroidRuntime: Calling main entry riru.Daemon
04-23 15:22:08.280   853   853 I rirud   : forked process 1095
04-23 15:22:08.281  1095  1095 I rirud   : action: read original native bridge
04-23 15:22:08.292  1015  1015 D rirud_java: read native_bridge size 1
04-23 15:22:08.293  1095  1095 I rirud   : no next action, exiting...
04-23 15:22:08.293  1015  1015 I rirud_java: Original native bridge is 0
04-23 15:22:08.296  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:09.297  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:10.298  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:11.299  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:12.300  1015  1015 W rirud_java: Riru is not loaded.
04-23 15:22:12.300  1015  1015 W rirud_java: https://github.com/RikkaApps/Riru/issues/154#issuecomment-739128851
04-23 15:22:12.300  1015  1015 W rirud_java: Restarting zygote...
04-23 15:22:12.378  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:13.100  1214  1214 I zygote  : option[51]=-XX:NativeBridge=libriruloader.so
04-23 15:22:13.381  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:14.382  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:15.383  1015  1015 I rirud_java: Service activity not found, wait 1s...
04-23 15:22:16.384  1015  1015 W rirud_java: Riru is not loaded.
04-23 15:22:24.566  1286  1286 I PackageManager: tango: skipping APK pre-translation for org.meowcat.edxposed.manager
04-23 15:22:24.566  1286  1286 I PackageManager: tango: skipping shared library pre-translation for org.meowcat.edxposed.manager
04-23 15:22:29.558  1589  1589 I /system/bin/webview_zygote32: option[51]=-XX:NativeBridge=libriruloader.so
04-23 15:22:30.107   840  1852 D Magisk  : su: request from pid=[1844], client=[11]
04-23 15:22:30.107   840  1852 D Magisk  : su: request from uid=[1000]
04-23 15:22:30.107   840  1852 D Magisk  : magiskdb: query magiskhide=[0]
04-23 15:22:30.108   840  1852 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 15:22:30.136   840  1852 D Magisk  : su: waiting child pid=[1860]
04-23 15:22:30.137  1860  1860 D Magisk  : su: fork handler
04-23 15:22:30.138  1860  1860 D Magisk  : su: use namespace of pid=[1844]
04-23 15:22:30.224   840  1852 D Magisk  : su: return code=[0]
04-23 15:22:30.322   840  1869 D Magisk  : su: request from pid=[1865], client=[12]
04-23 15:22:30.322   840  1869 D Magisk  : su: request from uid=[1000]
04-23 15:22:30.334   840  1869 D Magisk  : su: waiting child pid=[1872]
04-23 15:22:30.348  1872  1872 D Magisk  : su: fork handler
04-23 15:22:30.351  1872  1872 D Magisk  : su: use namespace of pid=[1865]
04-23 15:22:30.508   840  1869 D Magisk  : su: return code=[0]
04-23 15:22:30.598   840  1887 D Magisk  : su: request from pid=[1884], client=[11]
04-23 15:22:30.598   840  1887 D Magisk  : su: request from uid=[1000]
04-23 15:22:30.612   840  1887 D Magisk  : su: waiting child pid=[1892]
04-23 15:22:30.630  1892  1892 D Magisk  : su: fork handler
04-23 15:22:30.634  1892  1892 D Magisk  : su: use namespace of pid=[1884]
04-23 15:22:30.732   840  1887 D Magisk  : su: return code=[0]
04-23 15:22:31.719  1286  1857 I ActivityManager:   ntv   ??   14778: rirud_java (pid 1015) native
04-23 15:22:31.802   840  1901 D Magisk  : su: request from pid=[1900], client=[12]
04-23 15:22:31.802   840  1901 D Magisk  : su: request from uid=[1000]
04-23 15:22:31.832   840  1901 D Magisk  : su: waiting child pid=[1906]
04-23 15:22:31.845  1906  1906 D Magisk  : su: fork handler
04-23 15:22:31.849  1906  1906 D Magisk  : su: use namespace of pid=[1900]
04-23 15:22:31.916   840  1901 D Magisk  : su: return code=[0]
04-23 15:22:32.237   840  1917 D Magisk  : su: request from pid=[1914], client=[11]
04-23 15:22:32.238   840  1917 D Magisk  : su: request from uid=[1000]
04-23 15:22:32.241   840  1918 D Magisk  : su: request from pid=[1915], client=[12]
04-23 15:22:32.241   840  1918 D Magisk  : su: request from uid=[1000]
04-23 15:22:32.245   840  1917 D Magisk  : su: waiting child pid=[1924]
04-23 15:22:32.258  1924  1924 D Magisk  : su: fork handler
04-23 15:22:32.260  1924  1924 D Magisk  : su: use namespace of pid=[1914]
04-23 15:22:32.261   840  1918 D Magisk  : su: waiting child pid=[1930]
04-23 15:22:32.276  1930  1930 D Magisk  : su: fork handler
04-23 15:22:32.283  1930  1930 D Magisk  : su: use namespace of pid=[1915]
04-23 15:22:32.338   840  1917 D Magisk  : su: return code=[0]
04-23 15:22:32.387   840  1918 D Magisk  : su: return code=[0]
04-23 15:22:32.457   840  1943 D Magisk  : su: request from pid=[1935], client=[13]
04-23 15:22:32.457   840  1943 D Magisk  : su: request from uid=[1000]
04-23 15:22:32.469   840  1943 D Magisk  : su: waiting child pid=[1946]
04-23 15:22:32.476  1946  1946 D Magisk  : su: fork handler
04-23 15:22:32.479  1946  1946 D Magisk  : su: use namespace of pid=[1935]
04-23 15:22:32.585   840  1943 D Magisk  : su: return code=[0]
04-23 15:22:32.681   840  1977 D Magisk  : su: request from pid=[1969], client=[11]
04-23 15:22:32.682   840  1977 D Magisk  : su: request from uid=[1000]
04-23 15:22:32.702   840  1977 D Magisk  : su: waiting child pid=[1981]
04-23 15:22:32.712  1981  1981 D Magisk  : su: fork handler
04-23 15:22:32.713  1981  1981 D Magisk  : su: use namespace of pid=[1969]
04-23 15:22:32.802   840  1977 D Magisk  : su: return code=[0]
04-23 15:22:32.872   840  1990 D Magisk  : su: request from pid=[1989], client=[12]
04-23 15:22:32.872   840  1990 D Magisk  : su: request from uid=[1000]
04-23 15:22:32.889   840  1990 D Magisk  : su: waiting child pid=[1993]
04-23 15:22:32.897  1993  1993 D Magisk  : su: fork handler
04-23 15:22:32.898  1993  1993 D Magisk  : su: use namespace of pid=[1989]
04-23 15:22:33.003   840  1990 D Magisk  : su: return code=[0]
04-23 15:22:33.115   840  2009 D Magisk  : su: request from pid=[2000], client=[11]
04-23 15:22:33.115   840  2009 D Magisk  : su: request from uid=[1000]
04-23 15:22:33.131   840  2009 D Magisk  : su: waiting child pid=[2013]
04-23 15:22:33.150  2013  2013 D Magisk  : su: fork handler
04-23 15:22:33.154  2013  2013 D Magisk  : su: use namespace of pid=[2000]
04-23 15:22:33.268   840  2009 D Magisk  : su: return code=[0]
04-23 15:22:35.605   840  2121 I Magisk  : ** boot_complete triggered
04-23 15:22:35.607   840  2121 D Magisk  : magiskdb: query magiskhide=[0]
04-23 15:22:35.804   840  2138 D Magisk  : su: request from pid=[2122], client=[11]
04-23 15:22:35.804   840  2138 D Magisk  : su: request from uid=[1000]
04-23 15:22:35.841   840  2138 D Magisk  : su: waiting child pid=[2143]
04-23 15:22:35.850  2143  2143 D Magisk  : su: fork handler
04-23 15:22:35.854  2143  2143 D Magisk  : su: use namespace of pid=[2122]
04-23 15:22:35.976   840  2138 D Magisk  : su: return code=[0]
04-23 15:22:37.827   840  2314 D Magisk  : su: request from pid=[2305], client=[13]
04-23 15:22:37.828   840  2314 D Magisk  : su: request from uid=[1000]
04-23 15:22:37.833   840  2314 D Magisk  : su: waiting child pid=[2317]
04-23 15:22:37.834  2317  2317 D Magisk  : su: fork handler
04-23 15:22:37.837  2317  2317 D Magisk  : su: use namespace of pid=[2305]
04-23 15:22:38.055   840  2314 D Magisk  : su: return code=[0]
04-23 15:22:43.673   840  2672 D Magisk  : su: request from pid=[2671], client=[11]
04-23 15:22:43.673   840  2672 D Magisk  : su: request from uid=[1000]
04-23 15:22:43.673   840  2672 D Magisk  : magiskdb: query magiskhide=[0]
04-23 15:22:43.673   840  2672 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 15:22:43.677   840  2672 D Magisk  : su: waiting child pid=[2676]
04-23 15:22:43.678  2676  2676 D Magisk  : su: fork handler
04-23 15:22:43.680  2676  2676 D Magisk  : su: use namespace of pid=[2671]
04-23 15:22:43.719   840  2672 D Magisk  : su: return code=[0]
04-23 15:22:43.737   840  2679 D Magisk  : su: request from pid=[2678], client=[13]
04-23 15:22:43.737   840  2679 D Magisk  : su: request from uid=[1000]
04-23 15:22:43.740   840  2679 D Magisk  : su: waiting child pid=[2682]
04-23 15:22:43.740  2682  2682 D Magisk  : su: fork handler
04-23 15:22:43.741  2682  2682 D Magisk  : su: use namespace of pid=[2678]
04-23 15:22:43.786   840  2679 D Magisk  : su: return code=[0]
04-23 15:22:43.821   840  2688 D Magisk  : su: request from pid=[2687], client=[11]
04-23 15:22:43.821   840  2688 D Magisk  : su: request from uid=[1000]
04-23 15:22:43.826   840  2688 D Magisk  : su: waiting child pid=[2691]
04-23 15:22:43.830  2691  2691 D Magisk  : su: fork handler
04-23 15:22:43.831  2691  2691 D Magisk  : su: use namespace of pid=[2687]
04-23 15:22:43.866   840  2688 D Magisk  : su: return code=[0]
04-23 15:22:43.893   840  2695 D Magisk  : su: request from pid=[2694], client=[13]
04-23 15:22:43.894   840  2695 D Magisk  : su: request from uid=[1000]
04-23 15:22:43.910   840  2695 D Magisk  : su: waiting child pid=[2699]
04-23 15:22:43.911  2699  2699 D Magisk  : su: fork handler
04-23 15:22:43.916  2699  2699 D Magisk  : su: use namespace of pid=[2694]
04-23 15:22:43.983   840  2695 D Magisk  : su: return code=[0]
04-23 15:22:44.039   840  2702 D Magisk  : su: request from pid=[2701], client=[11]
04-23 15:22:44.039   840  2702 D Magisk  : su: request from uid=[1000]
04-23 15:22:44.056   840  2702 D Magisk  : su: waiting child pid=[2705]
04-23 15:22:44.065  2705  2705 D Magisk  : su: fork handler
04-23 15:22:44.065  2705  2705 D Magisk  : su: use namespace of pid=[2701]
04-23 15:22:44.158   840  2702 D Magisk  : su: return code=[0]
04-23 15:23:38.673  1286  2783 I PackageManager: tango: skipping APK pre-translation for org.meowcat.edxposed.manager
04-23 15:23:38.673  1286  2783 I PackageManager: tango: skipping shared library pre-translation for org.meowcat.edxposed.manager
