### ISSUE TITLE
Edxposed framework stopped working after update

### ISSUE THREAD

**Issue by qwerty123000** [RikkaApps/Riru#155]
Hey man... After i updated riru from magisk. My edxposed manager and exposed framework stopped working. I reinstalled riru core, riru framework and edxposed manager but i encountered this problem. 
![Screenshot_20201202-210043185](https://user-images.githubusercontent.com/75373213/100875812-78913400-34e1-11eb-9c1c-8a05df120224.jpg)
And im having a hard time to install a previous versions of riru core because magisk wont let me install it.
![Screenshot_20201202-210147290](https://user-images.githubusercontent.com/75373213/100875910-9fe80100-34e1-11eb-9203-8e5700fe9d0a.jpg)
Does riru core can be installed through twrp?

**Comment by RikkaW** [comment]
ElderDrivers/EdXposed#665 💩

**Comment by RikkaW** [comment]
About TWRP, it's 2020, forget about it
