### ISSUE TITLE
How to enable the hide mechanism? 

### ISSUE THREAD

**Issue by yuhangrao** [RikkaApps/Riru#156]
After I flash the riru-core v23.0, I install the riru apk to check riru status. It show the hide mechanism is disabled. But I couldn't find a way to enable it. Won't it turn on automatically after flash? 
![Screenshot_20201203-082146~2](https://user-images.githubusercontent.com/28585220/100947951-b45be600-3541-11eb-92be-4ad040f0d6aa.png)

**Comment by LoganDark** [comment]
`touch /data/adb/riru/enable_hide` and reboot
