### ISSUE TITLE
EdXposed can't run this on my phone 

### ISSUE THREAD

**Issue by GitHub-Updates** [RikkaApps/Riru#158]
Edxposed (newest version) won't run this, I did download the "riru.apk" to check and it shows its working but edxposed says "framework not found" switched back to  older riru-core I was using and edxposed works again. Motorola G7 (River) - LineageOS. 

Thanks

**Comment by RikkaW** [comment]
Open an issue at EdXposed :)

**Comment by RikkaW** [comment]
"riru.apk" to check and it shows its working -> Riru does its jobs perfectly
