### ISSUE TITLE
Google Camera App Issue

### ISSUE THREAD

**Issue by RGBok** [RikkaApps/Riru#159]
When Riru is enabled I am unable to open the system camera app since it immediately crashes. 

**Device information:**
 - Device: Pixel 3a
 - OS: Android 11

You can email me at vvRGBvv@gmail.com for any additional information you need. Will gladly provide. I am unsure what else I need to submit here.

**Comment by RikkaW** [comment]
Please confirm this is tested with the latest version of Riru 
and otherr modules are disabled.

**Comment by RGBok** [comment]
Just disable the edxposed module and the issue is gone. Seems like I didn't identify the problem correctly. My bad. I guess its probably the edxposed or a module of that. Ill proceed down the chain from here.
