### ISSUE TITLE
Riru il2cpp dumper cant install in magisk after an update to version 23. 

### ISSUE THREAD

**Issue by jokerart06** [RikkaApps/Riru#160]
**Describe the bug:**
When installing updated riru core in magisk , its completely installed and activated in list then trying to install the riru il2cpp dumper in magisk its says riru core is not installed even its installed completely. Using android 9+ mobile devices . with rooted phone. 

**Device information:**
 - Device: Samsung J7 Core
 - OS: [e.g. Android 9 Rooted with magisk updated version. 
![riru dumper error](https://user-images.githubusercontent.com/54529030/101272326-b7b8c280-3737-11eb-8f2a-36e7e8173906.jpg)

**Additional context**

**Comment by RikkaW** [comment]
> Riru v22 has a new hide mechanism which makes detection "not that easy".
> 
> Because of this, all modules must change. If your module hasn't updated, ask the module developer to make changes. For 99% modules, this is super easy.

https://github.com/RikkaApps/Riru/releases/tag/v22.0
