### ISSUE TITLE
[23.0] Updated but Not Working Properly

### ISSUE THREAD

**Issue by mechtifs** [RikkaApps/Riru#161]
**Describe the bug:**
I have storage isolation and dreamland installed, however, after updating to riru 23.0 from 22.4, both of them are not functioning. Riru hide is disabled.

**Device information:**
 - Device: Smartisan U3 Pro
 - OS: Smartisan OS 6.0.3, Android 7.1.1
 - Magisk version: 20.4
 - Riru module version: 23.0
 - Storage Isolation app version: 5.0.0-rc02.r2795.fdf6cafd-arm64-v8a
 - Storage Isolation module version: 23.1
 - Dreamland module version: 2.0_beta9

**Additional context**
Here's the output of the Riru app:
```
Riru v23.0 (50, API v10) is in use.
Hide is disabled.

Native methods:
nativeForkAndSpecialize: ok
nativeForkSystemServer: ok

Loaded modules:
storage_redirect: v23.1 (51), api v10, support hide

File contents:
/data/adb/riru/dev_random: dbwTDEs
/dev/riru_dbwTDEs/api: 10
/dev/riru_dbwTDEs/hide: false
/dev/riru_dbwTDEs/version: 50
/dev/riru_dbwTDEs/version_name: v23.0
nativeForkAndSpecialize: true
(II[II[[IILjava/lang/String;Ljava/lang/String;[ILjava/lang/String;Ljava/lang/String;)I
nativeForkSystemServer: true
(II[II[[IJJ)I
/dev/riru_dbwTDEs/modules/storage_redirect/version_name: v23.1
/dev/riru_dbwTDEs/modules/storage_redirect/version: 51
/dev/riru_dbwTDEs/modules/storage_redirect/api: 10
/dev/riru_dbwTDEs/modules/storage_redirect/hide: true
```
Then I checked the logs. There were some warnings:
```
Riru
not zygote (cmdline=rirud_java)

StorageRedirectNative
no Riru found in zygote

Riru
not zygote (cmdline=app_process)

Riru
not zygote (cmdline=storage_isolation_cleaner)

Riru
not zygote (cmdline=storage_isolation)
```
It seems that dreamland wasn't even loaded btw.  
No computer at hand, thus I cannot provide full logcat for now. Sry for the inconveniences.

**Comment by RobertNissan** [comment]
me toca tener las versiones anteriores, ya que las últimas actualizaciones no funcionan en mi J7 Prime G610M con Android 9 pie.
Custom rom "Black Bird"

**Comment by RikkaW** [comment]
Riru itself has no change from v22.4 to v23.0.

You should provide the full log rather than only something you think useful.

**Comment by mechtifs** [comment]
> Riru itself has no change from v22.4 to v23.0.
> 
> You should provide the full log rather than only something you think useful.

Just to provide every single possible information I could get for now for possible workarounds.  
As I mentioned before, pc is currently inaccessible. Ofc I'll provide

**Comment by mechtifs** [comment]
> Riru itself has no change from v22.4 to v23.0.
> 
> You should provide the full log rather than only something you think useful.

Just to provide every single possible information I could get for now for possible workarounds.  
As I mentioned before, pc is currently inaccessible. Ofc I'll provide

**Comment by mechtifs** [comment]
Well I reinstalled all modules and dreamland works again while storage isolation is still not functioning... I may open a new issue there when I got the full logcat😕
