### ISSUE TITLE
[v23.0] riru EdXposed don't installed the actual version from magisk?

### ISSUE THREAD

**Issue by linuxdep** [RikkaApps/Riru#164]
**Describe the bug:**
after update my riru toolset to v23.0 i can't update/install Riru - EdXposed (YAHFA) v0.4.6.4 or older versions are fail. 
SandHook i had also tested, but the same.
I need this for XposedLua, this don't work anymore :-(

**Device information:**
 - HTC U11
 - OS: Android 9 (original - 1. Juli 2019 - 3.34.401.1)
 - Magisk v20.4
 - Magisk Manager v8.0.3
 - 

**Additional context**
Error message
Requirement module 'Riru - Core' is not installed or unsupportet v22+ is installed, use v21.3 instead.

Is it possible to fix ist, or is this not possible? Why Magisk show only this Version?

**Comment by yujincheng08** [comment]
You should have read the changelog of riru22+ or the pinned msg of edxp.

This issue will soon be marked as a stupid question.
