### ISSUE TITLE
Edxposed not loading 

### ISSUE THREAD

**Issue by Frwerewolf** [RikkaApps/Riru#165]
*Describe the bug:**
Since the last update of riru, my Edxposed v4.5.7 was not loading, no Exposed modules were loaded and the phone seems to be like unrooted. 
I had to go back to the before last version of riru to make it work again. (21.3). 

**Device information:**
Samsung galaxy note 10 +
Android P
Edxposed yahfa 

**Additional context**

**Comment by JasonKhew96** [comment]
Read Riru changelog before upgrading
https://github.com/ElderDrivers/EdXposed/issues/665
