### ISSUE TITLE
Riru detected by "PASS by SKT" even riru hide enabled

### ISSUE THREAD

**Issue by someone5678** [RikkaApps/Riru#166]
**Describe the bug:**
Riru detected by Korean security app called "PASS by SKT" even Riru hide enabled. I removed all Riru module(Edxp, Storage isolation) but issue persists. Disable or remove Riru resolve the issue.

**Device information:**
 - Device: Galaxy S9+
 - OS: One UI 2.5 (Q), Havoc-OS 3.11 (Q)

**Additional context**
Magisk Hide already enabled. With Magisk only, it can't detects root.
(You might want to remove Magisk Manager even it's hided. Because it detected.)

Riru status
![836](https://user-images.githubusercontent.com/59456192/102109846-daee1b00-3e77-11eb-906b-a68bcc814892.png)

APK link: https://apkcombo.com/pass-by-skt-–-운전면허증이-내-휴대폰속으로/com.sktelecom.tauth/

When Magisk hide not enabled or Riru detected, This message will be shown.
![Screenshot_20201215-014058~2](https://user-images.githubusercontent.com/59456192/102108866-c78e8000-3e76-11eb-9f9c-8210eb86e0c9.jpg)

**Comment by someone5678** [comment]
After update to today's 3.7.0 update, It doesn't detect Riru anymore. I don't know why but issue solved somehow so thread closed..

**Comment by someone5678** [comment]
"PASS by SKT" starts detecting Riru again in v3.7.3 update. So I re-open the issue.
Looks like they temporarily removed Riru detection and re-addded it.

Device: Galaxy S9+
OS: crDroid 7.2 (R)

![Screenshot_20210114-130300_PASS](https://user-images.githubusercontent.com/59456192/104543697-6a4e4000-5669-11eb-85fc-3ecdabbc7044.png)
Message changed slightly, but it's almost same. Please ignore that "/system/bin/su exists". They can't detect Magisk Canary 21201, when Magisk Hide is enabled. 

![Screenshot_20210114-130649_Riru](https://user-images.githubusercontent.com/59456192/104544051-3f182080-566a-11eb-8152-d49bf081b615.png)
Riru version is latest v23.3. And Riru Hide is enabled. Tested with all module removed and only Riru installed.

Although you can still download apk from Apkcombo, I also added Google Play link down below.

Google Play: https://play.google.com/store/apps/details?id=com.sktelecom.tauth

ApkCombo: https://apkcombo.com/pass-by-skt-–-운전면허증이-내-휴대폰속으로/com.sktelecom.tauth/

**Comment by RikkaW** [comment]
Nowhere to find the download for version 3.7.3

**Comment by someone5678** [comment]
> Nowhere to find the download for version 3.7.3

Sorry.. looks like apkcombo didn't updated for long time

https://mega.nz/file/WE52HBrL#KL2xw8IQGO0h_nljHg_GRc_wZ4lhCLcSiW5ajg9PF2Y

I directly extracted 3.7.3 from Play Store and upload it to Mega.

**Comment by RikkaW** [comment]
Works for me, maybe it detects some other things.
