### ISSUE TITLE
Riru core 23.0 shows as stable update in magisk

### ISSUE THREAD

**Issue by fusionneur** [RikkaApps/Riru#167]
Version 23 is definetely not stable and it only works with edxposed canary and only on certain builds. I had to revert twice in latest weeks, and also compromised the device's privacy when edxposed was not working properly, or even boot looped the device once.

Version 21.3 is the only one that actually works with edxposed alpha 0.4.6.4 (4563) yahfa, and this version should show in magisk, or else people update and break their phones or leak data.

**Comment by RikkaW** [comment]
"My app stop working with Android 11, Android 11 is not stable"
