### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by fusionneur** [RikkaApps/Riru#169]
@rikkaw  Stop being an asshole dev and support your app. Why close issues with stupid tag instead of acknowledging them or eventually ask for more info.
And why is there such a passive aggressive tag. Grow up people, be professional. Don't expect to have support and respect from testers or other developers if you treat us like shit.
If you can't handle it, then leave others handle it. What's the purpose of open source if you only do as you please?

**Comment by RikkaW** [comment]
They are all for EdXposed and there already enough info:
1. EdXposed's installer: install lastest canary version or downgrade Riru
2. Riru's issue template: only submit issues related to Riru itself
3. Changelog of Riru v22: don't upgrade until modules are updated

Why do you think these people should get "support and respect" when they show no respect first?

By the way, before publish to Magisk's repo, Riru v22 gives modules for nearly two months to update. And the devs of EdXposed know this in the very beginning.

**Comment by fusionneur** [comment]
ignorant

**Comment by fusionneur** [comment]
so sad too waste such good brains on such personality

**Comment by fusionneur** [comment]
I perfectly understand that edxposed is resposible of the crashes. 

But you need to work close to them and since riru core is most commonly used for edxposed, having an incompatible version in the magisk store will get a lot of people's phones bricked. So .. once again.. someone (you or whoever) must downgrade the version from magisk store to be compatible with the edxposed version.

**Comment by RikkaW** [comment]
> By the way, before publish to Magisk's repo, Riru v22 gives modules for **nearly two months** to update. And the devs of EdXposed know this in the very beginning.

It is **long enough**. Riru is NOT only for EdXposed, why do you think other modules should wait for it?

Stop giving wrong ideas, old module with new Riru leads nothing rather than "lot of people's phones bricked" (same to not installed) 🙃.
