### ISSUE TITLE
Request adaptation TWRP mode brush in

### ISSUE THREAD

**Issue by scarlet-glass** [RikkaApps/Riru#17]
Is it suitable for TWRP brush - in? My Nubia machine could not use magisk to install the module because of the BUG in F2FS itself.

**Comment by lijun0326** [comment]
硬核brush机

**Comment by switchtegrax1** [comment]
You can use the latest magisk Canary version,it no longers uses an EXT4 image so it works even on devices with buggy f2fs,https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337

**Comment by 2220209876** [comment]
一直都能rec里刷吧。。。
