### ISSUE TITLE
I have an error installing modules that require riru

### ISSUE THREAD

**Issue by 3goodm** [RikkaApps/Riru#170]
every time I try to install a module, which requires riru it shows me that I do not have riru installed and I already have it installed: ((
![Screenshot_20201217-221728](https://user-images.githubusercontent.com/76194801/102574135-aa93c000-40b5-11eb-9bdf-90d30ca95340.png)
![Screenshot_20201217-221701](https://user-images.githubusercontent.com/76194801/102574137-ab2c5680-40b5-11eb-9401-6015c41d9523.png)

**Comment by RikkaW** [comment]
ElderDrivers/EdXposed#665
