### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by ffuser1** [RikkaApps/Riru#171]
![2020-12-19 13 16 22](https://user-images.githubusercontent.com/42816218/102699241-82fd3e80-4200-11eb-86df-b6a8a07566f4.png)

The new version will install but won't work because the sandhook module won't install. I think this has happened since 22, as I use 21-3

**Comment by DrSaad77** [comment]
Exactly the same is happening to me!!!
I even installed the new Riru apk, to check that Riru is installed correctly and it is!
But no way to install EdXposed SandHook, so how are we supposed to installed our modules???
![Screenshot_20201219-231732_Riru](https://user-images.githubusercontent.com/36936960/102699879-0b0b3480-4251-11eb-98c7-a4abfec4899b.jpg)

**Comment by elesbb** [comment]
Download the EdXposed Manager apk from the EdXposed manager GitHub.
Choose "Canary" tab and install that version. You can try the alpha too, but I think canary is needed. EdXposed manager will say Xposed is installed but not active. Ignore that as it is active and works. You will then need to toggle the option under EdXposed manager settings to skip checking if Xposed is active.

**Comment by ffuser1** [comment]
Then it should be clarified somewhere that in order to use the newest version of riru, you must run the canary version of sandhook (and I assume the other one also). The alpha version is what we are trying to re-install.

**Comment by elesbb** [comment]
@ffuser1 

It is. You have to Google. Its posted int he ElderDriver's github

**Comment by DrSaad77** [comment]
Thx you, I finally found the solution in Telegram Group.
As said you should use the Canary Version of SandHook or Yahfa.
It can be installed from EdXposed Manager.
