### ISSUE TITLE
Riru Core Make Me Lost Access To Phone Storage

### ISSUE THREAD

**Issue by SonJeremy** [RikkaApps/Riru#173]
**Describe the bug:**
I can't access to phone storage when install Riru Core V23.1. 
**Device information:**
 - Device: Nokia 3.1 (ES2)
 - OS: Android One 10

**Comment by RikkaW** [comment]
It's highly possible caused by something else rather Riru itself.

**Comment by SonJeremy** [comment]
Riru V23.0 is OK. Let me check again.

**Comment by SonJeremy** [comment]
This issues maybe due by App Ops. Sorry for wrong issue.
