### ISSUE TITLE
Screen timeout

### ISSUE THREAD

**Issue by Rezazahmad** [RikkaApps/Riru#174]
The last version (23.1) keeps the screen awake and ignores the screen timeout. 
System info: Xiaomi Note 8 Pro (Android 10)

**Comment by RikkaW** [comment]
Impossible for Riru itself to affect screen timeout.

**Comment by Rezazahmad** [comment]
Hey Rikka, 
Thanks for the module. 
I have frozen the whole apps and found no change. Therefore I deactivated the Magisk modules and reactivated them one after another and reset my phone every time and I found Riru is the one which affects the screen timeout. Please rest assured that I am right about this. I can even send you a video.
