### ISSUE TITLE
如何在不使用magisk的情况下内置riru进系统？

### ISSUE THREAD

**Issue by kk599** [RikkaApps/Riru#175]
在老版本中直接替换文件可以内置进系统，在22+后尝试相同的方法无效

**Comment by RikkaW** [comment]
其实弄回换文件的实现是最方便的（但是想做只能自己做

否则就需要保证：
1. 有改 prop 的能力
2. 能运行 rirud 或是能保证 zygote 有权读取需要的文件们

**Comment by HimekoEx** [comment]
还是建议用虚拟机搞, 改系统配置容易炸鸡
我自己搓的利用脚本刷入Riru的项目 [HimekoEx/Riru-Shell](https://github.com/HimekoEx/Riru-Shell)

目前只有 `v21.3`
最新的 `API9` 以上的已经折腾好了, 但是得等调试优化, 估计过几天会更

VMOS刷入的成果
![image](https://user-images.githubusercontent.com/49508376/104708456-b5934c00-5758-11eb-99db-5e647f2d5e39.png)

**Comment by kk599** [comment]
riru23.3已在真机上内置成功，感谢大佬的指导

**Comment by kk599** [comment]
> 其实弄回换文件的实现是最方便的（但是想做只能自己做
> 
> 否则就需要保证：
> 
> 1. 有改 prop 的能力
> 2. 能运行 rirud 或是能保证 zygote 有权读取需要的文件们

感谢大佬的指点，已在真机内置23.3成功，还有似乎不运行rirud也能正常工作
