### ISSUE TITLE
can't install on android 10

### ISSUE THREAD

**Issue by Bk3rZ** [RikkaApps/Riru#177]
**Describe the bug:**
 - app info "Riru not found in memory"
 - using latest magisk 21.2
 - installed latest Riru 23.1
 - no other modules installed.

**Device information:**
 - Device: samsung s8+
 - OS: android 10, custom rom -> Havoc, based on pixel

**Additional context
trying to overcome safetynet fail.

**Comment by RikkaW** [comment]
Upgrade Riru app.
