### ISSUE TITLE
where i can get newer version than 23.1?

### ISSUE THREAD

**Issue by Bk3rZ** [RikkaApps/Riru#178]
sorry, but 23.1 is as latest available to download on magisk or here?

---------------------------------------------------------
Describe the bug:

    app info "Riru not found in memory"
    using latest magisk 21.2
    installed latest Riru 23.1
    no other modules installed.

Device information:

    Device: samsung s8+
    OS: android 10, custom rom -> Havoc, based on pixel

**Additional context
trying to overcome safetynet fail.
---------------------------------------------------------
@RikkaW
Member

Upgrade Riru app.

**Comment by RikkaW** [comment]
Upgrade Riru app.

**Comment by Bk3rZ** [comment]
stupid indeed...i was after magisk module instead of app. apologies.
