### ISSUE TITLE
riru core 23.2 magisk 21.2 conflict

### ISSUE THREAD

**Issue by 7wells** [RikkaApps/Riru#180]
Hello, please consider this issue described there:
https://github.com/Magisk-Modules-Repo/riru_edxposed/issues/2

**Comment by JasonKhew96** [comment]
https://github.com/ElderDrivers/EdXposed/issues/665

**Comment by 7wells** [comment]
"Stupid issue"? ;D

Anyway, thanks @JasonKhew96 for the hint over there. 👍
