### ISSUE TITLE
虚拟机 /dev 目录无法访问导致rirud内部读取失败

### ISSUE THREAD

**Issue by HimekoEx** [RikkaApps/Riru#181]
在虚拟机APP(vmos等)中部分目录并没有访问权限
其中就有 `/dev`, 我自己改了一下路径, 可以使用
建议再加一层判断,如果无法访问 `/dev` 目录的话

弱弱的问一句, 我这个菜逼能给大佬的项目添一份用于类虚拟机使用的Riru安装脚本吗. 

搓了好几天的成果
![image](https://user-images.githubusercontent.com/49508376/104707946-0fdfdd00-5758-11eb-8894-2f1a46b05d70.png)

**Comment by RikkaW** [comment]
`/dev` 存在的意义是让 rirud_java 及有 root 权限的程序得知 Riru 的信息，其中 rirud_java 是用来重启因为隐藏目的而暂停的 rirud。虚拟机应该是没有隐藏的意义吧（

**Comment by HimekoEx** [comment]
> `/dev` 存在的意义是让rirud_java及具有root权限的程序调用Riru的信息，其中rirud_java是重新启动因为隐藏目的而暂停的rirud。虚拟机应该是没有隐藏的意义吧（

虚拟机确实没隐藏的意义, 但是有些邪乎的虚拟机APP不会被检测到, `rirud_java` 重启 `rirud` 是在开机状态下重启么, 还是不太懂这玩意

**Comment by RikkaW** [comment]
rirud 的存在意义是让 zygote 能借此（rirud 开了一个 context 是 zygote 的 socket）读取不能读的文件（指 `/data/adb` 里的），你的那种虚拟机极有可能是 SELinux 宽容模式，所以 rirud 其实也是不需要的（

**Comment by HimekoEx** [comment]
所以大大有做备用的储存位置的想法吗, 没有的话就算了
