### ISSUE TITLE
When attempting to install Riru - EdXposed

### ISSUE THREAD

**Issue by SavageTheUnicorn** [RikkaApps/Riru#182]
It fails every time saying that I need to use release 21.3 but i cant find a download link for the old version anywhere. I do in fact have Riru 23.3 installed as well. Any suggestions? ![Screenshot_20210116-050328 1](https://user-images.githubusercontent.com/57853203/104810111-4a796200-57b8-11eb-9bbe-7f40c07a162a.jpg)

**Comment by RikkaW** [comment]
They already have new versions for months, check their GitHub page.
