### ISSUE TITLE
更新至最新版riru后开机卡死，疑似内存溢出

### ISSUE THREAD

**Issue by TsXor** [RikkaApps/Riru#185]
**bug描述**
在已经刷入riru23.3和edxposed最新SandHook稳定版后再刷入riru23.4（最新的release），开机后卡死

**设备信息**
设备：华为平板M510.8寸全网通（CMR-AL09）
操作系统：EMUI9.1-Android9

**附加信息**
勉强能操作，但是非常卡，最终都只能强制重启
初步猜测是内存溢出（edxp传统艺能）

**Comment by RikkaW** [comment]
E 什么 d Xposed 这个质量超低的东西是第一嫌疑人，以及 issue 模板里都说了其他模块都关了再来（

Riru 本体是非常简单的，另外本体的行为已经非常久没有变化了，瞎甩锅也要有个限度
