### ISSUE TITLE
靜讀天下 無法正常使用

### ISSUE THREAD

**Issue by at01076172** [RikkaApps/Riru#19]
Android Pie, Magisk V18.1, Riru V13(V11也是同樣的情況)
無任何模組啟用的情況下，靜讀天下(Moon+ Reader)正常載入

僅啟用Riru的情況下，從畫面判斷 此APP會載入到一半就卡住不動了，
有時甚至就是載入了一個全黑的畫面而已

如果還需要提供任何訊息，我會盡快提供，謝謝！

**Comment by Keriteal** [comment]
在magisk hide里面把静读天下打上钩就可以了

**Comment by at01076172** [comment]
實測有效，感謝你的回覆
