### ISSUE TITLE
Riru Causes Random Reboots

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [RikkaApps/Riru#190]
Riru version: 23.6
Magisk version: 22.0
Device: Samsung Galaxy Note9 (SM-GN960F)
OS: One UI 2.5 (Android 10)

As per title. Below is how I determined the problem is caused by Riru:

About 20 days ago I flashed my phone with the official One UI 2.5. Ever since that, my phone has been rebooting randomly, roughly twice a day. 

At first I thought it was a hardware problem. But the tests for my flash drive, ram and other sensors all said normal.

Then I moved onto software problems like dm-verity, Safety Net, etc. I ended up resetting my phone and left it blank, with only the apps I need daily installed. However the phone still rebooted after a few hours. At that time the only Magisk module installed was Riru 23.5.

I began to suspect Riru caused the reboot, so I unistalled Riru. My phone has not rebooted for once for a week. Last night, I reinstalled Riru 23.6, and just now my phone rebooted again.

The reboots were not entirely random. They mostly happen when I swiped down the notification bar, turned on the torch, launched the camera app, or even pressed the Bixby button. They all seemed to have something to do with the system itself.

I collected some of the ramoops logs stored at /sys/fs/pstore and attached them. I compared these with logs after app induced reboots and found them to be completely different.

I'm not sure if this is an OS-variant-specific problem, i.e. only devices with this specific OS version would encounter this problem since Googling this problem returned nothing.

Peace

[ramoopses.zip](https://github.com/RikkaApps/Riru/files/6048277/ramoopses.zip)

**Comment by frnksmdlkedjnfr** [comment]
Edit:

I ran Dumpstate/Logcat, and went to /log/eRR.p, found the most recent abnormal reboot. The log went:

REASON: (uid 0, pid: 22584, processName: app_process)

Some google indicates that app_process is related to zygote, the core where Riru runs

**Comment by RikkaW** [comment]
First, if you don't see the first screen of a normal boot (for example, normal "first screen" of Pixel devices https://source.android.com/security/images/boot_orange.png), it's very likely that something causes zygote to restart. In such cases, the normal logcat rather than kernel-related log should be helpful.

Second, Riru does not have a process that has the name "app_process". Anything started with app_process has a default name "app_process".

**Comment by frnksmdlkedjnfr** [comment]
> First, if you don't see the first screen of a normal boot (for example, normal "first screen" of Pixel devices https://source.android.com/security/images/boot_orange.png), it's very likely that something causes zygote to restart. In such cases, the normal logcat rather than kernel-related log should be helpful.
> 
> Second, Riru does not have a process that has the name "app_process". Anything started with app_process has a default name "app_process".

Here's the [link](https://cowtransfer.com/s/ed35fd082f5b47) to 5 logs collected immediately after abnormal reboots (somehow Google Drive isn't working for me, **CODE: 423751**): . After the last reboot I disabled Riru, and my phone hasn't rebooted once ever since just like last time. 

Samsung really be messing around with Galaxy Note9's software in the recent updates. Some even report completely greened out screens after certain updates. I don't know if the logs would help tackle the reboot problem. But as a Note9 user I sincerely hope to use Riru modules as everyone else.

Peace

**Comment by RikkaW** [comment]
For your case, what I want is "adb logcat", your weird dumps do not help.

1. Change "Logger buffer size" to the maximum in "Developer options".
2. To prove your problem is about Riru itself, **disable all Riru modules** and other Magisk modules. **Your weird dumps show you didn't do this. 👎**
3. Start "adb logcat" when your device "reboots".
4. Open a new issue

**Comment by RikkaW** [comment]
> You can disable other modules to confirm if the problem comes from Riru itself.

Since you have totally ignored this in the issue template, this issue is marked as "stupid issue"
