### ISSUE TITLE
应用程序运行异常

### ISSUE THREAD

**Issue by Vstory** [RikkaApps/Riru#198]
**Information:**

- Riru version: 25.1.0 debug
- Magisk version: 22.0
- All other modules are disabled: Yes
- Device: Xiaomi Note 3
- OS: MIUI  12 20.6.18
- Android: 9.0

**Logs:**

1. 仅启用 Riru -Core 模块：
2. [all_2021-03-17_21-20-27.zip](https://github.com/RikkaApps/Riru/files/6156671/all_2021-03-17_21-20-27.zip)

2.启用隔离存储空间 模块 v23.6：
[隔离存储空间模块_all_2021-03-17_21-25-41.zip](https://github.com/RikkaApps/Riru/files/6156697/_all_2021-03-17_21-25-41.zip)

**Describe the bug:**

1. 仅启用 Riru - Core  v25.1.0 模块时，黑阈 `me.piebridge.brevent` 运行正常。

2. 启用隔离存储空间模块后，黑阈 `me.piebridge.brevent` 运行报错。

![Screenshot_2021-03-17-21-23-24-996_me piebridge brevent](https://user-images.githubusercontent.com/20795557/111475428-0549c000-8768-11eb-864b-8cce43844bac.jpg)

**Additional context:**

![Snipaste_2021-03-17_21-31-00](https://user-images.githubusercontent.com/20795557/111475496-198dbd00-8768-11eb-8c50-78f5a184b760.png)

![Snipaste_2021-03-17_21-32-43](https://user-images.githubusercontent.com/20795557/111475699-56f24a80-8768-11eb-9b00-e715825f8001.png)

**Comment by RikkaW** [comment]
等所有模块都升级到 25 就没问题了

**Comment by RikkaW** [comment]
当然也可以先把 24 的把名字抹掉加回来（

**Comment by Vstory** [comment]
> 当然也可以先把 24 的把名字抹掉加回来（

手动把这个目录 `/data/adb/riru/modules/` 下的 Riru 模块的 `module.prop` 改成 24？

**Comment by RikkaW** [comment]
用 25.2.0（

**Comment by Vstory** [comment]
> 等所有模块都升级到 25 就没问题了

这个不是一两天的是🤷‍♂️

> 用 25.2.0（

Rikka yyds!✨
