### ISSUE TITLE
关于内存查找

### ISSUE THREAD

**Issue by makegame007** [RikkaApps/Riru#2]
感觉无需从runtime里查找nativeForkAndSpecialize的函数指针，从android的版本可以直接判断出nativeForkAndSpecialize的参数列表。

还有一个，文档里说要求是6.0以上的设备？我看代码，也支持6.0以下的，nativeForkAndSpecialize的参数列表要再修改下。

**Comment by RikkaW** [comment]
不暴力搜内存的话要怎么找到 nativeForkAndSpecialize 的地址呢？
不根据 Android 版本判断的理由是，万一用户设备上的和 Android 版本并不对应，再去 RegisterNatives 就会 爆炸（

支持 6.0 以下是肯定可以的（

**Comment by makegame007** [comment]
HI, 有个不解之处load_modules，加载模块so，模块so里是要求一定要有moduleLoaded。但是在location_report_enabler的工程里里没有发现这个函数。很不解，求示意

**Comment by RikkaW** [comment]
没有一定要有呀（

**Comment by makegame007** [comment]
兄弟，是一定要有了，对吧。但是在location_report_enabler的工程里确实没有发现这个函数呀

**Comment by makegame007** [comment]
老兄，还有个问题，关于加载顺序的问题要请教个，理论是先加载libmemtrack在先，再加载目标APP的dex. 但是日志有点奇怪，先打印了目标APP的dex，再打印出libmemtrack的日志。可能是是什么原因出现这种现象？

**Comment by makegame007** [comment]
老兄，还有个问题，关于加载顺序的问题要请教下，理论是先加载libmemtrack，再加载目标APP的dex. 但是从打印日志来看有点奇怪，先打印了目标APP的dex里的日志，后打印出libmemtrack的日志。可能是什么原因导致出现这种现象？
