### ISSUE TITLE
samsung oreo riru issue

### ISSUE THREAD

**Issue by Jasi2169** [RikkaApps/Riru#20]
Edit sorry wrong title it should have been samsung pie issue by mistake wrote oreo

Riru v13 found.
However, native methods of Zygote class not replaced, please contact developer with the following information.

nativeForkAndSpecializeSignature:
(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I

getNativeForkSystemServerSignature:
(II[II[[IJJ)I

**Comment by RikkaW** [comment]
Try https://github.com/RikkaApps/Riru/releases/tag/v14

**Comment by Jasi2169** [comment]
V15 fixed it all samsung stock pie roms working on s9 and note9 and s8 beta

Riru v15 found.
Native methods of Zygote class replaced.

nativeForkAndSpecialize calls count: 392
nativeForkSystemServer calls count: 1

Everything looks fine :D
