### ISSUE TITLE
Riru v25 does not load

### ISSUE THREAD

**Issue by Kazurin-775** [RikkaApps/Riru#203]
### Information:

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: v25.3.3 debug
- Magisk version: 22.0 (22000)
- Android version: 11 (Project Sakura, LineageOS-like)
- Device: Xiaomi MI 6X (wayne)

### Logs:

Full boot log: [logcat-20210324-2207.log](https://github.com/RikkaApps/Riru/files/6197900/logcat-20210324-2207.log)

### Describe the bug:

After an update to Riru v25, the Riru app shows that Riru is not installed, and all Riru modules do not take effect.

The logcat says:

```
01-12 16:44:53.231   801   801 E Riru    : dlopen /dev/6nEXc9/.magisk/modules/riru-core/lib/libriru.so: dlopen failed: library "/dev/6nEXc9/.magisk/modules/riru-core/lib/libriru.so" not found
01-12 16:44:53.238   800   800 E Riru64  : dlopen /dev/6nEXc9/.magisk/modules/riru-core/lib64/libriru.so: dlopen failed: library "/dev/6nEXc9/.magisk/modules/riru-core/lib64/libriru.so" not found
```

But these 2 files do exist if I check them manually, e.g.:

```
wayne:/ # ls -lZ /dev/6nEXc9/.magisk/modules/riru-core/lib/libriru.so
-rw-r--r-- 1 root root u:object_r:system_file:s0  1982708 2021-03-24 22:05 /dev/6nEXc9/.magisk/modules/riru-core/lib/libriru.so
```

**Comment by RikkaW** [comment]
`01-12 16:44:53.236   800   800 W main    : type=1400 audit(0.0:123): avc: denied { search } for name="riru-core" dev="mmcblk0p64" ino=1089616 scontext=u:r:zygote:s0 tcontext=u:object_r:adb_data_file:s0 tclass=dir permissive=0`

This is the root cause, the context for at least one of the folders at every level of `/dev/6nEXc9/.magisk/modules/riru-core/lib(64)` has become `u:object_r:adb_data_file:s0`. Please check it.

Under normal circumstances, `modules` and its child should have `u:object_r:system_file:s0` context.

**Comment by Kazurin-775** [comment]
You're right, it seems that `modules/riru-core` and `modules/riru-core/{lib,lib64,system}` are automatically relabelled to `u:object_r:adb_data_file:s0` during boot, but other files like `module.prop` remain unchanged. Strange.

I think there is no SELinux magic installed or running. What other information should I provide?

**Comment by RikkaW** [comment]
Try reset them back to `u:object_r:system_file:s0`, does it get relabelled again after reboot?

I know everything in `/data` will be "restorecon" on boot, but `init` does not have permission to run `restorecon` on `system_file`.

```
W init    : type=1400 audit(0.0:111): avc: denied { relabelfrom } for name="modules" dev="dm-5" ino=23017 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir permissive=0
```

Use `magiskpolicy --save` to save current policies to a file and use `sesearch`, `sesearch --allow -s init -t system_file -p relabelfrom`, to check if `init` has the permission.

**Comment by Kazurin-775** [comment]
> Try reset them back to `u:object_r:system_file:s0`, does it get relabelled again after reboot?

Yes. I followed your instructions, and found out that `init` actually has relabel permission on **directories**:

```
$ sesearch --allow -s init -t system_file -p relabelfrom test.policy
allow init system_file:dir { add_name getattr ioctl lock mounton open read relabelfrom remove_name rmdir search watch watch_reads write };
```

On the other hand, `init` does not have permission to relabel **files**, so all files stay unchanged. This is almost consistent with my observation (except for `/data/adb/modules/` itself, which remains `system_file` for unknown reason).

Is this due to the ROM I'm using?

**Comment by RikkaW** [comment]
To access a file, the `search` permission of upper folders is required, so if the folders are relabeled, the zygote cannot access the file inside.

Maybe your ROM maintainer added the rule incorrectly.

**Comment by shengruoyu** [comment]
> 
> 
> Try reset them back to `u:object_r:system_file:s0`, does it get relabelled again after reboot?
> 
> I know everything in `/data` will be "restorecon" on boot, but `init` does not have permission to run `restorecon` on `system_file`.
> 
> ```
> W init    : type=1400 audit(0.0:111): avc: denied { relabelfrom } for name="modules" dev="dm-5" ino=23017 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir permissive=0
> ```
> 
> Use `magiskpolicy --save` to save current policies to a file and use `sesearch`, `sesearch --allow -s init -t system_file -p relabelfrom`, to check if `init` has the permission.

I followed the posts above, and got this:

> sesearch: inaccessible or not found

**Comment by Kazurin-775** [comment]
> `sesearch: inaccessible or not found`

`sesearch` belongs to Linux package `setools`. See https://github.com/SELinuxProject/setools.

This issue is already closed, so please do not comment if your information is off-topic. Thanks for your support.
