### ISSUE TITLE
Updated v25.3.3, can't use google feed anymore.

### ISSUE THREAD

**Issue by nictse2013** [RikkaApps/Riru#204]
everything ok before update......

**Comment by VD171** [comment]
Did you check if that is not a problem with the webview? 
https://www.xda-developers.com/google-confirms-webview-issue-crashing-android-apps/

**Comment by nictse2013** [comment]
> Did you check if that is not a problem with the webview?
> https://www.xda-developers.com/google-confirms-webview-issue-crashing-android-apps/

Thx I uninstall webview update, but still no luck for now....
