### ISSUE TITLE
在magsik 22版本中安装失败

### ISSUE THREAD

**Issue by 1608637229** [RikkaApps/Riru#205]
版本v25.33, magsik版本是最新的22，
安装失败：错误提示要版本20.4+，所以是目前还不支持22版吗。
还是说22版本会与Riru有冲突呢。系统是miui 10, 安卓9.

**Comment by RikkaW** [comment]
但是应该你安装的 Magisk 的环境可能是损坏的（

**Comment by 1608637229** [comment]
你说的对。我挂梯子从magsik商店下的文件确实有问题，
我从github这边下载后就直接刷进去了。不知道是什么问题导致的，以前也是直接在
magsik仓库直接下载都可以直接刷进去。
