### ISSUE TITLE
LDPlayer 4 emulator freezing after boot when Riru is installed

### ISSUE THREAD

**Issue by Toshiba1127** [RikkaApps/Riru#206]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: No other modules are installed since this is the first time attempting to use Magisk on emulator
- Riru version: v25.3.3.r393.ed83041(393)
- Magisk version: v21.4
- Android version: 7.1.1
- Device: (optional): LDPlayer 4.0.53, disguise as Samsung SM-G960N

**Logcat:**

https://pastebin.com/P6RKfQgj

**Installation Logs:**

![image](https://user-images.githubusercontent.com/64008639/112626787-f9799000-8e30-11eb-95cc-46e35d66da58.png)

**Describe the bug:**

The emulator freeze up as soon as it booted into launcher.

**Additional context:**

I followed this guide to install Magisk on LDPlayer 4 https://forum.xda-developers.com/t/guide-magisk-supersu-and-xposed-for-memu-7-3-2-or-ldplayer-4-0-45.4222919/post-84580333
Magisk working perfectly with root access

**Comment by RikkaW** [comment]
From the log, it seems the reason is installd not start, but no other clues.

Additionally,
```
2021-03-26 12:39:19.164 1203-1203/? I/appproc: exec app_process! cmdline: -Xzygote /system/bin --zygote --start-system-server 
...
2021-03-26 12:39:24.620 2026-2030/? I/Magisk: ** post-fs-data mode running
```
Magisk runs **later** than the zygote, under normal circumstances this shouldn't happen. We can conclude that Magisk on such devices is broken, anything could happen.

**Comment by Toshiba1127** [comment]
Oh RIP, then i will try other emulators
