### ISSUE TITLE
Riru not installed or not enabled.

### ISSUE THREAD

**Issue by shengruoyu** [RikkaApps/Riru#209]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: v25.3.4
- Magisk version: 66e30a77(2206)
- Android version: 11AOSP
- Device: sagit

**Logs:**

[dmesgonlyriru.log](https://github.com/RikkaApps/Riru/files/6226384/dmesgonlyriru.log)

**Describe the bug:**

之前使用 Magisk v22 + Riru v25.3.3 一切正常，不明操作之后 Riru 突然失效，Riru 检测提示：
![Screenshot_20210330-133839(1)](https://user-images.githubusercontent.com/9843486/112939141-88521980-915d-11eb-81c4-bfe237cdce1b.png)

LSPsoed 提示 Losposed is not currently installed or active。

尝试使用 Magisk Canary 并升级 Riru 至 v25.3.3 依然如此。

失效当天曾进行的可能有影响的操作：
曾安装 [Hide My Applist](https://github.com/Dr-TSNG/Hide-My-Applist)  并对某些 APP 设置不可见Magisk、LSPosed等；
曾安装 Riru - Location Report Enabler。
 
**Additional context:**

**Comment by RikkaW** [comment]
Seems same to #203, SELinux context of Magisk module folders are reseted to `u:object_r:adb_data_file:s0`, so zygote can't access files in them.

> https://github.com/RikkaApps/Riru/issues/203#issuecomment-807025002

It's highly possible your ROM's problem since AOSP does is explicitly disallow `init` to relable `system_files`.

**Comment by shengruoyu** [comment]
It's weired that it did work fine days ago. I have done nothing to the ROM.
