### ISSUE TITLE
Riru doesn't work on the Samsung Galaxy A41! 

### ISSUE THREAD

**Issue by ShamiDead-kali** [RikkaApps/Riru#210]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes]
- Riru version: 23+ (to the last)
- Magisk version: 22006 Canary
- Android version: 10
- Device: Samsung Galaxy A41

**LOG**

[Logcat.txt](https://drive.google.com/file/d/1L3DAWk8TiwiWWC018vB_H_CHGvUlNG6O/view?usp=sharing) 

**Describe the bug:**

I install Riru and the phone goes into a cyclical reboot. The smartphone turns on the desktop and after a while hangs then restart.

**Additional context:**

Maybe the KNOX is acting on it somehow.

**Comment by ShamiDead-kali** [comment]
*LOG*

https://drive.google.com/file/d/1L3DAWk8TiwiWWC018vB_H_CHGvUlNG6O/view?usp=sharing

**Comment by RikkaW** [comment]
```
04-01 10:45:19.649   738   738 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7fd2286000 in tid 738 (keystore), pid 738 (keystore)
```

KeyStore crashed, this is the reason. Theoretically, Riru does nothing to `keystore` since `keystore` is started directly by `init`, Riru only affect `zygote`.

Does your problem still exist after disabling Riru? If the problem still exists, try to create and install a Magisk module with `sepolicy.rule` which content is `allow crash_dump keystore *` and catch log again so that further investigations can be done.


```
04-01 10:45:19.673   536   536 E audit   : type=1400 audit(1617252319.667:251): avc:  denied  { ptrace } for  pid=3385 comm="crash_dump64" scontext=u:r:crash_dump:s0 tcontext=u:r:keystore:s0 tclass=process permissive=0 SEPF_SM-A415F_10_0025 audit_filtered
```

**Comment by ShamiDead-kali** [comment]
There are no problems after the disable Riru.

**Comment by RikkaW** [comment]
> If the problem still exists, because of crash dump does not have permission to ptrace keystore, it's required to create and install a Magisk module with `sepolicy.rule` which content is `allow crash_dump keystore *`. Then catch log again so that further investigations can be done.

**Comment by ShamiDead-kali** [comment]
_install a Magisk module with sepolicy.rule_

Where do I get such a module?

**Comment by yujincheng08** [comment]
> Except Riru itself, all other Magisk modules are disabled: [Yes]

You are not doing so.

>  bind_mnt: /system/bin/keystore <- /sbin/.magisk/modules/safetynet-fix/system/bin/keystore
