### ISSUE TITLE
Riru 25本身和使用Riru-API 25的模块合作似乎有问题

### ISSUE THREAD

**Issue by notxx** [RikkaApps/Riru#211]
我的安装环境是
硬件: Mi MiX2s polaris
操作系统: PixelExperience_Plus_polaris-11.0-20210327-1844-OFFICIAL
Magisk: 22.0(22000)

单独安装Riru 25是可以正常运作的
如果安装依赖于Riru的模块，但是这些模块是不使用Riru-API 25的，也可以正常运作
但是如果安装的模块使用Riru-API 25，就会造成Riru本身也失效（Riru APP会检测不到Riru）

目前测试过会造成Riru 25失效的模块包括Riru - LSPosed（包括v1.3.3和v1.3.4）和Riru - Enhanced mode for Storage Isolation（riru-storage-isolation-v24.0.0-release.zip）

**Comment by RikkaW** [comment]
开机 log（

**Comment by notxx** [comment]
这是正常状态下的logcat
[logcat-2.log](https://github.com/RikkaApps/Riru/files/6254104/logcat-2.log)
但是很奇怪selinux也有报错的，马上来收集Riru损害状态的logcat

**Comment by notxx** [comment]
这个是损坏状态的logcat
[logcat-3.log](https://github.com/RikkaApps/Riru/files/6254112/logcat-3.log)

**Comment by notxx** [comment]
然后重新确认了一下刷入Riru - Enhanced mode for Storage Isolation（riru-storage-isolation-v24.0.0-release.zip）是不会损坏Riru本体的，但是不能正确生效（存储空间隔离app中提示和增强模块无法连接）。
奇怪的是，如果用旧版Riru就可以生效。

**Comment by RikkaW** [comment]
全部的 log 都太晚了
开发者设置里日志缓冲区大小开到最大再来
然后还有用 canary 版的 Magisk
