### ISSUE TITLE
Riru v23.3.4 and LSposed v1.3.4 makes the phone cycle restart!

### ISSUE THREAD

**Issue by ShamiDead-kali** [RikkaApps/Riru#212]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: [No] (LSposed v1.3.4)
- Riru version: 25.3.4
- Magisk version: Canary 22006
- Android version: 10
- Device: Samsung Galaxy A41 SM-A415F

**Logs:**

--------- beginning of main
04-04 13:00:24.617   370   370 I SELinux : SELinux: Loaded service_contexts from:
04-04 13:00:24.618   370   370 I SELinux :     /system/etc/selinux/plat_service_contexts
04-04 13:00:24.628   371   371 I hwservicemanager: hwservicemanager is ready now.
04-04 13:00:24.629   384   384 E DSMS-LIB: Failed to open /data/local/dsms/preboot.log : No such file or directory
04-04 13:00:24.640   375   375 E cutils-trace: Error opening trace file: Permission denied (13)
04-04 13:00:24.640   371   371 E cutils-trace: Error opening trace file: Permission denied (13)
04-04 13:00:24.641   375   375 I ServiceManagement: Registered vendor.samsung.frameworks.security.dsms@1.0::ISehDsms/default (start delay of 57ms)
04-04 13:00:24.642   375   375 I ServiceManagement: Removing namespace from process name vendor.samsung.frameworks.security.dsms@1.0-service to dsms@1.0-service.

[FULL LOG.txt](https://drive.google.com/file/d/1djbNQW26TZAIPNhlQE4RtMuxftY_mdJD/view?usp=drivesdk)

**Describe the bug:**

Riru v25.3.4 and LSposed v1.3.4 makes the phone cycle restart! There are no other modules! KNOX is disabled!

**Comment by fiftydinar** [comment]
Same here with latest Exposed module on ArrowOS Android 11, POCO X3 NFC. I had to do clean flash of the ROM. I even got a message in TWRP that my phone activated Rescue Party?

**Comment by ShamiDead-kali** [comment]
RikkaW HELP PLEASE!

**Comment by RikkaW** [comment]
Everything looks fine from your log.
Does the problem still exist when only Riru itself is enabled?

**Comment by ShamiDead-kali** [comment]
Да, проблема остаётся

**Comment by ShamiDead-kali** [comment]
Have you looked at the full log?

**Comment by RikkaW** [comment]
> Everything looks fine from your log.

There are even logs of the start of android apps in the last part.

> 不愿透露姓名的西大师：The version of log catcher you are using seems too old, it ends when the device boots. Switch to the new version so that it will stop after unlocking.

**Comment by ShamiDead-kali** [comment]
> > 不愿透露姓名的西大师：The version of log catcher you are using seems too old, it ends when the device boots. Switch to the new version so that it will stop after unlocking. https://t.me/hzrtools/10

Okay, I'll try it tomorrow. I also want to ask what this means: **E cutils-trace: Error opening trace file: Permission denied (13)**

**Comment by ShamiDead-kali** [comment]
> 不愿透露姓名的西大师：The version of log catcher you are using seems too old, it ends when the device boots. Switch to the new version so that it will stop after unlocking. https://t.me/hzrtools/10

I made a new log.

**Comment by ShamiDead-kali** [comment]
**NewLog

https://drive.google.com/file/d/13LIvIDcgO5g1BmyBzfFb_fB7SkbEr_JQ/view?usp=drivesdk

**Comment by ShamiDead-kali** [comment]
>https://t.me/hzrtools/10

I did it.

**Boot.log:**

https://drive.google.com/file/d/18pj8PYJ_Zb7-8GvoLYzjBE7K8monXzJl/view?usp=drivesdk

**Comment by RikkaW** [comment]
@ShamiDead-kali It seems the logcat on your device does not include crash buffer by default. This could explain why everything looks fine because crash logs are missing.

Use `adb logcat -b main,system,crash` manually or this 
[modified version of Log Catcher-v21](https://github.com/RikkaApps/Riru/files/6301335/Log.Catcher-v21.21.zip) to catch a new log.

**Comment by ShamiDead-kali** [comment]
Due to the debug version of Riru, the phone does not turn on at all. Hangs on the inscription Samsung.

**Comment by ShamiDead-kali** [comment]
>modified version of Log Catcher-v21

I'll try it in a few hours.

**Comment by ShamiDead-kali** [comment]
A new version has been released - 25.4.1, should I install it?

**Comment by ShamiDead-kali** [comment]
>modified version of Log Catcher-v21

**I did this, and learned two logs:**

**After the first reboot:**

https://drive.google.com/file/d/19Dr67SrxVro8ehThD_b1dlg2O5iljcbx/view?usp=drivesdk

**After a cyclic reboot:**

https://drive.google.com/file/d/19AkNojLg9SUSa5nM55hdZz6mTvRiafPG/view?usp=drivesdk

**Comment by ShamiDead-kali** [comment]
Rikka, help please))

**Comment by ShamiDead-kali** [comment]
What should I do next?

**Comment by ShamiDead-kali** [comment]
Спасибо за помощь (
Теперь мне придётся просто менять телефон (
Потому что Самсунг не поддерживает Ваш Riru (

**Comment by ShamiDead-kali** [comment]
RIKKKKKKAAAAAAAAAAAWWWWWWWWWW!

**Comment by ShamiDead-kali** [comment]
HELP!

**Comment by h0nus** [comment]
Having same issue :)

**Comment by RikkaW** [comment]
With the help of another Samsung user, I got some very strange conclusions.
The phenomenon is that once zygote loads our library, even if the library is "empty" (do nothing inside), he will still encounter his problem. His problem is the device becomes laggy after boot.

Maybe I can conclude that Samsung has some weird limitations, disallow some special process to use libraries from non-system partition. Magisk module files are not in system partition, even if they looks in `/system`. This may be similar to Samsung's other limitation, disallow uid 0 (root) to execute executable files in the non-system partition. If this is true, nothing I can do.

Maybe you can try to use a third-party kernel (if there is), they should not have Samsung's weird limitations.

**Comment by dr-kaisar** [comment]
@ShamiDead-kali Did you find any solution?

**Comment by dr-kaisar** [comment]
Does this issue occur in all the Samsung phones? Or only a few phones face this issue?
