### ISSUE TITLE
riru好像对苏宁易购有bug

### ISSUE THREAD

**Issue by njtony11** [RikkaApps/Riru#214]
xprivacylua无法挂住苏宁易购，我查看了日志有一个苏宁的错误，我联系了xprivacylua开发者，他说“This is a bug in Riru.”
我把riru换成V23.0还是一样的错误，我想反馈一下，谢谢

Riru version: v25.3.4.r399.84f7084 (399)
Magisk version: 22.1 (22100)
Android version: P3A，11
Edxposed：0.5.2.2_4683

Logs:
04-10 11:45:26.389  5323  5323 I EdXposed: Riru hooks installed
04-10 11:45:26.452  5323  5323 I EdXposed: ART hooks installed
04-10 11:45:26.522  5311  5311 I EdXposed-Bridge: XLua.Xposed Loaded com.android.traceur:10090
04-10 11:45:26.532  5323  5323 I EdXposed: Loading modules for com.suning.mobile.ebuy
04-10 11:45:26.532  5323  5323 I EdXposed-Bridge: Loading modules from /data/app/~~hcjuv6HzQbZOKMB3ug7WSw==/eu.faircode.xlua-vNspZ6pSQTrjHf23gYkdcA==/base.apk
04-10 11:45:26.572  5323  5323 I EdXposed-Bridge:   Loading class eu.faircode.xlua.XLua
04-10 11:45:26.806  5359  5359 I EdXposed: Start to install inline hooks
04-10 11:45:26.806  5359  5359 I EdXposed: Using api level 30
04-10 11:45:26.806  5359  5359 I EdXposed: Start to install Riru hook
04-10 11:45:26.907  5323  5323 E EdXposed: error when hooking bindApp: pkg=com.suning.mobile.ebuy, prc=com.suning.mobile.ebuy
04-10 11:45:26.907  5323  5323 E EdXposed: java.lang.ArrayIndexOutOfBoundsException: length=1052; index=1263817555
04-10 11:45:26.907  5323  5323 E EdXposed: 	at pxb.android.axml.AxmlParser.getNamespacePrefix(AxmlParser.java:151)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at pxb.android.axml.AxmlReader.accept(AxmlReader.java:80)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at com.elderdrivers.riru.edxp.util.MetaDataReader.<init>(MetaDataReader.java:27)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at com.elderdrivers.riru.edxp.util.MetaDataReader.getMetaData(MetaDataReader.java:19)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.HandleBindApp.beforeHookedMethod(HandleBindApp.java:69)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:361)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at SandHookerNew_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:51)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at android.os.Looper.loop(Looper.java:223)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-10 11:45:26.907  5323  5323 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-10 11:45:26.935  5359  5359 I EdXposed: Riru hooks installed
04-10 11:45:26.983  5359  5359 I EdXposed: ART hooks installed

**Comment by yujincheng08** [comment]
https://github.com/ElderDrivers/EdXposed/issues/846

Stop using Edxp.
