### ISSUE TITLE
Riru Manager app does not install

### ISSUE THREAD

**Issue by r1Ns3** [RikkaApps/Riru#215]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: No
- Riru version: Latest
- Magisk version: 66e30a77 (22006)
- Android version: 11
- Device: Pixel 3

**Logs:**

In the log of installing the riru through magisk, it says the app is not installed despite me creating the folder that you specified (/data/adb/modules/riru-core/allow_install_app )

**Describe the bug:**

The module installation fails installing the riru manager app.

**Additional context:**

I haven't provided logs because I do not know how to.

**Comment by RikkaW** [comment]
Save the module installation log from Magisk.

**Comment by r1Ns3** [comment]
![image](https://user-images.githubusercontent.com/19488222/114297863-788beb00-9af6-11eb-9f4d-168a32057839.png)

**Comment by RikkaW** [comment]
Actually what I want is the log from the save button, but it's enough for this case.

> In the log of installing the riru through magisk, it says the app is not installed despite me creating the **folder** that you specified (/data/adb/modules/riru-core/allow_install_app )

> To allow the module install the app, create a **file** named /data/adb/modules/riru-core/allow_install_app.

Create a file rather than a folder

**Comment by r1Ns3** [comment]
> 
> 
> Actually what I want is the log from the save button, but it's enough for this case.
> 
> > In the log of installing the riru through magisk, it says the app is not installed despite me creating the **folder** that you specified (/data/adb/modules/riru-core/allow_install_app )
> 
> > To allow the module install the app, create a **file** named /data/adb/modules/riru-core/allow_install_app.
> 
> Create a file rather than a folder

How am I meant to create a file? I used mkdir in adb

**Comment by RikkaW** [comment]
`touch /data/adb/modules/riru-core/allow_install_app` (rm your folder first

**Comment by r1Ns3** [comment]
[magisk_install_log_2021-04-11T19_14_33Z.log](https://github.com/RikkaApps/Riru/files/6291444/magisk_install_log_2021-04-11T19_14_33Z.log)


Did as you said, still didn't install app.

**Comment by RikkaW** [comment]
`stat /data/adb/modules/riru-core/allow_install_app`

**Comment by r1Ns3** [comment]
Thank you, I don't know how but I guess I must have messed it up the first time.
