### ISSUE TITLE
Failure to update Riru

### ISSUE THREAD

**Issue by gallegonovato** [RikkaApps/Riru#216]
Good morning:

I have on my Nexus 5 lineageos 17.1. More specifically: https://forum.xda-developers.com/t/rom-unofficial-lineageos-17-1-for-nexus-5-hammerhead.4039273/ . And on other terminals also unofficials versions.

I have the latest version of Magisk and Magisk Manager.

Yesterday I got a warning in Magisk new version of Riru. I hit update as usual. But it does not install. I tried to install it via local, from storage with Magisk. And neither.

I look at https://github.com/RikkaApps/Riru/releases under debug. And from Magisk I try to install. But nothing.

I look at:

Bundle app with the module (Create file /data/adb/modules/riru-core/allow_install_app to allow the module to install the app)

I have Amaze from fdroid. With super user permissions. I go to that path I notice I don't have a file with that name and create it. I reboot the system. I try to update Riru again. But nothing.

I check with trwp that the file is still there. And it is. But there is no way to update.

Always https://ibb.co/z7JJTPq (which can not be updated).

Is there any solution.

Best regards

**Comment by RikkaW** [comment]
https://github.com/z3DD3r/android_device_lge_hammerhead/blob/lineage-17.1/sepolicy/init.te#L13
https://github.com/RikkaApps/Riru/wiki/Explanation-about-incorrect-SELinux-rules-from-third-party-ROMs-cause-Riru-not-working

Tell your ROM maintainer that some denials are intended behavior 🙃.
