### ISSUE TITLE
Incorrect SELinux rules

### ISSUE THREAD

**Issue by ljszx** [RikkaApps/Riru#218]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: v25.4.1.r411.22618ad (Riru API 25)
- Magisk version: 22102
- Android version:11 (PixelExperience)
- Device: Xiaomi Mi 9 (cepheus)

**Logs:**

[Logs](https://del.dog/amucodirud.txt)

**Describe the bug:**

Cannot update to v25.4.1.r411.22618ad. It says 
```
- Checking if your ROM has incorrect SELinux rules
! Your ROM has incorrect SELinux rules
```
And I've checked your [wiki](https://github.com/RikkaApps/Riru/wiki/Explanation-about-incorrect-SELinux-rules-from-third-party-ROMs-cause-Riru-not-working). But there's no any rules about system_file relabelfrom according to the [device tree](https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/blob/eleven/sepolicy/vendor/init.te).

What could be the cause then?

Thank you for your time!

**Comment by tehcneko** [comment]
@EcrosoftXiao

**Comment by EcrosoftXiao** [comment]
> **Information:**
> 
> * Except Riru itself, all other Magisk modules are disabled: Yes
> * Riru version: v25.4.1.r411.22618ad (Riru API 25)
> * Magisk version: 22102
> * Android version:11 (PixelExperience)
> * Device: Xiaomi Mi 9 (cepheus)
> 
> **Logs:**
> 
> [Logs](https://del.dog/amucodirud.txt)
> 
> **Describe the bug:**
> 
> Cannot update to v25.4.1.r411.22618ad. It says
> 
> ```
> - Checking if your ROM has incorrect SELinux rules
> ! Your ROM has incorrect SELinux rules
> ```
> 
> And I've checked your [wiki](https://github.com/RikkaApps/Riru/wiki/Explanation-about-incorrect-SELinux-rules-from-third-party-ROMs-cause-Riru-not-working). But there's no any rules about system_file relabelfrom according to the [device tree](https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/blob/eleven/sepolicy/vendor/init.te).
> 
> What could be the cause then?
> 
> Thank you for your time!

> @EcrosoftXiao

Fixed.
https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/commit/44a8bdc20cd8d8e22dd877565552410211629155
https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/commit/3ad71d0b4d3335f6795776f8f9c5ed6b17331a92
https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/commit/89177d437ddb7b363df7a734aaecec8462c02e3d

**Comment by EcrosoftXiao** [comment]
> > **Information:**
> > 
> > * Except Riru itself, all other Magisk modules are disabled: Yes
> > * Riru version: v25.4.1.r411.22618ad (Riru API 25)
> > * Magisk version: 22102
> > * Android version:11 (PixelExperience)
> > * Device: Xiaomi Mi 9 (cepheus)
> > 
> > **Logs:**
> > [Logs](https://del.dog/amucodirud.txt)
> > **Describe the bug:**
> > Cannot update to v25.4.1.r411.22618ad. It says
> > ```
> > - Checking if your ROM has incorrect SELinux rules
> > ! Your ROM has incorrect SELinux rules
> > ```
> > 
> > 
> > And I've checked your [wiki](https://github.com/RikkaApps/Riru/wiki/Explanation-about-incorrect-SELinux-rules-from-third-party-ROMs-cause-Riru-not-working). But there's no any rules about system_file relabelfrom according to the [device tree](https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/blob/eleven/sepolicy/vendor/init.te).
> > What could be the cause then?
> > Thank you for your time!
> 
> > @EcrosoftXiao
> 
> Fixed.
> [PixelExperience-Devices/device_xiaomi_cepheus@44a8bdc](https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/commit/44a8bdc20cd8d8e22dd877565552410211629155)
> [PixelExperience-Devices/device_xiaomi_cepheus@3ad71d0](https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/commit/3ad71d0b4d3335f6795776f8f9c5ed6b17331a92)
> [PixelExperience-Devices/device_xiaomi_cepheus@89177d4](https://github.com/PixelExperience-Devices/device_xiaomi_cepheus/commit/89177d437ddb7b363df7a734aaecec8462c02e3d)

Thnx sar.
