### ISSUE TITLE
Riru is not loaded.

### ISSUE THREAD

**Issue by CNoob4ever** [RikkaApps/Riru#221]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version:  v25.4.2.r415
- Magisk version:  22102
- Android version: 8.1
- Device: (optional)

**Logs:**

4-23 18:37:28.753   840   840 I Magisk  : Magisk c4e8dda3(22102) daemon started
04-23 18:37:28.753   840   840 W Magisk  : Can't switch cgroup
04-23 18:37:28.753   840   840 I Magisk  : * Device API level: 27
04-23 18:37:28.763   840   842 E Magisk  : mount (null)->/ failed with 16: Device or resource busy
04-23 18:37:28.765   840   842 D Magisk  : resetprop: getprop [ro.crypto.state]: [unsupported]
04-23 18:37:28.765   840   842 D Magisk  : resetprop: getprop [init.svc.vold]: [running]
04-23 18:37:28.765   840   842 I Magisk  : ** post-fs-data mode running
04-23 18:37:28.766   840   842 I Magisk  : * Mounting mirrors
04-23 18:37:28.766   840   842 I Magisk  : mount: /sbin/.magisk/mirror/data
04-23 18:37:28.766   840   842 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
04-23 18:37:28.766   840   842 I Magisk  : mount: /sbin/.magisk/mirror/system
04-23 18:37:28.766   840   842 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
04-23 18:37:28.766   840   842 I Magisk  : mount: /sbin/.magisk/mirror/system
04-23 18:37:28.767   840   842 E Magisk  : mount /sbin/.magisk/block/data->/sbin/.magisk/mirror/data failed with 16: Device or resource busy
04-23 18:37:28.767   840   842 I Magisk  : mount: /sbin/.magisk/mirror/data
04-23 18:37:28.767   840   842 I Magisk  : link: /sbin/.magisk/mirror/vendor
04-23 18:37:28.767   840   842 I Magisk  : * Initializing Magisk environment
04-23 18:37:28.794   840   842 D Magisk  : resetprop: read prop from [/data/property/persist.sys.safemode]
04-23 18:37:28.795   840   842 D Magisk  : resetprop: getprop (persist) [persist.sys.safemode]: [0]
04-23 18:37:29.336   840   842 I Magisk  : * Running post-fs-data.d scripts
04-23 18:37:29.342   840   842 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:37:29.343   840   842 D Magisk  : bind_mnt: /sbin/.magisk/modules <- /sbin/.magisk/mirror/data/adb/modules
04-23 18:37:29.343   840   842 E Magisk  : open: /sys/fs/selinux/context failed with 2: No such file or directory
04-23 18:37:29.349   840   842 I Magisk  : * Running module post-fs-data scripts
04-23 18:37:29.353   847   847 I Magisk  : riru-core: exec [post-fs-data.sh]
04-23 18:37:29.390   849   849 I rirud   : backup original native bridge 0
04-23 18:37:29.431   849   849 I rirud   : Magisk version is 22102
04-23 18:37:29.457   849   849 I rirud   : Magisk tmpfs path is /sbin
04-23 18:37:29.459   847   847 I Magisk  : riru_edxposed: exec [post-fs-data.sh]
04-23 18:37:29.459   853   853 E rirud   : setsockcreatecon failed with 22: Invalid argument
04-23 18:37:29.459   853   853 I rirud   : socket rirud created
04-23 18:37:30.580   840   842 I Magisk  : * Loading modules
04-23 18:37:30.580   840   842 I Magisk  : riru-core: loading [system.prop]
04-23 18:37:30.580   840   842 D Magisk  : resetprop: Parse prop file [/data/adb/modules/riru-core/system.prop]
04-23 18:37:30.580   840   842 D Magisk  : resetprop: delete prop [ro.dalvik.vm.native.bridge]
04-23 18:37:30.580   840   842 D Magisk  : resetprop: create prop [ro.dalvik.vm.native.bridge]: [libriruloader.so] by modifying prop data structure
04-23 18:37:30.580   840   842 I Magisk  : riru-core: loading mount files
04-23 18:37:30.580   840   842 I Magisk  : riru_edxposed: loading [system.prop]
04-23 18:37:30.580   840   842 D Magisk  : resetprop: Parse prop file [/data/adb/modules/riru_edxposed/system.prop]
04-23 18:37:30.580   840   842 D Magisk  : resetprop: create prop [dalvik.vm.dex2oat-flags]: [--inline-max-code-units=0] by modifying prop data structure
04-23 18:37:30.580   840   842 I Magisk  : riru_edxposed: loading mount files
04-23 18:37:31.248   931   931 I zygote  : option[51]=-XX:NativeBridge=libriruloader.so
04-23 18:37:31.463   840  1002 I Magisk  : ** late_start service mode running
04-23 18:37:31.463   840  1002 I Magisk  : * Running service.d scripts
04-23 18:37:31.463   840  1002 I Magisk  : * Running module service scripts
04-23 18:37:31.463   840  1002 I Magisk  : riru-core: exec [service.sh]
04-23 18:37:31.780   840  1019 D Magisk  : su: request from pid=[1005], client=[10]
04-23 18:37:31.780   840  1019 D Magisk  : su: request from uid=[0]
04-23 18:37:31.780   840  1019 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:37:31.787   840  1019 D Magisk  : su: waiting child pid=[1032]
04-23 18:37:31.800  1032  1032 D Magisk  : su: fork handler
04-23 18:37:31.802  1032  1032 D Magisk  : su: use namespace of pid=[1005]
04-23 18:37:32.691  1035  1035 W rirud_java: Could not reserve sentinel fault page
04-23 18:37:33.006  1035  1035 I rirud_java: The ClassLoaderContext is a special shared library.
04-23 18:37:33.006  1035  1035 W rirud_java: Failed to find OatDexFile for DexFile /data/adb/modules/riru-core/rirud.dex (canonical path /data/adb/modules/riru-core/rirud.dex) in OatFile /data/adb/modules/riru-core/oat/arm/rirud.odex
04-23 18:37:33.091  1035  1035 D AndroidRuntime: Calling main entry riru.Daemon
04-23 18:37:33.095   853   853 I rirud   : forked process 1113
04-23 18:37:33.097  1113  1113 I rirud   : action: read original native bridge
04-23 18:37:33.104  1035  1035 D rirud_java: read native_bridge size 1
04-23 18:37:33.104  1035  1035 I rirud_java: Original native bridge is 0
04-23 18:37:33.106  1113  1113 I rirud   : no next action, exiting...
04-23 18:37:33.107  1035  1035 I rirud_java: Service activity not found, wait 1s...
04-23 18:37:34.108  1035  1035 I rirud_java: Service activity not found, wait 1s...
04-23 18:37:35.109  1035  1035 W rirud_java: Riru is not loaded.
04-23 18:37:35.109  1035  1035 W rirud_java: https://github.com/RikkaApps/Riru/issues/154#issuecomment-739128851
04-23 18:37:35.110  1035  1035 W rirud_java: Restarting zygote...
04-23 18:37:35.183  1035  1035 I rirud_java: Service activity not found, wait 1s...
04-23 18:37:36.184  1035  1035 I rirud_java: Service activity not found, wait 1s...
04-23 18:37:36.213  1197  1197 I zygote  : option[51]=-XX:NativeBridge=libriruloader.so
04-23 18:37:37.187  1035  1035 I rirud_java: Service activity not found, wait 1s...
04-23 18:37:38.187  1035  1035 I rirud_java: Service activity not found, wait 1s...
04-23 18:37:39.188  1035  1035 W rirud_java: Riru is not loaded.
04-23 18:37:41.036  1419  1419 I /system/bin/webview_zygote32: option[51]=-XX:NativeBridge=libriruloader.so
04-23 18:37:41.905   840  1695 D Magisk  : su: request from pid=[1692], client=[11]
04-23 18:37:41.905   840  1695 D Magisk  : su: request from uid=[1000]
04-23 18:37:41.905   840  1695 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:37:41.908   840  1695 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 18:37:41.929   840  1695 D Magisk  : su: waiting child pid=[1699]
04-23 18:37:41.939  1699  1699 D Magisk  : su: fork handler
04-23 18:37:41.941  1699  1699 D Magisk  : su: use namespace of pid=[1692]
04-23 18:37:42.036   840  1695 D Magisk  : su: return code=[0]
04-23 18:37:42.096   840  1709 D Magisk  : su: request from pid=[1707], client=[12]
04-23 18:37:42.096   840  1709 D Magisk  : su: request from uid=[1000]
04-23 18:37:42.118   840  1709 D Magisk  : su: waiting child pid=[1712]
04-23 18:37:42.133  1712  1712 D Magisk  : su: fork handler
04-23 18:37:42.135  1712  1712 D Magisk  : su: use namespace of pid=[1707]
04-23 18:37:42.221   840  1709 D Magisk  : su: return code=[0]
04-23 18:37:42.304   840  1719 D Magisk  : su: request from pid=[1718], client=[11]
04-23 18:37:42.304   840  1719 D Magisk  : su: request from uid=[1000]
04-23 18:37:42.330   840  1719 D Magisk  : su: waiting child pid=[1723]
04-23 18:37:42.346  1723  1723 D Magisk  : su: fork handler
04-23 18:37:42.349  1723  1723 D Magisk  : su: use namespace of pid=[1718]
04-23 18:37:42.457   840  1719 D Magisk  : su: return code=[0]
04-23 18:37:43.087  1264  1675 I ActivityManager:   ntv   ??    8485: rirud_java (pid 1035) native
04-23 18:37:43.346   840  1736 D Magisk  : su: request from pid=[1734], client=[12]
04-23 18:37:43.346   840  1736 D Magisk  : su: request from uid=[1000]
04-23 18:37:43.374   840  1736 D Magisk  : su: waiting child pid=[1745]
04-23 18:37:43.386  1745  1745 D Magisk  : su: fork handler
04-23 18:37:43.386  1745  1745 D Magisk  : su: use namespace of pid=[1734]
04-23 18:37:43.471   840  1736 D Magisk  : su: return code=[0]
04-23 18:37:43.773   840  1768 D Magisk  : su: request from pid=[1761], client=[11]
04-23 18:37:43.773   840  1768 D Magisk  : su: request from uid=[1000]
04-23 18:37:43.794   840  1768 D Magisk  : su: waiting child pid=[1776]
04-23 18:37:43.794   840  1773 D Magisk  : su: request from pid=[1762], client=[12]
04-23 18:37:43.794   840  1773 D Magisk  : su: request from uid=[1000]
04-23 18:37:43.804  1776  1776 D Magisk  : su: fork handler
04-23 18:37:43.806  1776  1776 D Magisk  : su: use namespace of pid=[1761]
04-23 18:37:43.828   840  1773 D Magisk  : su: waiting child pid=[1782]
04-23 18:37:43.857  1782  1782 D Magisk  : su: fork handler
04-23 18:37:43.863  1782  1782 D Magisk  : su: use namespace of pid=[1762]
04-23 18:37:43.918   840  1768 D Magisk  : su: return code=[0]
04-23 18:37:44.002   840  1773 D Magisk  : su: return code=[0]
04-23 18:37:44.088   840  1796 D Magisk  : su: request from pid=[1787], client=[13]
04-23 18:37:44.088   840  1796 D Magisk  : su: request from uid=[1000]
04-23 18:37:44.104   840  1796 D Magisk  : su: waiting child pid=[1808]
04-23 18:37:44.115  1808  1808 D Magisk  : su: fork handler
04-23 18:37:44.116  1808  1808 D Magisk  : su: use namespace of pid=[1787]
04-23 18:37:44.236   840  1796 D Magisk  : su: return code=[0]
04-23 18:37:44.364   840  1836 D Magisk  : su: request from pid=[1831], client=[11]
04-23 18:37:44.364   840  1836 D Magisk  : su: request from uid=[1000]
04-23 18:37:44.399   840  1836 D Magisk  : su: waiting child pid=[1846]
04-23 18:37:44.405  1846  1846 D Magisk  : su: fork handler
04-23 18:37:44.406  1846  1846 D Magisk  : su: use namespace of pid=[1831]
04-23 18:37:44.501   840  1836 D Magisk  : su: return code=[0]
04-23 18:37:44.566   840  1850 D Magisk  : su: request from pid=[1849], client=[12]
04-23 18:37:44.566   840  1850 D Magisk  : su: request from uid=[1000]
04-23 18:37:44.621   840  1850 D Magisk  : su: waiting child pid=[1855]
04-23 18:37:44.634  1855  1855 D Magisk  : su: fork handler
04-23 18:37:44.635  1855  1855 D Magisk  : su: use namespace of pid=[1849]
04-23 18:37:44.721   840  1850 D Magisk  : su: return code=[0]
04-23 18:37:44.807   840  1859 D Magisk  : su: request from pid=[1858], client=[11]
04-23 18:37:44.807   840  1859 D Magisk  : su: request from uid=[1000]
04-23 18:37:44.827   840  1859 D Magisk  : su: waiting child pid=[1865]
04-23 18:37:44.846  1865  1865 D Magisk  : su: fork handler
04-23 18:37:44.857  1865  1865 D Magisk  : su: use namespace of pid=[1858]
04-23 18:37:44.985   840  1859 D Magisk  : su: return code=[0]
04-23 18:37:47.055   840  1947 I Magisk  : ** boot_complete triggered
04-23 18:37:47.055   840  1947 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:37:47.623   840  2024 D Magisk  : su: request from pid=[2011], client=[11]
04-23 18:37:47.623   840  2024 D Magisk  : su: request from uid=[1000]
04-23 18:37:47.638   840  2024 D Magisk  : su: waiting child pid=[2031]
04-23 18:37:47.644  2031  2031 D Magisk  : su: fork handler
04-23 18:37:47.646  2031  2031 D Magisk  : su: use namespace of pid=[2011]
04-23 18:37:47.813   840  2024 D Magisk  : su: return code=[0]
04-23 18:37:49.198   840  2130 D Magisk  : su: request from pid=[2128], client=[13]
04-23 18:37:49.198   840  2130 D Magisk  : su: request from uid=[1000]
04-23 18:37:49.225   840  2130 D Magisk  : su: waiting child pid=[2133]
04-23 18:37:49.243  2133  2133 D Magisk  : su: fork handler
04-23 18:37:49.244  2133  2133 D Magisk  : su: use namespace of pid=[2128]
04-23 18:37:49.420   840  2130 D Magisk  : su: return code=[0]
04-23 18:37:58.666   840  2504 D Magisk  : su: request from pid=[2503], client=[11]
04-23 18:37:58.666   840  2504 D Magisk  : su: request from uid=[1000]
04-23 18:37:58.667   840  2504 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:37:58.668   840  2504 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 18:37:58.678   840  2504 D Magisk  : su: waiting child pid=[2508]
04-23 18:37:58.679  2508  2508 D Magisk  : su: fork handler
04-23 18:37:58.682  2508  2508 D Magisk  : su: use namespace of pid=[2503]
04-23 18:37:58.716   840  2504 D Magisk  : su: return code=[0]
04-23 18:37:58.735   840  2511 D Magisk  : su: request from pid=[2510], client=[13]
04-23 18:37:58.735   840  2511 D Magisk  : su: request from uid=[1000]
04-23 18:37:58.739   840  2511 D Magisk  : su: waiting child pid=[2514]
04-23 18:37:58.739  2514  2514 D Magisk  : su: fork handler
04-23 18:37:58.744  2514  2514 D Magisk  : su: use namespace of pid=[2510]
04-23 18:37:58.782   840  2511 D Magisk  : su: return code=[0]
04-23 18:37:58.819   840  2520 D Magisk  : su: request from pid=[2519], client=[11]
04-23 18:37:58.819   840  2520 D Magisk  : su: request from uid=[1000]
04-23 18:37:58.824   840  2520 D Magisk  : su: waiting child pid=[2523]
04-23 18:37:58.826  2523  2523 D Magisk  : su: fork handler
04-23 18:37:58.831  2523  2523 D Magisk  : su: use namespace of pid=[2519]
04-23 18:37:58.876   840  2520 D Magisk  : su: return code=[0]
04-23 18:37:58.907   840  2527 D Magisk  : su: request from pid=[2526], client=[13]
04-23 18:37:58.908   840  2527 D Magisk  : su: request from uid=[1000]
04-23 18:37:58.920   840  2527 D Magisk  : su: waiting child pid=[2530]
04-23 18:37:58.920  2530  2530 D Magisk  : su: fork handler
04-23 18:37:58.921  2530  2530 D Magisk  : su: use namespace of pid=[2526]
04-23 18:37:58.987   840  2527 D Magisk  : su: return code=[0]
04-23 18:37:59.040   840  2535 D Magisk  : su: request from pid=[2533], client=[11]
04-23 18:37:59.040   840  2535 D Magisk  : su: request from uid=[1000]
04-23 18:37:59.076   840  2535 D Magisk  : su: waiting child pid=[2539]
04-23 18:37:59.091  2539  2539 D Magisk  : su: fork handler
04-23 18:37:59.091  2539  2539 D Magisk  : su: use namespace of pid=[2533]
04-23 18:37:59.193   840  2535 D Magisk  : su: return code=[0]
04-23 18:38:54.056  1264  2621 I PackageManager: tango: skipping APK pre-translation for org.meowcat.edxposed.manager
04-23 18:38:54.056  1264  2621 I PackageManager: tango: skipping shared library pre-translation for org.meowcat.edxposed.manager
04-23 18:58:02.071   840  3273 D Magisk  : su: request from pid=[3271], client=[13]
04-23 18:58:02.071   840  3273 D Magisk  : su: request from uid=[1000]
04-23 18:58:02.071   840  3273 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:58:02.072   840  3273 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 18:58:02.079   840  3273 D Magisk  : su: waiting child pid=[3276]
04-23 18:58:02.079  3276  3276 D Magisk  : su: fork handler
04-23 18:58:02.080  3276  3276 D Magisk  : su: use namespace of pid=[3271]
04-23 18:58:02.126   840  3273 D Magisk  : su: return code=[0]
04-23 18:58:05.325  1264  2517 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd bnds=[426,152][559,334]} from uid 10063
04-23 18:58:05.381  1264  2517 I ActivityManager: Start proc 3291:org.meowcat.edxposed.manager/u0a67 for activity org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd
04-23 18:58:05.470   840  3301 D Magisk  : su: request from pid=[3297], client=[11]
04-23 18:58:05.470   840  3301 D Magisk  : su: request from uid=[1000]
04-23 18:58:05.470   840  3301 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:58:05.471   840  3301 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 18:58:05.481   840  3301 D Magisk  : su: waiting child pid=[3309]
04-23 18:58:05.514  3309  3309 D Magisk  : su: fork handler
04-23 18:58:05.514  3309  3309 D Magisk  : su: use namespace of pid=[3297]
04-23 18:58:05.612   840  3301 D Magisk  : su: return code=[0]
04-23 18:58:05.704  3291  3291 D MeowCatApplication: base dir is : /data/user_de/0/org.meowcat.edxposed.manager/
04-23 18:58:05.955  3291  3291 I zygote  :   at void org.meowcat.edxposed.manager.WelcomeActivity.onCreate(android.os.Bundle) (WelcomeActivity.java:55)
04-23 18:58:05.956  3291  3291 I zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/org.meowcat.edxposed.manager-KGjlMWOB7KoNP8mVdHBWDw==/base.apk"],nativeLibraryDirectories=[/data/app/org.meowcat.edxposed.manager-KGjlMWOB7KoNP8mVdHBWDw==/lib/arm, /system/lib, /system/vendor/lib]]
04-23 18:58:05.956  3291  3291 I zygote  :   at void org.meowcat.edxposed.manager.WelcomeActivity.onCreate(android.os.Bundle) (WelcomeActivity.java:55)
04-23 18:58:05.958  3291  3291 I zygote  :   at void org.meowcat.edxposed.manager.WelcomeActivity.onCreate(android.os.Bundle) (WelcomeActivity.java:55)
04-23 18:58:05.958  3291  3291 I zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/org.meowcat.edxposed.manager-KGjlMWOB7KoNP8mVdHBWDw==/base.apk"],nativeLibraryDirectories=[/data/app/org.meowcat.edxposed.manager-KGjlMWOB7KoNP8mVdHBWDw==/lib/arm, /system/lib, /system/vendor/lib]]
04-23 18:58:05.958  3291  3291 I zygote  :   at void org.meowcat.edxposed.manager.WelcomeActivity.onCreate(android.os.Bundle) (WelcomeActivity.java:55)
04-23 18:58:05.959  3291  3291 I zygote  :   at void org.meowcat.edxposed.manager.WelcomeActivity.onCreate(android.os.Bundle) (WelcomeActivity.java:55)
04-23 18:58:05.959  3291  3291 I zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/org.meowcat.edxposed.manager-KGjlMWOB7KoNP8mVdHBWDw==/base.apk"],nativeLibraryDirectories=[/data/app/org.meowcat.edxposed.manager-KGjlMWOB7KoNP8mVdHBWDw==/lib/arm, /system/lib, /system/vendor/lib]]
04-23 18:58:05.959  3291  3291 I zygote  :   at void org.meowcat.edxposed.manager.WelcomeActivity.onCreate(android.os.Bundle) (WelcomeActivity.java:55)
04-23 18:58:06.729   840  3352 D Magisk  : su: request from pid=[3351], client=[13]
04-23 18:58:06.729   840  3352 D Magisk  : su: request from uid=[1000]
04-23 18:58:06.732   840  3352 D Magisk  : su: waiting child pid=[3355]
04-23 18:58:06.732  3355  3355 D Magisk  : su: fork handler
04-23 18:58:06.734  3355  3355 D Magisk  : su: use namespace of pid=[3351]
04-23 18:58:06.775   840  3352 D Magisk  : su: return code=[0]
04-23 18:58:06.845  1264  1289 I ActivityManager: Displayed org.meowcat.edxposed.manager/.WelcomeActivityMlgmXyysd: +1s488ms
04-23 18:58:07.288  3291  3329 I EdXposedManager: RepoLoader -> Downloaded https://dl.xposed.info/repo/partial/19876.xml.gz with status 0 (error: null), size 10149 bytes
04-23 18:58:07.672  3291  3329 I EdXposedManager: RepoLoader -> Updated repository https://dl-xda.xposed.info/repo/full.xml.gz to version 19879 (3 new / 0 removed modules)
04-23 18:58:07.890   949   949 D SurfaceFlinger: duplicate layer name: changing org.meowcat.edxposed.manager/org.meowcat.edxposed.manager.WelcomeActivityMlgmXyysd to org.meowcat.edxposed.manager/org.meowcat.edxposed.manager.WelcomeActivityMlgmXyysd#1
04-23 18:58:07.984   840  3374 D Magisk  : su: request from pid=[3373], client=[11]
04-23 18:58:07.984   840  3374 D Magisk  : su: request from uid=[1000]
04-23 18:58:07.988   840  3374 D Magisk  : su: waiting child pid=[3378]
04-23 18:58:07.993  3378  3378 D Magisk  : su: fork handler
04-23 18:58:07.993  3378  3378 D Magisk  : su: use namespace of pid=[3373]
04-23 18:58:08.025   840  3374 D Magisk  : su: return code=[0]
04-23 18:58:09.625   949  1192 E BufferQueueProducer: [org.meowcat.edxposed.manager/org.meowcat.edxposed.manager.WelcomeActivityMlgmXyysd#0] disconnect: not connected (req=1)
04-23 18:58:09.651   840  3389 D Magisk  : su: request from pid=[3388], client=[13]
04-23 18:58:09.652   840  3389 D Magisk  : su: request from uid=[1000]
04-23 18:58:09.655  3393  3393 D Magisk  : su: fork handler
04-23 18:58:09.655   840  3389 D Magisk  : su: waiting child pid=[3393]
04-23 18:58:09.656  3393  3393 D Magisk  : su: use namespace of pid=[3388]
04-23 18:58:09.739   840  3389 D Magisk  : su: return code=[0]
04-23 18:58:09.765   840  3396 D Magisk  : su: request from pid=[3395], client=[11]
04-23 18:58:09.765   840  3396 D Magisk  : su: request from uid=[1000]
04-23 18:58:09.769   840  3396 D Magisk  : su: waiting child pid=[3399]
04-23 18:58:09.772  3399  3399 D Magisk  : su: fork handler
04-23 18:58:09.772   949   998 E BufferQueueProducer: [org.meowcat.edxposed.manager/org.meowcat.edxposed.manager.WelcomeActivityMlgmXyysd#1] disconnect: not connected (req=1)
04-23 18:58:09.774  3399  3399 D Magisk  : su: use namespace of pid=[3395]
04-23 18:58:09.810   840  3396 D Magisk  : su: return code=[0]
04-23 18:58:11.923   840  3421 D Magisk  : su: request from pid=[3420], client=[13]
04-23 18:58:11.923   840  3421 D Magisk  : su: request from uid=[1000]
04-23 18:58:11.928   840  3421 D Magisk  : su: waiting child pid=[3425]
04-23 18:58:11.928  3425  3425 D Magisk  : su: fork handler
04-23 18:58:11.929  3425  3425 D Magisk  : su: use namespace of pid=[3420]
04-23 18:58:11.964   840  3421 D Magisk  : su: return code=[0]
04-23 18:58:13.076   840  3438 D Magisk  : su: request from pid=[3437], client=[11]
04-23 18:58:13.076   840  3438 D Magisk  : su: request from uid=[1000]
04-23 18:58:13.101   840  3438 D Magisk  : su: waiting child pid=[3442]
04-23 18:58:13.102  3442  3442 D Magisk  : su: fork handler
04-23 18:58:13.120  3442  3442 D Magisk  : su: use namespace of pid=[3437]
04-23 18:58:13.164   840  3445 D Magisk  : su: request from pid=[3443], client=[13]
04-23 18:58:13.164   840  3445 D Magisk  : su: request from uid=[10061]
04-23 18:58:13.165   840  3445 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:58:13.166   840  3445 D Magisk  : su: waiting child pid=[3446]
04-23 18:58:13.174  3446  3446 D Magisk  : su: fork handler
04-23 18:58:13.176  3446  3446 D Magisk  : su: use global namespace
04-23 18:58:13.267   840  3438 D Magisk  : su: return code=[0]
04-23 18:58:13.409   840  3451 D Magisk  : su: request from pid=[3449], client=[14]
04-23 18:58:13.410   840  3451 D Magisk  : su: request from uid=[1000]
04-23 18:58:13.410   840  3451 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:58:13.411   840  3451 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 18:58:13.415   840  3451 D Magisk  : su: waiting child pid=[3454]
04-23 18:58:13.417  3454  3454 D Magisk  : su: fork handler
04-23 18:58:13.424  3454  3454 D Magisk  : su: use namespace of pid=[3449]
04-23 18:58:13.520   840  3451 D Magisk  : su: return code=[0]
04-23 18:58:16.195   840  3539 D Magisk  : su: request from pid=[3538], client=[14]
04-23 18:58:16.195   840  3539 D Magisk  : su: request from uid=[1000]
04-23 18:58:16.199   840  3539 D Magisk  : su: waiting child pid=[3543]
04-23 18:58:16.199  3543  3543 D Magisk  : su: fork handler
04-23 18:58:16.200  3543  3543 D Magisk  : su: use namespace of pid=[3538]
04-23 18:58:16.232   840  3539 D Magisk  : su: return code=[0]
04-23 18:58:17.143   840  3560 D Magisk  : su: request from pid=[3559], client=[11]
04-23 18:58:17.143   840  3560 D Magisk  : su: request from uid=[1000]
04-23 18:58:17.151   840  3560 D Magisk  : su: waiting child pid=[3564]
04-23 18:58:17.155  3564  3564 D Magisk  : su: fork handler
04-23 18:58:17.157  3564  3564 D Magisk  : su: use namespace of pid=[3559]
04-23 18:58:17.222   840  3560 D Magisk  : su: return code=[0]
04-23 18:58:31.560   840  3597 D Magisk  : su: request from pid=[3588], client=[14]
04-23 18:58:31.561   840  3597 D Magisk  : su: request from uid=[1000]
04-23 18:58:31.561   840  3597 D Magisk  : magiskdb: query magiskhide=[0]
04-23 18:58:31.563   840  3597 D Magisk  : magiskdb: query policy=[2] log=[1] notify=[1]
04-23 18:58:31.589   840  3597 D Magisk  : su: waiting child pid=[3602]
04-23 18:58:31.616  3602  3602 D Magisk  : su: fork handler
04-23 18:58:31.617  3602  3602 D Magisk  : su: use namespace of pid=[3588]
04-23 18:58:31.688   840  3597 D Magisk  : su: return code=[0]
04-23 18:58:32.254   840  3652 D Magisk  : su: request from pid=[3651], client=[11]
04-23 18:58:32.254   840  3652 D Magisk  : su: request from uid=[1000]
04-23 18:58:32.262   840  3652 D Magisk  : su: waiting child pid=[3656]
04-23 18:58:32.264  3656  3656 D Magisk  : su: fork handler
04-23 18:58:32.265  3656  3656 D Magisk  : su: use namespace of pid=[3651]
04-23 18:58:32.319   840  3652 D Magisk  : su: return code=[0]

**Describe the bug:**

ro.dalvik.vm.native.bridge libriruloader.so
riru模块加载不上，/dev/riru_MYAIzx9文件不存在。

**Additional context:**

**Comment by RikkaW** [comment]
Please provide full log rather than filtered log
