### ISSUE TITLE
Riru on Pixel Experience (Poco F1)

### ISSUE THREAD

**Issue by Nevarnost** [RikkaApps/Riru#224]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
Riru version: v25.4.2r415
Magisk version: 22100
Android version:11 (PixelExperience)
Device: Poco F1 (beryllium)

**Logs:**
[magisk_install_log_2021-05-03T19_07_48Z.log](https://github.com/RikkaApps/Riru/files/6416425/magisk_install_log_2021-05-03T19_07_48Z.log)

**Describe the bug:**

Cannot update Riru, It says

- Checking if your ROM has incorrect SELinux rules
! Your ROM has incorrect SELinux rules -

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru/wiki/Explanation-about-incorrect-SELinux-rules-from-third-party-ROMs-cause-Riru-not-working

**Comment by Nevarnost** [comment]
My selinux is Enforcing. What's wrong with that? I see that the #218 ticket was fixed, why this won't?

**Comment by RikkaW** [comment]
Did you really read that document?
The problem is not about enforcing or not, it about if there are incorrectSELinux policy.
