### ISSUE TITLE
Breaks/Corrupts the  USER DATA PARTITION on Samsung Galaxy A9 2018(A920F) PERMANENTLY EVEN AFTER UNINSTALL 

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [RikkaApps/Riru#226]
After installing Riru everything worked fine, until I felt the need of adding my 2nd Google account, that's when things became terrible.  As I entered my password , completed my 2FA and as I agreed on Google ToS phone started to reboot then show the lock screen , then screen  automatically turns off though still on lockscreen and reboots again , this happens continuously.  The temporary  fix is to go to safe mode and remove the added Google account  and then restart and problem goes off. So now I have found that Riru doesn't perfectly support my device, it does what it it is required to do but also crashes the system at boot . So I uninstalled  it. Then hoping that the problem is gone , I added back my 2nd google account . But guess what Riru did something PERMANENT to the system  though it is a module which can be turned off. The PERMANENT effect is that now whenever I add a new Google account system reboots shows lockscreen for 5-7 seconds or so and then again reboots until I fix in the above way mentioned , it broke something related to Google in Accounts in Settings .Whenver I add an account it again happens. 
Later I just reflashed the whole Magisk rooted stock AP, BL, CP files but with HOME_CSC file to preserve my data. And the reboot problem persists, so Riru did something to USER DATA partition and not SYSTEM PARTITION 
 which causes the issue. Also I have only installed riru + edxposed modules. I uninstalled both but no help. Hope you fix this.
THANK YOU ,
WAITING FOR THIS TO BE FIXED

**Comment by srccrow** [comment]
@Navneet-Kumar-Singh Are you on Android 9 too?

**Comment by RikkaW** [comment]
Riru does not do permanent changes, you should suspect EdXposed and your xposed modules first since many of them have 💩 quality.

**Comment by srccrow** [comment]
@RikkaW At least in my case it happens without using any modules, I simply flash Magisk, and RiruCore, no modules at all, on next reboot I am unable to unlock either through pin or pattern, and even removing Magisk doesn't solve it.

At this point I guess is either releated to TWRP or SEPolicy, because I don't have it happen on the same device if I use Android 10 without SEPolicy and the same version of TWRP.

https://lineageos.wickenberg.nu/gts210vewifi LineageOS16.

**Comment by Navneet-Kumar-Singh** [comment]
> @Navneet-Kumar-Singh Are you on Android 9 too?

No, I am on android 10

**Comment by Navneet-Kumar-Singh** [comment]
> Riru does not do permanent changes, you should suspect EdXposed and your xposed modules first since many of them have 💩 quality.

RikkaW , I have no other modules installed , all this problem started after I installed only Riru 1st on a freshly installed  stock firmware
