### ISSUE TITLE
Riru v15与Taichi•Magisk 4.7同时使用时，riru不生效

### ISSUE THREAD

**Issue by singleNeuron** [RikkaApps/Riru#23]
Riru v15 found.
However, native methods of Zygote class not replaced, please contact developer with the following information.

nativeForkAndSpecializeSignature:
null

getNativeForkSystemServerSignature:
null

重启手机无效，但使用镧工具箱软重启后正常，禁用太极后正常

**Comment by zhangxuhu** [comment]
小米的miui用了几部手机都是随便重启，太极和riru都兼容

一加5t和部分类原生都是玄学兼容，有时重启一次就好，再重启又不行了

**Comment by singleNeuron** [comment]
我是Nexus6p，StatixOS，第一次重启了三次之后就可以了。之后过了两天在某一次重启之后突然就不行了，再重启也没用，但用镧工具箱软重启就行。

**Comment by zhangxuhu** [comment]
难道太极和riru的启动次序影响兼容性？

**Comment by zhangxuhu** [comment]
对于riru没有启动的情况，应该如何提供日志？

**Comment by RikkaW** [comment]
> 对于riru没有启动的情况，应该如何提供日志？

都直接提供开机以来的 log（

**Comment by zhangxuhu** [comment]
> > 对于riru没有启动的情况，应该如何提供日志？
> 
> 都直接提供开机以来的 log（

大佬你好，我刚才抓了log，麻烦大佬看看

##使用Taichi•Magisk 4.7+Riru core 15
现象：玄学兼容，有时候riru有效，有时候无效

#第一次重启，有效
[1.log](https://github.com/RikkaApps/Riru/files/2926056/1.log)
#第二次重启，无效
[2.log](https://github.com/RikkaApps/Riru/files/2926058/2.log)
#第三次重启，无效
[3.log](https://github.com/RikkaApps/Riru/files/2926059/3.log)
#第四次重启，无效
[4.log](https://github.com/RikkaApps/Riru/files/2926063/4.log)
#第五次重启，无效
[5.log](https://github.com/RikkaApps/Riru/files/2926065/5.log)
#第六次和第七次重启，有效
[6+7.log](https://github.com/RikkaApps/Riru/files/2926068/6%2B7.log)
#第八次重启，失效
[8.log](https://github.com/RikkaApps/Riru/files/2926071/8.log)


烦请Rikka看看，谢谢

**Comment by RikkaW** [comment]
发出 建议去向什么都藏着掖着的太极提问题 的声音（

**Comment by Howard20181** [comment]
太极的作者说不再兼容了
等Edxposed再稳定点再切换回来这边

**Comment by singleNeuron** [comment]
> 发出 建议去向什么都藏着掖着的太极提问题 的声音（

委屈的发出我其实是被太极作者赶过来的声音
https://github.com/taichi-framework/TaiChi/issues/387

**Comment by RikkaW** [comment]
另一个人会说用凄惨 4.6 没问题 那你试试（

**Comment by zhangxuhu** [comment]
> 发出 建议去向什么都藏着掖着的太极提问题 的声音（

Rikka，有没有什么办法通过上述log避开Taichi•Magisk 4.7对Riru的干扰？谢谢

**Comment by Howard20181** [comment]
![screenshot_2019-03-07-14-16-00-976_moe riru manager](https://user-images.githubusercontent.com/40033067/53936256-3f494b80-40e4-11e9-90a9-cd96b36865f6.png)
![screenshot_2019-03-07-14-18-39-203_com solohsu android edxp manager](https://user-images.githubusercontent.com/40033067/53936271-48d2b380-40e4-11e9-81e0-14216e30a769.png)
![screenshot_2019-03-07-14-16-35-883_me weishu exp](https://user-images.githubusercontent.com/40033067/53936282-4ec89480-40e4-11e9-85fd-98a00a64018f.png)
又同时好了，概率问题😂

**Comment by zhangxuhu** [comment]
> ![screenshot_2019-03-07-14-16-00-976_moe riru manager](https://user-images.githubusercontent.com/40033067/53936256-3f494b80-40e4-11e9-90a9-cd96b36865f6.png)
> ![screenshot_2019-03-07-14-18-39-203_com solohsu android edxp manager](https://user-images.githubusercontent.com/40033067/53936271-48d2b380-40e4-11e9-81e0-14216e30a769.png)
> ![screenshot_2019-03-07-14-16-35-883_me weishu exp](https://user-images.githubusercontent.com/40033067/53936282-4ec89480-40e4-11e9-85fd-98a00a64018f.png)
> 又同时好了，概率问题😂

老哥，再重启一次试试看看能行不

**Comment by Howard20181** [comment]
重启一次，两个都掉 
重启第二次，riru可以，太极掉

**Comment by 06ji** [comment]
> 重启一次，两个都掉
> 重启第二次，riru可以，太极掉

试试4.7.5？

**Comment by eromoe** [comment]
偏个题，想问一下同时装 riru 和 太极有什么好处
好久没root，上次root还是android6的时候

**Comment by singleNeuron** [comment]
riru好处都有啥，谁说对了就给他。（误riru的话有开启位置服务存储重定向，太极是用来当xp用，因为有些插件对edxp兼容性不是很好。顺便说一下这个问题到了riru19仍然没有解决2019年5月19日 19:49，eromoe <notifications@github.com>写道：偏个题，想问一下同时装 riru 和 太极有什么好处

好久没root，上次root还是android6的时候
