### ISSUE TITLE
cant boot after installing riru

### ISSUE THREAD

**Issue by adifoi232** [RikkaApps/Riru#232]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes, No]
- Riru version: 25
- Magisk version: 23
- Android version: lineage os 10
- Device: samsung

**Logs:**

Related **full logcat**. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

**Describe the bug:**

bro i cant install this
pressed reboot after i install riru in magisk, it just booted into samsung download mode
wont boot into system, cant use my phone now

**Additional context:**

**Comment by lilPrince** [comment]
riru + lsposed not worked on magisk 23(

**Comment by canyie** [comment]
No one can solve your problem without enough info.
