### ISSUE TITLE
Could not load on SmartisanOS 6.7.4.3

### ISSUE THREAD

**Issue by the-eric-kwok** [RikkaApps/Riru#236]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: 25.4.4.r426.05efc94
- Magisk version: 23.0(23000)
- Android version: 7.1.2
- Device: (optional) Smartisan Nut U3

**Logs:**

[magisk_log_2021-07-03T14:27:05Z.log](https://github.com/RikkaApps/Riru/files/6757944/magisk_log_2021-07-03T14.27.05Z.log)

**Describe the bug:**

![Screenshot_2021-07-03-14-12-19-529_Riru](https://user-images.githubusercontent.com/16463312/124345504-c7629180-dbc8-11eb-8bed-c0b23f0541c4.png)

**Comment by RikkaW** [comment]
It's possible that the SELinux context of the Magisk module folder is incorrect. Please run these commands in `adb shell` or any terminal app, then send the results here.

```
su
ls -laZ /data/adb
ls -laZ /data/adb/modules
ls -laZ /data/adb/modules/riru-core
ls -laZ /data/adb/modules/riru-core/lib64
```

**Comment by the-eric-kwok** [comment]
```
ls -laZ /data/adb
total 96
drwx------  8 root   root   u:object_r:adb_data_file:s0     4096 2021-07-03 14:25 .
drwxrwx--x 49 system system u:object_r:system_data_file:s0  4096 2021-07-02 17:16 ..
drwxr-xr-x  3 root   root   u:object_r:magisk_file:s0       4096 2021-07-02 13:07 magisk
-rw-------  1 root   root   u:object_r:adb_data_file:s0    10240 2021-07-03 14:25 magisk.db
drwxr-xr-x  6 root   root   u:object_r:system_file:s0       4096 2021-07-03 14:19 modules
drwxr-xr-x  2 root   root   u:object_r:adb_data_file:s0     4096 2021-07-02 13:07 post-fs-data.d
drwxr-xr-x  2 root   root   u:object_r:adb_data_file:s0     4096 2021-07-02 19:35 riru
drwxr-xr-x  2 root   root   u:object_r:adb_data_file:s0     4096 2021-07-02 13:07 service.d
drwx------  3 root   root   u:object_r:adb_data_file:s0     4096 2021-07-03 11:55 storage-isolation

ls -laZ /data/adb/modules
total 48
drwxr-xr-x 6 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 .
drwx------ 8 root root u:object_r:adb_data_file:s0 4096 2021-07-03 14:25 ..
drwxr-xr-x 3 root root u:object_r:system_file:s0   4096 2021-07-03 14:24 hosts
drwxr-xr-x 5 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 riru-core
drwxr-xr-x 3 root root u:object_r:system_file:s0   4096 2021-07-03 14:24 ssh
drwxr-xr-x 3 root root u:object_r:system_file:s0   4096 2021-07-03 14:24 terminal_systemizer

ls -laZ /data/adb/modules/riru-core
total 632
drwxr-xr-x 5 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 .
drwxr-xr-x 6 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 ..
drwxr-xr-x 2 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 lib
drwxr-xr-x 2 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 lib64
-rw-r--r-- 1 root root u:object_r:system_file:s0    199 2021-07-03 14:19 module.prop
-rw-r--r-- 1 root root u:object_r:system_file:s0    148 2021-07-03 14:19 post-fs-data.sh
-rwx------ 1 root root u:object_r:system_file:s0 249968 2021-07-03 14:19 rirud
-rw------- 1 root root u:object_r:system_file:s0  27608 2021-07-03 14:19 rirud.dex
-rw-r--r-- 1 root root u:object_r:system_file:s0    244 2021-07-03 14:19 service.sh
drwxr-xr-x 4 root root u:object_r:system_file:s0   4096 2021-07-03 14:19 system
-rw-r--r-- 1 root root u:object_r:system_file:s0     44 2021-07-03 14:19 system.prop
-rw-r--r-- 1 root root u:object_r:system_file:s0   1575 2021-07-03 14:19 util_functions.sh

ls -laZ /data/adb/modules/riru-core/lib64
total 2536
drwxr-xr-x 2 root root u:object_r:system_file:s0    4096 2021-07-03 14:19 .
drwxr-xr-x 5 root root u:object_r:system_file:s0    4096 2021-07-03 14:19 ..
-rw-r--r-- 1 root root u:object_r:system_file:s0 1203408 2021-07-03 14:19 libriru.so
-rw-r--r-- 1 root root u:object_r:system_file:s0   85504 2021-07-03 14:19 libriruhide.so
```

**Comment by the-eric-kwok** [comment]
Any news on this? @RikkaW

**Comment by RikkaW** [comment]
I found that I was confused you with the last person who has a similar problem, so I even forget to ask you for the boot log.
Get the boot log in short:
1. Set "Log buffer size" to maximum in "Developer settings"
2. During (or after) the boot stage, use `adb logcat > 1.txt`
3. Send 1.txt here

**Comment by the-eric-kwok** [comment]
[boot.log](https://github.com/RikkaApps/Riru/files/6776421/boot.log)
Here is the boot log captured during boot stage. The smartisan OS doesn't have "Log buffer size" in "Developer settings" so I'm not sure if the log will help. I've already searched "Riru" and "Magisk" inside the log and there're some results.

**Comment by RikkaW** [comment]
You stopped the logcat too early.

**Comment by the-eric-kwok** [comment]
[boot.log](https://github.com/RikkaApps/Riru/files/6777432/boot.log)
How about this one? It stopped automatically and I restart logcat and append the rest to the file.

**Comment by RikkaW** [comment]
It seems that Riru is not loaded by the system.

> 07-07 21:07:57.469   452   454 E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy

I'm not sure if this means Magisk modules are not working on your devices at all. Check if `/system/lib64/libriruloader.so` exists.

Or another possibility, SmartisanOS removes the support of native bridge. If this is true, nothing I can do unless switching to other methods in the future.

**Comment by the-eric-kwok** [comment]
no, /system/lib64/libriruloader.so doesn't exists.

Rikka ***@***.***> 于2021年7月8日周四 下午2:22写道：

**Comment by RikkaW** [comment]
Maybe Magisk is broken on your device, you can try installing other modules which modify files in `/system` and check if they are working.

**Comment by the-eric-kwok** [comment]
I’m not sure which module will modify `/system` 
I tried Systemless Xposed Framework module and that didn’t work either.

**Comment by RikkaW** [comment]
Magisk is broken on your device 😋

**Comment by the-eric-kwok** [comment]
Is there anyway I can fix it?
