### ISSUE TITLE
Not installing installation failed

### ISSUE THREAD

**Issue by Piurani** [RikkaApps/Riru#249]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes, No]
- Riru version: 
- Magisk version: 
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

**Describe the bug:**

**Additional context:**

It is asking to install Ritu from magisk and that is done already but edexposed module not installing

**Comment by Piurani** [comment]
![Screenshot_2021-07-26-23-25-07-134_com topjohnwu magisk](https://user-images.githubusercontent.com/87998910/127038572-751405d0-ee82-4d78-b36e-62f929309b13.jpg)

**Comment by Piurani** [comment]
Screen shot attached

**Comment by RikkaW** [comment]
> v26.0.0
> * Remove support for pre-v24 modules (it has been more than 4 months and **all live modules have upgraded to v24+**)
