### ISSUE TITLE
after update Riru version to "v26.0.1" or "v26.0.2", "EdXposed-v0.5.2.2" can't install success

### ISSUE THREAD

**Issue by guangdeshishe** [RikkaApps/Riru#250]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**. **Reports not meet the requirements will be immediately closed**. **Information:** - Except Riru itself, all other Magisk modules are disabled: [Yes, No] - 

Riru version: 26.0.2 
- Magisk version: 23.0
- Android version:11
- Device: (optional) Samsung 
 
**Logs:** 
- Copying zip to temp directory - Installing Riru_EdXposed-v0.5.2.2_4683-master.zip - Device is system-as-root Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: module.prop *********************** Riru - EdXposed by solohsu, MlgmXyysd *********************** Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: customize.sh ******************* Powered by Magisk ******************* Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: zh_CN.sh Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: zh_CN.sh.s - EdXposed 版本 v0.5.2.2_4683-master Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: verify.sh Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: customize.sh Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: customize.sh.s - 已验证 customize.sh Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: util_functions.sh Archive: /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip inflating: util_functions.sh.s - 已验证 util_functions.sh - Android SDK 版本: 30 - Magisk 版本: 23000 ********************************************************* ! 未安装 ! 请先从 Magisk Manager 中安装 Riru ********************************************************* ! Installation failed 

**Describe the bug:** 
after install "Riru_v26.0.2", "Riru_EdXposed-v0.5.2.2_4683-master" can't be installed success, notice: "! 未安装,! 请先从 Magisk Manager 中安装 Riru", that means "EdXposed-v0.5.2.2" can't judge whether Riru installed, "Riru_v26.0.1" has the same issue. 

**Additional context:**

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru/releases/tag/v26.0.0
> Remove support for pre-v24 modules (it has been more than 4 months and **all live modules have upgraded to v24+**)

EdXposed is dead :)

**Comment by reyis4402** [comment]
@RikkaW then how will the modules work?

**Comment by DrSaad77** [comment]
I got the same issue, impossible to install EdXposed. Dead?? Is that a joke?? Any help???
Thx

**Comment by ricpans** [comment]
When an xposed module allows for signature spoofing your phone so I can use Magisk, not allowing Edxposed to keep working forces me to stop updating Riru!
Is there another way around this issue?

**Comment by reyis4402** [comment]
@DrSaad77 @ricpans 
Use this instead of EDXPOSED and activate all modules for applications
![IMG_20210809_181131_233](https://user-images.githubusercontent.com/60405617/128729942-8b913893-4d76-47c3-b28d-0f5b1b676b43.jpg)

**Comment by VD171** [comment]
EdXposed is NOT a problem of RIRU or of RIKKAPPS.
If you have anything to say, just say here:
https://github.com/ElderDrivers/EdXposed

**Comment by reyis4402** [comment]
...
![Screenshot_20210809-181452](https://user-images.githubusercontent.com/60405617/128730166-53798600-74e1-4649-bf9a-5063d525c41d.png)

**Comment by ricpans** [comment]
> ...
> ![Screenshot_20210809-181452](https://user-images.githubusercontent.com/60405617/128730166-53798600-74e1-4649-bf9a-5063d525c41d.png)
> 

Thank you so much, my new Xposed is working flawlessly now!

**Comment by liukepeng** [comment]
哈哈哈，我要笑死了，他们说你们不负责，你们说他们死了

**Comment by DrSaad77** [comment]
> @DrSaad77 @ricpans
> Use this instead of EDXPOSED and activate all modules for applications
> ![IMG_20210809_181131_233](https://user-images.githubusercontent.com/60405617/128729942-8b913893-4d76-47c3-b28d-0f5b1b676b43.jpg)

Thx, it is very long to activate each modules, for all the apps.
Sad there not a "Select All" options.

**Comment by VD171** [comment]
You do NOT need "select all".
EdXposed is the "select all" of the LSPosed.
But, EdXposed is dead, so "select all" is dead too.
Long Life to LSPosed ♥️
