### ISSUE TITLE
Tori problem

### ISSUE THREAD

**Issue by Piurani** [RikkaApps/Riru#251]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes, No] no
- Riru version: 26.0.2
- Magisk version: 23.0
- Android version: 9
- Device: (optional)

**Logs:**

Related **full logcat**. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

**Describe the bug:**

**Additional context:**

![Screenshot_2021-07-27-13-55-34-219_com topjohnwu magisk](https://user-images.githubusercontent.com/87998910/127123552-f74b7ae4-da2b-46a7-a0d7-b0741a907ef2.jpg)

**Comment by Piurani** [comment]
I have opened magisk hide prop config that's it and Riri is not able to install ed-xpoded module

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru/issues/250#issuecomment-887301945
