### ISSUE TITLE
Long boot time with v26.0.4

### ISSUE THREAD

**Issue by BurhanDanger** [RikkaApps/Riru#254]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: v26.0.4
- Magisk version: 23
- Android version: 11
- Device: (optional)

**Logs:**

Related **full logcat**. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

**Describe the bug:**

With v26.0.3 riru boot time is about 25 seconds. And with v26.0.4/v26.0.5 it's 1 minute.

**Comment by yujincheng08** [comment]
No log no fix.

**Comment by BurhanDanger** [comment]
Which log do I give ?

**Comment by etmatrix** [comment]
> Which log do I give ?

is wriitten in template issue
> Related full logcat. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

However i noticed the same issue after the update, if you can't catch log, I will do it.

**Comment by RikkaW** [comment]
Specific for your case, kernel log may be more useful.

**Comment by BurhanDanger** [comment]
[Logcat without any modules](https://termbin.com/ongn3)
[Logcat with v26.0.3](https://termbin.com/gmqz)
[Logcat with v26.0.4](https://termbin.com/hsbh)

I'll take a look at how to take kernel logs.

**Comment by yujincheng08** [comment]
those logs are too late. Riru has already finished its job before the first line.

**Comment by etmatrix** [comment]
today I tested some reboots and I was wrong, only the firtst time I had a long boot, between 25.4.4 and 26.0.5 there is no difference on 3 reboots, so my logs are useless.

**Comment by BurhanDanger** [comment]
[bootlog-2021-08-09-12-48-50.tar.gz](https://github.com/RikkaApps/Riru/files/6952553/bootlog-2021-08-09-12-48-50.tar.gz)

**Comment by BurhanDanger** [comment]
Are these logs okay ? or do provide something else ?

**Comment by yujincheng08** [comment]
@BurhanDanger 
In 26.0.4 we notice `W Magisk  : * post-fs-data scripts blocking phase timeout` but it has been fixed in 26.0.5. So plz provide log with 26.0.5.

**Comment by yujincheng08** [comment]
maybe u misremembered.
