### ISSUE TITLE
Riru v26.0.5 prevent LSPosed 1.4.7 (5803) to function (even if LSPosed is reinstalled) on android 10.

### ISSUE THREAD

**Issue by admzzz** [RikkaApps/Riru#256]
Riru v26.0. was installed over Riru 25.4.4, after reboot LSPosed manager told that there are no LSPosed installed.
after installation of LSPosed 1.4.7 over previous one LSPosed manager told  the same.
after total cleaning LSPosed in /data/adb/ and another try of installing it, LSPosed manager told  the same.
in magisk's log there was only one line: "riru_lsposed: exec [post-fs-data.sh], line "riru_lsposed: loading [system.prop]" was absent.

**Comment by yujincheng08** [comment]
Need full bootlog.

**Comment by admzzz** [comment]
@yujincheng08 , here it is.
[magisk_log_2021-08-06T143149Z.log.zip](https://github.com/RikkaApps/Riru/files/6945231/magisk_log_2021-08-06T143149Z.log.zip)

**Comment by yujincheng08** [comment]
I mean bootlog, rather than magisk log.

In case u don't know how to grab one:
```
With PC: 
https://t.me/hzrtools/12
WIthmagisk20.4+:
https://t.me/hzrtools/10
```

**Comment by admzzz** [comment]
@yujincheng08 , 
[log1.txt.zip](https://github.com/RikkaApps/Riru/files/6945289/log1.txt.zip)

**Comment by yujincheng08** [comment]
Check magisk modules list. Riru will show its status there. And apparently if you look at there you will see riru's post-fs-data.sh was not executed. And it's caused by /data/adb/post-fs-data.d/dns-redirect.sh

Nothing to do with Riru and LSPosed.

**Comment by admzzz** [comment]
@yujincheng08 ,
can you please explain your previous answer (with the line's numberes of log file)?
which line of /data/adb/post-fs-data.d/dns-redirect.sh prevents riru's post-fs-data.sh from executing?

```
$cat /data/adb/post-fs-data.d/dns-redirect.sh
#!/system/bin/sh

until [ "$(getprop sys.boot_completed)" == "1" ] && [ -d /storage/emulated/0/Android ]; do
  sleep 1
done
sysctl -p -e
pkill -9 netmgrd >/dev/null 2>&1
pkill -9 imsrcsd >/dev/null 2>&1
pkill -9 ims_rtp_daemon >/dev/null 2>&1
```
> Check magisk modules list. 
excuse me, where exactly? in magisk manager all ok.

> Riru will show its status there. 
excuse me again, where it will?

and, once again, with Riru v25.4.4, all (LSPosed and dns-redirect.sh) works fine...

one more question: should scripts (i.e. *.sh) in /data/adb/modules/*, /data/adb/post_fs_data/, /data/adb/servise.d/ be executable or they may not?

**Comment by yujincheng08** [comment]
Please read the Magisk document carefully. `post-fs-data` is synchronized and will run one by one. You have a busy wait there and will BLOCK all other modules' post-ds-data from running!

Read carefully here:
https://topjohnwu.github.io/Magisk/guides.html#boot-scripts

**Comment by admzzz** [comment]
@yujincheng08 ,
thank you kindly for your explanation, after deleting untill-done block Riru 26.0.5 &  LSPosed works fine.
