### ISSUE TITLE
App launch delay after reboot

### ISSUE THREAD

**Issue by jbro129** [RikkaApps/Riru#259]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: v26.0.5
- Magisk version: 23.0
- Android version: 11.0
- Device: Galaxy S20+
- Logs:

**Logs:**

Should I add a kernal log or just the Magisk log?

**Describe the bug:**

I recently updated my riru from v25.4.4 to v26.0.5 and noticed that there was a 5-10 second app launch delay whenever I try to open an app after a reboot. The only apps that I've noticed don't have a delay are apps that I've allowed to use root permissions. 

My entire phone basically freezes pretty much. I have to either wait through the delay or press the home button to get back to my home screen.

**Additional context:**

This app delay issue also occurs when I use Riru v26.0.0 but not on v25.4.4.

**Comment by jbro129** [comment]
Typo

**Comment by jbro129** [comment]
Might be related to #254

**Comment by yujincheng08** [comment]
No log.
