### ISSUE TITLE
Exposed flashing failed. Android 11 how to fix..?

### ISSUE THREAD

**Issue by JHRumon222** [RikkaApps/Riru#261]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes, No]
- Riru version: 
- Magisk version: 
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

**Describe the bug:**

**Additional context:**

![Screenshot_2021-08-13-12-56-13-778_rnzun syecncjigi](https://user-images.githubusercontent.com/88876217/129317095-448e910f-0253-4e8f-844f-2cf673f4c5d6.jpg)

**Comment by JHRumon222** [comment]
![Uploading Screenshot_2021-08-13-12-58-20-933_rnzun.syecncjigi.jpg…]()

**Comment by etmatrix** [comment]
EdXposed is not more supported https://github.com/RikkaApps/Riru/issues/250#issuecomment-887301945
