### ISSUE TITLE
请问怎么查看Riru启动的日志，logcat里只有很少的日志

### ISSUE THREAD

**Issue by ghd8239820** [RikkaApps/Riru#263]
我看到[hide.cpp](https://github.com/RikkaApps/Riru/blob/8b337d16dd7f104f543e54ad7d82149018df3298/riru/src/main/cpp/hide/hide.cpp)里面有很多日志输出到了logcat，我想从里面知道模块的so被加载到了虚存空间的哪个位置，但是logcat里日志没有这些，怎样操作会触发这些日志呢。

**Comment by RikkaW** [comment]
用 debug 版
