### ISSUE TITLE
更新最新版后不能使用edxp

### ISSUE THREAD

**Issue by reBurn0216** [RikkaApps/Riru#264]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes, No]
- Riru version: 
- Magisk version: 
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**. For example, if you have a "Riru module not loaded" problem, a full boot log will be helpful.

**Describe the bug:**

**Additional context:**

手机型号是Oneplus KB2000
更新Riru26.1.0后edxp失效且无法刷入，提示无安装riru

**Comment by RikkaW** [comment]
EdXposed 已经死了，建议更换为其他的 Xposed 实现。
