### ISSUE TITLE
Riru Exposed is not updated

### ISSUE THREAD

**Issue by gallegonovato** [RikkaApps/Riru#268]
Good afternoon:

I have a Huawei Nexus 6p with lineageos 17.1 without gaps. And magisk in its latest version

It turns out that since recently Riru Exposed is not updated. And with it does not activate well Exposed.

I do not know if it affected that Riru https://github.com/RikkaApps/Riru was updated or do not understand what happened or happens.

I try to update from Magisk directly and fails. I try to download and Magisk install from storage and nothing either.

I upload screenshots to see if you can tell me what happens or I'm doing wrong.

https://ibb.co/hZBC6Vk
https://ibb.co/njHFKjY
https://ibb.co/xFwhDRQ
https://ibb.co/gD5G3Zr
https://ibb.co/b6YhxZs
https://ibb.co/Wv8QF9b
https://ibb.co/TmDkCJJ
https://ibb.co/Ntq2NGb
https://ibb.co/yQ0V5Tv
https://ibb.co/RNR0TZM
https://ibb.co/wLnBRr2
https://ibb.co/vvbJ09y
https://ibb.co/4RCdzHP
https://ibb.co/PwWyf0M

A hug and thank you for your time and help.

**Comment by yujincheng08** [comment]
Exposed does not require Riru.

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for your time. But since Riru updates Riru Exposed is not updated.

I used to have the latest versions of Riru Exposed. But I don't know if the Riru add-on influences but Riru Exposed is not updated.

I tried uninstalling and reinstalling and nothing.

Best regards

**Comment by canyie** [comment]
Exposed = TaiChi

**Comment by yujincheng08** [comment]
Taichi never requres Riru.

**Comment by gallegonovato** [comment]
Good afternoon:

At the end if it influences Riru to update or install Riru Exposed.

What I did was to remove Riru and Riru Exposed from Magisk. I also uninstalled Exposed and XprivacyLua.

Then I rebooted the phone. Once booted, I ran lte cleanner from fdroid and sd maid. And clear all caches.

Abtes I had seen a video, of a Mr., I think he is Indian. That is https://youtu.be/RoLLTC-Gw-M where you can see that the solution is to disable Riru. But it did not work at all. Xposed and XprivacyLua not hiban.

Then I checked that magisk and magisk manager were in their latest version. They were.

Then I went to https://github.com/RikkaApps/Riru/releases . And I looked for version 25.4.4 release (https://github.com/RikkaApps/Riru/releases/tag/v25.4.4) 

Then from Riru Exposed I installed the one that comes up in the magisk module finder. Here I did tell it to reboot.

Then I downloaded the latest version of exposed https://github.com/ElderDrivers/EdXposedManager/releases

In exposed, it started fine, I checked the afwall+ module in my case. At the top of exposed you look for reboot, system. You are prompted by magisk to give you superuser permission. You accept it. Let it reboot.

Then install XprivacyLua. (In my case). Activate the module in Xposed.

And everything working.

A hug
