### ISSUE TITLE
Riru不生效，V17（没有太极）

### ISSUE THREAD

**Issue by Howard20181** [RikkaApps/Riru#27]
日志
[logcat.log](https://github.com/RikkaApps/Riru/files/2944502/logcat.log)

**Comment by Howard20181** [comment]
重启3次后终于可用的日志
[logcat.log](https://github.com/RikkaApps/Riru/files/2944558/logcat.log)

**Comment by RikkaW** [comment]
然而两个 log 都太晚了 没有有用的内容（

**Comment by Howard20181** [comment]
> 然而两个 log 都太晚了 没有有用的内容（

/(ㄒoㄒ)/~~
今晚回家再试图复现，能告诉我怎么抓才行吗？

**Comment by Howard20181** [comment]
> 然而两个 log 都太晚了 没有有用的内容（

问题复现
这是riru不生效的
[bootloop-2019-03-12-12-26-26.log](https://github.com/RikkaApps/Riru/files/2955189/bootloop-2019-03-12-12-26-26.log)

这是生效的
[bootloop-2019-03-12-12-36-51.log](https://github.com/RikkaApps/Riru/files/2955190/bootloop-2019-03-12-12-36-51.log)

不生效时似乎没有
2113  2113 I Riru    : hook installed
> 

这步出现
