### ISSUE TITLE
Riru v26+ no longer working with EdXposed

### ISSUE THREAD

**Issue by digaogt** [RikkaApps/Riru#274]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: [Yes, No]
- Riru version: 26.0.0 and above
- Magisk version: 23.0
- Android version: 9
- Device: Nvidia Shield TV

Riru 26+ no longer working with EdXposed. Tested with Riru version 25 still working fine!

**Comment by MBRjun** [comment]
使用 25.4.4 版本
use v25.4.4

**Comment by diassynthesis** [comment]
If you are using LSPOSED try to use [TAICHI](https://github.com/taichi-framework/TaiChi/releases) to manage Edxposed modules.
