### ISSUE TITLE
Created enable_hide but hide still disabled

### ISSUE THREAD

**Issue by acestars** [RikkaApps/Riru#277]
Please report bugs of Riru itself. Always use **the latest debug version** of Riru, and **make sure any other modules are disabled**.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Except Riru itself, all other Magisk modules are disabled: Yes
- Riru version: 26.1.2 (505, api v26)
- Magisk version: 23000
- Android version: 9
- Device: Xiaomi Redmi Note 2 (hermes)

**Logs:**

[logcat.txt](https://github.com/RikkaApps/Riru/files/7121614/logcat.txt)

**Describe the bug:**

I have already created /data/adb/riru/enable_hide but the riru hide still disabled

**Additional context:**

![riru1](https://user-images.githubusercontent.com/637192/132348451-870a2b61-66ae-4040-a647-e7f06671ad2d.jpg)
![riru2](https://user-images.githubusercontent.com/637192/132348462-998b8397-6d14-40f5-ac07-0e51bdfffb1b.jpg)
![riru3](https://user-images.githubusercontent.com/637192/132348467-da881099-5e1f-4898-a89b-d7cc0be6cdb8.jpg)
![riru4](https://user-images.githubusercontent.com/637192/132348472-54ffe0d9-d187-493e-a982-bb377fc82304.jpg)

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru/releases/tag/v26.0.5

> Display status on module description in Magisk (**app is removed because of this**)

https://github.com/RikkaApps/Riru/releases/tag/v24.1.1

> Hide is enabled by default and cannot be disabled
