### ISSUE TITLE
Can't install any Riru v24.x.x through Magisk - unzip error

### ISSUE THREAD

**Issue by Quado1** [RikkaApps/Riru#280]
**Information:**
- Except Riru itself, all other Magisk modules are disabled: [No] (MagiskHide Props Config, NFC Screen Off, Systemless Hosts)
- Riru version: 24.0.0 - 24.1.2
- Magisk version: 23.0 (23000)
- Android version: 11 RP1A.200720.011
- Device: (optional) Xiaomi Redmi Note 8 Pro

**Describe the bug:**
Can't install any Riru v24.0.0 - 24.1.2 through Magisk - getting 2 messages during installations:
> Copying zip to temp directory
> ! Unzip error

**Additional context:**
Trying to install those versions since the safetynet fix 2.0.0 supports only RIru v24.0.0 or higher (https://github.com/kdrag0n/safetynet-fix/blob/master/riru/module.gradle)

**Comment by RikkaW** [comment]
https://github.com/topjohnwu/Magisk/blob/038f73a5f7102283e857cb1f450e217a648c6a87/app/src/main/java/com/topjohnwu/magisk/core/tasks/FlashZip.kt#L55

Your zip is broken 😉
