### ISSUE TITLE
Riru does not load module and stucks in bootloop

### ISSUE THREAD

**Issue by fakerqu** [RikkaApps/Riru#281]
**Information:**

- Except Riru itself, all other Magisk modules are disabled: [No],loaded module :[adb&fastboot , busyBox, MagiskHide Props Config,scene]
- Riru version:  26.1.2r505.c20529bced
- Magisk version:  23.0
- Android version: 11
- Device: ZTE

**Logs:**
Time:2021-09-18 10:19
Boot Log maybe in loglast1.tar.gz
https://cloud.189.cn/t/e2IVNjiEb6Bb

**Describe the bug:**

riru loaded successfully, but when I enable riru-module, like lsposed and stroage-redirect, my phone goes into a bootloop

**Additional context:**

**Comment by fakerqu** [comment]
after disabling selinux, problem still exists

**Comment by RikkaW** [comment]
Please upload the log to GitHub directly or other places where registering an account is not required.

**Comment by fakerqu** [comment]
Time:2021-09-18 20:04
Riru Version : master@3c61696 debug
Log:
https://1drv.ms/u/s!An3GWRkFHk_yoOBpOctQ7Q-yaM7UNA

**Comment by yujincheng08** [comment]
send `/system/lib64/libbinder.so`

**Comment by fakerqu** [comment]
[]()https://1drv.ms/u/s!An3GWRkFHk_yoOBqqtrySKixksAE2g

**Comment by RikkaW** [comment]
[riru-storage-isolation-v25.1.1-release.zip](https://github.com/RikkaApps/Riru/files/7226953/riru-storage-isolation-v25.1.1-release.zip)
ZTE has libbinder modified, try this module and see if it works.

**Comment by fakerqu** [comment]
It works, stroage redirect is now working in enhanced mode

**Comment by yujincheng08** [comment]
good. now we need some info to check if the device is ZTE. could you paste result of getprop?

also one from ls /system/lib64?

**Comment by fakerqu** [comment]
[prop.txt](https://github.com/RikkaApps/Riru/files/7227282/prop.txt
[ls.txt](https://github.com/RikkaApps/Riru/files/7227283/ls.txt)
)

**Comment by fakerqu** [comment]
[prop.txt](https://github.com/RikkaApps/Riru/files/7227290/prop.txt)
[ls.txt](https://github.com/RikkaApps/Riru/files/7227291/ls.txt)

**Comment by yujincheng08** [comment]
[riru-v26.1.2.r222.f7abf4c191-debug.zip](https://github.com/RikkaApps/Riru/files/7228967/riru-v26.1.2.r222.f7abf4c191-debug.zip)
Try this Riru with the **official** storage redirect enhanced module

**Comment by fakerqu** [comment]
stroage-redirect-enhance, lsposed, sui and ifw-enhance work fine for me
