### ISSUE TITLE
rirud 26.1.2安装后无法安装RIRU-EDX，安装提示检测不到RIRU。

### ISSUE THREAD

**Issue by funnylook** [RikkaApps/Riru#282]
rirud 26.1.2安装后无法安装RIRU-EDX，安装提示检测不到RIRU。
另外，旧版本安装Magisk+RIRU+RIRU-EDX后卡启动界面DUK-AL20

**Comment by RikkaW** [comment]
EdXposed is out of maintenance. If you want to use Xposed Framework, use the original Xposed, LSPosed, Taichi or Dreamland instead.
