### ISSUE TITLE
Magisk 安装失败

### ISSUE THREAD

**Issue by 906499861** [RikkaApps/Riru#286]
![搜狗截图20210925100606](https://user-images.githubusercontent.com/82579833/134754373-6b9a9a6c-0190-4b1d-9c82-4b6606409464.png)
![搜狗截图20210925100617](https://user-images.githubusercontent.com/82579833/134754374-24250e0f-6378-4e65-a453-e1444e824b25.png)
![搜狗截图20210925100737](https://user-images.githubusercontent.com/82579833/134754375-ed4014ac-62e3-455f-91f7-2418c618d2f1.png)

**Comment by 906499861** [comment]
![搜狗截图20210925100934](https://user-images.githubusercontent.com/82579833/134754391-ad8971e0-b4e6-4a97-9c4b-d8e7515bf575.png)

**Comment by Vstory** [comment]
请不要下载源代码，用于安装。
