### ISSUE TITLE
Not work for Phoenix OS darkmatter x86

### ISSUE THREAD

**Issue by RANZAKI** [RikkaApps/Riru#287]
After i install riru module in magisk i get this issue  my Phoenix OS stuck on booting i hope this problem will be fixed soon Thanks😊
![1632739878308361931717](https://user-images.githubusercontent.com/66541872/134894970-95b21652-e9dd-489e-8302-803636902258.jpg)

**Comment by canyie** [comment]
no log no fix

**Comment by RANZAKI** [comment]
Oke bro sorry if indeed this is spam I don't mean so 🙏
