### ISSUE TITLE
bootloop

### ISSUE THREAD

**Issue by dumprop** [RikkaApps/Riru#288]
**Information:**

- Riru version: riru-v26.1.2.r505.c20529bced-release.zip
- Magisk version: 23.0
- Android version: 11 (grapheneos blueline-factory-2021092612)
- Device: pixel 3

**Describe the bug:**

bootloop 

**Additional context:**
probably problem in grapheneos (is it compatible?)

**Comment by RikkaW** [comment]
no log no fix
