### ISSUE TITLE
Riru 不工作 V17

### ISSUE THREAD

**Issue by Howard20181** [RikkaApps/Riru#29]
检测应用报告

> Riru not found in memory.

设备：小米5
系统：MIUI 10.2 Android8.0

Magisk：18.1(18100)
Magisk Manager：7.0.0(185)

Riru模块仅有Ed Xposed

下面是日志
[magisk_log_20190313_125016.log](https://github.com/RikkaApps/Riru/files/2959832/magisk_log_20190313_125016.log)
[bootlog.log](https://github.com/RikkaApps/Riru/files/2959833/bootlog.log)

@RikkaW

**Comment by RikkaW** [comment]
试一下 https://github.com/RikkaApps/Riru/releases/download/v17/magisk-riru-core-v17.1-test.zip

**Comment by Howard20181** [comment]
> 试一下 https://github.com/RikkaApps/Riru/releases/download/v17/magisk-riru-core-v17.1-test.zip

可以了，工作了

**Comment by Howard20181** [comment]
需要更多日志吗？

**Comment by 2220209876** [comment]
![2019-03-13_19-48-08](https://user-images.githubusercontent.com/7346652/54276736-0e2bb800-45c9-11e9-9849-50b31a090309.png)
同样V17会挂掉（卸载重新安装第一次开机有时会有反应，重启后就会掉）。。。。17.1test重启了两次目前没问题

magisk用的测试通道
