### ISSUE TITLE
[Bug] Updated Magisk, now I get this error. 

### ISSUE THREAD

**Issue by QuartzWarrior** [RikkaApps/Riru#295]
### This is a bug of Riru itself

- [X] This is a bug of Riru, not a bug of a Riru module or something else

### Other modules are disabled

- [X] Except Riru itself, all other Magisk modules are disabled

### Riru version

v25.4.4.r426.05efc94

### Android version

11

### Device

Oneplus 7 Pro

### Describe the bug

Riru just doesn't work. 

### Relevant logs

```shell
Riru not installed or not enabled.

Property "ro.dalvik.vm.native.bridge" is not "libriruloader.so".

Make sure you are not using other module which changes this property.

A typical example is, some "optimize" modules changes this property. Since changing this property is meaningless for "optimization", their quality is very questionable. In fact, changing properties for optimization is a joke.

File contents:
/data/adb/riru/dev_random: uOfOD6P
/dev/riru_uOfOD6P not exist
ro.dalvik.vm.native.bridge=0
```

**Comment by RikkaW** [comment]
If Zygisk is enabled, Riru will be disabled.

**Comment by Evengard** [comment]
Won't there be some kind of "Riru compat layer" for such cases, to allow run existing Riru modules on top of Zygisk? Eg loading Riru not directly, but through Zygisk, or just shiming the modules to Zygisk somehow?
