### ISSUE TITLE
[Bug] Riru can't load Lsposed module

### ISSUE THREAD

**Issue by SungJinWoou** [RikkaApps/Riru#296]
### This is a bug of Riru itself

- [X] This is a bug of Riru, not a bug of a Riru module or something else

### Other modules are disabled

- [X] Except Riru itself, all other Magisk modules are disabled

### Zygisk are disabled

- [x] I know that Zygisk and Riru are not compatible and Zygisk has been disabled

### Riru version

26.1.3

### Android version

11

### Device

OnePlus 7 Pro

### Describe the bug

When I check on magisk module, Riru can't load a single module, when I launch Lsposed manager it says that I have to activate it or install, nor I already did that even with a fresh installation it says that.

[magisk_log_2021-11-01T14_52_57Z.log](https://github.com/RikkaApps/Riru/files/7453774/magisk_log_2021-11-01T14_52_57Z.log)

### Relevant logs

```shell
In attachment
```

**Comment by yujincheng08** [comment]
It's me again.

And,

>  I know that Zygisk and Riru are not compatible and Zygisk has been disabled

You didnt disable zygisk...

**Comment by SungJinWoou** [comment]
How can I disable it ?

**Comment by SungJinWoou** [comment]
![Screenshot_20211101-150844](https://user-images.githubusercontent.com/93525884/139684978-478ad70b-4c6a-42d8-9504-422715df351d.jpg)
![Screenshot_20211101-150842](https://user-images.githubusercontent.com/93525884/139684981-466e802c-807c-402c-a5ff-89ecd6522bb8.jpg)
#
![Screenshot_20211101-150834](https://user-images.githubusercontent.com/93525884/139684984-f6904f3b-91b3-4436-9e63-b0b752731830.jpg)
![Screenshot_20211101-141508](https://user-images.githubusercontent.com/93525884/139684987-9e00bf90-f995-4e81-8490-47ed12a3215f.jpg)

I don't have anything that is called zygisk
