### ISSUE TITLE
[Bug] Crashing on Samsung A41

### ISSUE THREAD

**Issue by hafometh88** [RikkaApps/Riru#300]
### This is a bug of Riru itself

- [X] This is a bug of Riru, not a bug of a Riru module or something else

### Other modules are disabled

- [X] Except Riru itself, all other Magisk modules are disabled

### Zygisk are disabled

- [X] I know that Zygisk and Riru are not compatible and Zygisk has been disabled

### Riru version

v26.1.3

### Android version

10

### Device

Samsung A41

### Describe the bug

I installed the module from Magisk and restarted. When I enter the passcode and UI starts booting up the phone crashes and reboots itself. Only thing I can do to get out of this loop is reflashing the software.

### Relevant logs

```shell
I don't have any
```

**Comment by RikkaW** [comment]
No one can help if you don't provide the log.

**Comment by hafometh88** [comment]
[logcat.txt](https://github.com/RikkaApps/Riru/files/7488330/logcat.txt)

Here you go... let me know if I did something wrong and you need other logs

**Comment by RikkaW** [comment]
Everything looks fine from the log.

**Comment by hafometh88** [comment]
That's weird... but you said the ADB connection will be connected, but it disconnects when it reboots... so perhaps the log is incomplete.

**Comment by hafometh88** [comment]
[logcat.txt](https://github.com/RikkaApps/Riru/files/7488488/logcat.txt)

How about this?
