### ISSUE TITLE
v17.1 will cause Felica not functional

### ISSUE THREAD

**Issue by ITJesse** [RikkaApps/Riru#33]
Device: Pixel 3
OS: Android Pie

The Felica cannot work after updated Riru Core from v17 to v17.1 which works will on v17. Sometimes the NFC totally disappeared act as a phone without NFC.

And it can be fixed by simply downgrade to v17.

**Comment by RikkaW** [comment]
Try v18?

**Comment by ITJesse** [comment]
Solved, thanks.
