### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by theFairestOfAll** [RikkaApps/Riru#37]
Riru Core is very laggy on MIUI 10 Oreo. The device is Poco f1

**Comment by Elimiriel** [comment]
Magisk 19+(19.1 and 19.2 for me) and Riru core+EdXposed cause stuttering on HTC 10 Oreo(8.0). Even though lags are reduced with EdXposed 0.4.2.3alpha(it has broken SafetyNet issue), but it is "reduced", not "solved".

**Comment by mirfatif** [comment]
+1, very laggy on AOSP Extended (Pie) Redmi Note 4 (mido).

**Comment by xDaKillerx** [comment]
Idk if it's riru that's causing it but the use of riru and EdXposed makes my Pie Note 8 with Samsung ROM laggy. It is noticably slower and also the booting is so slow . And kinda unstable (tried both variants) likes to bootloop

**Comment by Elimiriel** [comment]
After testing in free time, I also think lags are from EdXposed. No lag was in only Riru core enabled, and current alpha build of EdXposed did huge reduce of lags.

**Comment by zeromentu** [comment]
I'm also having extreme lags, sometimes I need to reboot. I'm on mi8 with pie miui10.
I have no modules on magisk and its smooth, if I enable the modules for edxposed , extreme lags

**Comment by RikkaW** [comment]
Seems the problem is caused by EdXposed. Theoretically, Riru itself should not cause lag problem.
