### ISSUE TITLE
请教如何手动安装Riru

### ISSUE THREAD

**Issue by zheung** [RikkaApps/Riru#39]
作者你好，
魅族的新手机由于无法使用的面具，因此无法通过面具安装Riru

我尝试按照`install.sh`的逻辑将libmemtrack复制后替换，
也在也将zygote_restart复制到`/data/misc/riru/bin/zygote_restart`

但似乎没有成功，App一直显示内存中没有Riru
请教一下我是否遗漏一些步骤？例如部署启动zygote_restart？
感谢万分

**Comment by RikkaW** [comment]
可以先试试直接运行一下 zygote_restart 看看有没有重启/重启之后有没有（

**Comment by tianyah** [comment]
> 作者你好，
> 魅族的新手机由于无法使用的面具，因此无法通过面具安装Riru
> 
> 我尝试按照`install.sh`的逻辑将libmemtrack复制后替换，
> 也在也将zygote_restart复制到`/data/misc/riru/bin/zygote_restart`
> 
> 但似乎没有成功，App一直显示内存中没有Riru
> 请教一下我是否遗漏一些步骤？例如部署启动zygote_restart？
> 感谢万分

请问您解决了吗

**Comment by tianyah** [comment]
> 可以先试试直接运行一下 zygote_restart 看看有没有重启/重启之后有没有（

执行以后没有重启呢，然后手动重启后，也没有

**Comment by KB5201314** [comment]
core：
1. libmemtrack.so替换
2. /data/misc/riru/里面的 bin modules文件夹和api_version文件

模块：
1. lib
2. common里的modules文件夹复制到/data/misc/riru/modules
