### ISSUE TITLE
有关于java的HOOK 入口吗？

### ISSUE THREAD

**Issue by makegame007** [RikkaApps/Riru#4]
求个功能拓展，java层的HOOK入口

**Comment by RikkaW** [comment]
理论上说完美的 hook Java 要用和那些热修复一样的技术。
如果退一步，只使用 Java 的动态代理（虽然范围很有限但是也能做很多事情），那问题会只剩一个如何加载 dex，这一点之前试过，但还不能做到在加载应用自己的 dex 之前就加载自己的 dex，等以后解决了会放出方法。

**Comment by makegame007** [comment]
谢谢，已经实现了

**Comment by solohsu** [comment]
> 谢谢，已经实现了

Can you share or maybe open a pull request please?

**Comment by gam2046** [comment]
> 退一步，只使用 Java 的动态代理（虽然范围很有限但是

经过尝试，nativeForkAndSpecializePost方法的回调中，其实目标程序已经运行起来了，这个时候开始hook，某些方法就hook不到了，例如`Application.<init>`，而如果在nativeForkAndSpecializePre回调中，则还没有fork出子进程，目标应用的dex还没有被加载。

这个情况就有点尴尬。

**Comment by BaeBae33** [comment]
参考[https://github.com/eritpchy/FingerprintPay/blob/aa24627428ddb595c0f7e2cdb58d8d0364b20a28/riru/src/cpp/fingerprint.cpp#L130-L159]可以实现
