### ISSUE TITLE
Loading Riru breaks Reicast emulator

### ISSUE THREAD

**Issue by leopard20** [RikkaApps/Riru#42]
I don't know why, but when I load Riru the Reicast emulator  (https://github.com/reicast/reicast-emulator) freezes when I want to select the storage location, and I can't even change the app settings. Basically, all operations that require writing to storage are broken (in this emu only).
I'm not sure whether it's an issue with Riru or the emulator so I'm posting the issue in both repositories. See here: https://github.com/reicast/reicast-emulator/issues/1628
The app is open source so you should be able to easily detect the problem and, if it's on Riru's end, hopefully fix it.

**Comment by RikkaW** [comment]
Enable Magisk hide for Reicast should avoid the problem. Don't know why :(

**Comment by leopard20** [comment]
You're right. That works. 
It should do for now. Thanks!

If you don't know why this happens, then no need for further investigation. This is good enough for me!
