### ISSUE TITLE
一加6今天刷了这三个包变砖了

### ISSUE THREAD

**Issue by Hiddensu** [RikkaApps/Riru#43]
有什么办法救回来吗？很多资料没备份啊

riru-core-v19.1-magisk-v17.zip
magisk-EdXposed-SandHook-v0.4.2.3_alpha-release.zip
magisk-EdXposed-YAHFA-v0.4.2.3_alpha-release.zip

**Comment by RikkaW** [comment]
1. 直接 Magisk uninstaller
2. 禁用/删除模块，参考 https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md
3. Riru 提供的禁用开关，建立 `/data/misc/riru/.disable`

**Comment by young-zy** [comment]
另外，直接切换boot的系统理论上应该可以恢复，因为一加6是双system分区，刷入包后只会影响其中一个分区，进入另一个分区理论上会保证data分区不受影响，并将system回滚到升级前的上一版本。
