### ISSUE TITLE
App open tIme increased

### ISSUE THREAD

**Issue by pritamdstan** [RikkaApps/Riru#45]
After installing riru core and riru edexposed modules via magisk on oreo, there is a increase in app opening time, Even after disabling the modules in magisk.

**Comment by RikkaW** [comment]
Riru itself should not add appreciable time, you need to provide the log to prove this.
Also, I think you should submit an issue at [EdXposed](https://github.com/ElderDrivers/EdXposed-Magisk).

"Even after disabling the modules in magisk": that is none of my business.
