### ISSUE TITLE
Huawei honor view 10

### ISSUE THREAD

**Issue by Mohsyn** [RikkaApps/Riru#48]
Riru module causes boot loop on honor view 10 emui 9
Magisk 19
Causing to lose root and phone can't skip Riru module anyway. Until lib files are deleted

**Comment by RikkaW** [comment]
Provide boot log please

**Comment by Mohsyn** [comment]
Can't provide bootlog now.
even in bootloop, we lose access to adb so bootlog isn't possible

**Comment by mikusjelly** [comment]
try dmesg or logcat.

**Comment by eebssk1** [comment]
adbd won't start before all basic system services are started succefully.You can try run logcat in magisk post-fs-data and redirect output to a file(remember to add & or it'll block booting)

**Comment by x011** [comment]
I followed all the instructions step by step, installed magisk, RiruCore 19+, edxposed, install edxposed  installer but I got nice brick at the end 👎 👎 👎 👎 👎 
Thank you for bricking  my honor 10

**Comment by MlgmXyysd** [comment]
> I followed all the instructions step by step, installed magisk, RiruCore 19+, edxposed, install edxposed installer but I got nice brick at the end     
> Thank you for bricking my honor 10

Congratulations, Huawei mobile phone is garbage.
Oh, I means Huashit mobile phone.

**Comment by x011** [comment]
> 
> 
> > I followed all the instructions step by step, installed magisk, RiruCore 19+, edxposed, install edxposed installer but I got nice brick at the end
> > Thank you for bricking my honor 10
> 
> Congratulations, Huawei mobile phone is garbage.
> Oh, I means Huashit mobile phone.

Fuck you.

**Comment by JasonKhew96** [comment]
> > > I followed all the instructions step by step, installed magisk, RiruCore 19+, edxposed, install edxposed installer but I got nice brick at the end
> > > Thank you for bricking my honor 10
> > 
> > 
> > Congratulations, Huawei mobile phone is garbage.
> > Oh, I means Huashit mobile phone.
> 
> Fuck you.

There is a chance to brick your phone through "rooting", since you take the risk, there is no reason to blame anybody else, so f**koff
Anyway, since huawei shutdown bootloader unlock code, developer can't really make sure it will work on huawei phone.
