### ISSUE TITLE
Android TV 8.0 安装Riru之后卡开机画面

### ISSUE THREAD

**Issue by imoldchen** [RikkaApps/Riru#53]
不知道是不是 Android TV 缺少什么导致的，Magisk 安装了其他模块都是正常的。

**Comment by RikkaW** [comment]
提供一下开机 log

**Comment by imoldchen** [comment]
> 
> 
> 提供一下开机 log

有获得开机日志文件的教程吗？因为卡在开机LOGO画面，没办法用ADB
