### ISSUE TITLE
MIUI10 面具安装Riru-Core模块后，调用照相机失败

### ISSUE THREAD

**Issue by solayao** [RikkaApps/Riru#54]
安装了该模块后，手机照相机功能不能正常使用

**Comment by RikkaW** [comment]
请提供你的手机型号、系统版本和开机 log

**Comment by solayao** [comment]
后来我安装了xposed模块也出现同样问题，看来不是core模块的问题。手机型号小米play，系统版本开发版10.9.7.25。开机log怎么看的？
---原始邮件---
发件人:"Rikka"<notifications@github.com>
发送时间:2019年7月31日 星期三 下午6:58
收件人:"RikkaApps/Riru"<Riru@noreply.github.com>
抄送:"Dizzy L"<932164534@QQ.com>;"Author"<author@noreply.github.com>
主题:Re: [RikkaApps/Riru] MIUI10 面具安装Riru-Core模块后，调用照相机失败 (#54)

请提供你的手机型号、系统版本和开机 log

&mdash;
