### ISSUE TITLE
请问libmemtrack.so？

### ISSUE THREAD

**Issue by yehosjhwd** [RikkaApps/Riru#55]
为什么觉得libmemtrack.so不是很好，还有比这个更简单的模块吗？
我可以自己编译libmemtrack.so而不是使用hook方式去替换系统的这个吗？
如果指针对某一API版本的anndroid系统的话

**Comment by RikkaW** [comment]
因为 libmemtrack 扯到的东西有点多
可以，但是不在 AOSP 里编译应该不是很方便

**Comment by yehosjhwd** [comment]
我编译了，确实可以 ，感谢
