### ISSUE TITLE
请问如何彻底卸载riru core？

### ISSUE THREAD

**Issue by adsl95** [RikkaApps/Riru#56]
magisk点卸载后，是完全卸载吗？并没有看见安装时的刷机界面，是不是文件其实还在只是没有启用？完全卸载是不是需要卸载包之类？请问哪里可以下载到？谢谢

**Comment by RikkaW** [comment]
再手动删 `/data/misc/riru` 就什么都没了，当然不删也没什么事

**Comment by adsl95** [comment]
请问安装的edxp框架也是删除这个文件夹是吗？谢谢

**Comment by RikkaW** [comment]
去问 EdXposed

**Comment by adsl95** [comment]
好的，谢谢您的解答
