### ISSUE TITLE
Causing bootscreen stuck on starting and then neither powering off or restarting on LYF FLAME 7 (LS 4006)

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [RikkaApps/Riru#60]
Even when I take out the battery and put it back and then restart phone is still stuck on boot screen.Same problem with all Riru core versions.Fix it.Please.I need it.

**Comment by DrSaad77** [comment]
not only for you, the same is happing to me on samsung!!!
Like you I tried some previous versions of Riru Core, and EdXplore and it is the same!!
And without to say that all fluidity of the phone is affected when the phone finally boot!!
I really think about to go back to Oreo and use all good Xposed!
