### ISSUE TITLE
源码无法编译

### ISSUE THREAD

**Issue by kotoricon** [RikkaApps/Riru#63]
永远都是这两个错误，不知道怎么回事 即便不修改任何内容直接编译也这样。
C:\Users\xxx\Desktop\Riru-master>gradlew.bat assembleMagiskRelease

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\xxx\Desktop\Riru-master\app\build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':app'.
> For input string: ""

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by RikkaW** [comment]
1. Install `git` or modify `app\build.gradle`
2. Should be solved by 1
