### ISSUE TITLE
Task :Riru:riru-core:buildNativeRelease FAILED 

### ISSUE THREAD

**Issue by eagle518** [RikkaApps/Riru#64]
branch :master v19.5

> Task :Riru-19.5:riru-core:buildNativeRelease FAILED
/Users/xxx/android/sdk2/ndk-bundle/ndk-build: line 3: /Users/xxx/workspace/Xposed/Riru-19.5/riru-core/build/ndk-build: No such file or directory

> Task :riru-core:assembleMagiskRelease FAILED

FAILURE: Build failed with an exception.

请问该如何解决？

**Comment by MyController** [comment]
sudo vim /etc/paths.d/android_ndk_path
里面添加类似这样的PATH
/Users/username/Library/Android/sdk/ndk-bundle
