### ISSUE TITLE
Boot loop on Android 8.0

### ISSUE THREAD

**Issue by Verrickt** [RikkaApps/Riru#65]
Hi,
I installed riru-core via magisk and I find that while enabling riru-core causes no problem,enabling edxposed(either YAHFA or SandHook) will cause a bootloop. 
Phone just reboot after boot animation.  

Sony xperia xzs
Android  8.0.0(Kernel 3.18.66)
Magisk 19.3(19300)
logs: 
- https://gist.github.com/Verrickt/d765314eab12e8d1802be87581f07f9c
- https://gist.github.com/Verrickt/58c0f9667e137d51d20b40e47e9ed609

Thanks in advance.

**Comment by RikkaW** [comment]
You should create issus at EdXposed's repo.
