### ISSUE TITLE
S10 android Q

### ISSUE THREAD

**Issue by Cholens** [RikkaApps/Riru#69]
Riru v27 found.
However, native methods of Zygote class not replaced, please contact developer with the following information.

nativeForkAndSpecializeSignature:
(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I

getNativeForkSystemServerSignature:
(II[IIII[[IJJ)I

**Comment by Jasi2169** [comment]
Yes same issue note 9

**Comment by amakuramio** [comment]
Give a dump of framework.jar from root/system/framework

**Comment by dr4go** [comment]
Here you are... G973F, January's firmware (BSL4)

[framework.zip](https://github.com/RikkaApps/Riru/files/4028277/framework.zip)

**Comment by amakuramio** [comment]
Does it work now? With new riru

**Comment by Cholens** [comment]
> Does it work now? With new riru

Yes is now working! :)

**Comment by alroy214** [comment]
How can we get the new riru?
