### ISSUE TITLE
请教一个问题, 怎么在service.jar进程中注入我的dex

### ISSUE THREAD

**Issue by 767972675** [RikkaApps/Riru#71]
framework.jar启动的时候确实会走nativeForkSystemServerPost，当我在想在service.jar里注入我的dex的时候，我发现service服务起来后不会走nativeForkSystemServerPost
我在我的dex调用 Class.forName("com.android.server.policy.PhoneWindowManager");函数

如果找不到class就会打印日志，发现每次都会打印找不到class的日志，nativeForkSystemServerPost也只会执行1次，我刚开始怀疑是loaddex时机问题，我又在进程启动后延迟了15秒后调用 Class.forName("com.android.server.policy.PhoneWindowManager");函数来判断是否有这个class,还是没有，但是这个class实际上是存在的，请问是我方法用错了吗！

**Comment by Kr328** [comment]
`Class.forName(String name);`
仅会搜索 Bootstrap Class Loader
services.jar 不被 Bootstrap Class Loader 加载
你可以参考 [这个](https://github.com/Kr328/Riru-ForceDisplayCutoutMode/blob/bdd32f81a840e4d1877d5de7b24d90ba9914214f/src/main/java/com/github/kr328/dcm/Injector.java#L62) 来获取 services.jar 的 Class Loader

**Comment by 767972675** [comment]
> `Class.forName(String name);`
> 仅会搜索Bootstrap Class Loader
> services.jar不被Bootstrap Class Loader加载
> 你可以参考[这个](https://github.com/Kr328/Riru-ForceDisplayCutoutMode/blob/bdd32f81a840e4d1877d5de7b24d90ba9914214f/src/main/java/com/github/kr328/dcm/Injector.java#L62)来获取services.jar的Class Loader

意思是nativeForkSystemServerPost中注入dex文件是没有问题的对吧

**Comment by 767972675** [comment]
> `Class.forName(String name);`
> 仅会搜索Bootstrap Class Loader
> services.jar不被Bootstrap Class Loader加载
> 你可以参考[这个](https://github.com/Kr328/Riru-ForceDisplayCutoutMode/blob/bdd32f81a840e4d1877d5de7b24d90ba9914214f/src/main/java/com/github/kr328/dcm/Injector.java#L62)来获取services.jar的Class Loader

services.jar 是通过PathClassLoader加载的吗

**Comment by 767972675** [comment]
> `Class.forName(String name);`
> 仅会搜索Bootstrap Class Loader
> services.jar不被Bootstrap Class Loader加载
> 你可以参考[这个](https://github.com/Kr328/Riru-ForceDisplayCutoutMode/blob/bdd32f81a840e4d1877d5de7b24d90ba9914214f/src/main/java/com/github/kr328/dcm/Injector.java#L62)来获取services.jar的Class Loader

那我应该如何在services.jar进程中注入自己的dex文件，求救
