### ISSUE TITLE
Oneplus 3T + Havoc 3 (Android Q/10): can't copy libmemtrack

### ISSUE THREAD

**Issue by edouard-lopez** [RikkaApps/Riru#72]
Hello,

### Env

* phone: Oneplus 3T
* OS: Havoc-OS-v3.0-20191223-oneplus3-Official.zip (Android Q/10)
* Revocery: TWRP `3.3.1-1`
* 

### Error

installing `Riru_-_Core-v19.5(27).zip`

	…
	- Found /sytem/lib64/libmemtrack.so
	! Can't copy /sytem/lib64/libmemtrack.so
	…

When trying to install Xposed-Framework-v90-beta3(9030).zip, it tells me:

	! Unsupported device

Does Android Q supported? Is it device dependant?

**Comment by RikkaW** [comment]
It's really weird, [a simple `cp`](https://github.com/Magisk-Modules-Repo/riru-core/blob/47cf5c968dbdc81df434604fc0150942f85f5732/install.sh#L154) fails.
Can you try `cp "/sytem/lib64/libmemtrack.so" "/data/adb/libmemtrack_real.so"` in any su shell?

For Xposed, rovo89 Xposed has stopped maintenance for years. So it definitely not support Q. Also, Xposed is not related to Riru.
