### ISSUE TITLE
Samsung Android 10 support

### ISSUE THREAD

**Issue by Jasi2169** [RikkaApps/Riru#73]
Edxposed wont work because it depends upon and riru cant hook system functions, needs to be supported in libmem for samsung android 10 roms using same patterns

[framework.zip](https://github.com/RikkaApps/Riru/files/4028307/framework.zip)

Riru v27 found.
However, native methods of Zygote class not replaced, please contact developer with the following information.

nativeForkAndSpecializeSignature:
(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I

getNativeForkSystemServerSignature:
(II[IIII[[IJJ)I

Attached framework.jar ,compressed in zip

**Comment by amakuramio** [comment]
Yes edxposed system modules won't work on Samsung q but work fine on AOSP q

**Comment by Exeedy** [comment]
> Riru v27 found.
> However, native methods of Zygote class not replaced, please contact developer with the following information.
> 
> nativeForkAndSpecializeSignature:
> (II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I
> 
> getNativeForkSystemServerSignature:
> (II[IIII[[IJJ)I

I had the same error.
Hopefully we will get it working soon 🤞

**Comment by amakuramio** [comment]
Give a dump of framework.jar from root/system/framework

**Comment by Jasi2169** [comment]
> Give a dump of framework.jar from root/system/framework

Here it is https://www100.zippyshare.com/v/LnH42MQz/file.html

**Comment by Jasi2169** [comment]
v19.6 is fine now
