### ISSUE TITLE
Riru on SM-G975F not working correctly

### ISSUE THREAD

**Issue by Exeedy** [RikkaApps/Riru#75]
`Riru Unknown (version code 27) found.
However, native methods of Zygote class not replaced, please contact developer with the following information.

nativeForkAndSpecializeSignature:
(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I

nativeSpecializeAppProcessSignature (from Q beta 3):
(II[II[[IILjava/lang/String;IILjava/lang/String;ZLjava/lang/String;Ljava/lang/String;)V

nativeForkSystemServerSignature:
(II[IIII[[IJJ)I`

**Here is the logcat:**
[logreader_2020-01-07_13-08-37.log](https://github.com/RikkaApps/Riru/files/4030569/logreader_2020-01-07_13-08-37.log)

**Comment by amakuramio** [comment]
Give a dump of framework.jar from root/system/framework

**Comment by Exeedy** [comment]
@amakuramio thank you

here is the

**Comment by amakuramio** [comment]
There is new riru version, can anyone test now?

**Comment by alroy214** [comment]
@amakuramio where can I find the new version?

**Comment by Exeedy** [comment]
@amakuramio yes i've tried the new version modules now loading but none of them are working. Looks like the modules are thinking that xposed is not activated.
