### ISSUE TITLE
Zip error in 19.6

### ISSUE THREAD

**Issue by mikehorizon** [RikkaApps/Riru#78]
Hello,

Installing 19.6 rezult in some zip error. It 
![Screenshot_20200110-185223](https://user-images.githubusercontent.com/59742668/72172948-1918ca00-33df-11ea-80de-c2fd7d5e025f.jpg)

**Comment by Schmitin** [comment]
Also having this issue after fresh factory reset.

![20200110_175227](https://user-images.githubusercontent.com/59183604/72191995-0fd53080-33d2-11ea-89b1-d5b40f54bf42.jpg)

**Comment by Schmitin** [comment]
19.5 installed fine. Broken zip?

**Comment by ram108** [comment]
I have the same error with failed installation.

**Comment by hdfg159** [comment]
19.6 安装有同样问题，OS : OnePlus 5T Android 8.1

**Comment by leec0830** [comment]
I have the same error with failed installation.

**Comment by RikkaW** [comment]
Download again, it should have no problem now.
