### ISSUE TITLE
Installation failed "failed to verify zygote_restart/zygote_restart_amd64

### ISSUE THREAD

**Issue by Quantexx** [RikkaApps/Riru#80]
One my OP7 pro I get this error message while trying to flash through standard Magisk 20.3. It installs some of the module though I think as it shows up after reboot but it's not a good install..
[magisk_install_log_2020-01-11T13:42:44Z.log](https://github.com/RikkaApps/Riru/files/4049340/magisk_install_log_2020-01-11T13.42.44Z.log)

**Comment by RikkaW** [comment]
Download again.

**Comment by Quantexx** [comment]
I did this. Both from here and the magisk repository.
