### ISSUE TITLE
请问com.android.systemui进程在nativeForkAndSpecializePre拿不到

### ISSUE THREAD

**Issue by 767972675** [RikkaApps/Riru#83]
请问com.android.systemui进程在nativeForkAndSpecializePre拿不到，我把所有函数都加了日志，把com.android.systemui杀掉都不会看到有打印日志

**Comment by RikkaW** [comment]
或许是因为你的系统的 systemui 在 uid 1000
然后默认是不处理的，如果需要要改下面（
https://github.com/RikkaApps/Riru-ModuleTemplate/blob/master/module/src/main/cpp/main.cpp#L59-L63
