### ISSUE TITLE
Wrong MAGISK version when using Canary

### ISSUE THREAD

**Issue by ch3mn3y** [RikkaApps/Riru#84]
Tried updating Core to 19.7, but got error to use MAGISK 19+. Wouldn't be a problen if I didn't have 20.4 already installed.
Seems some change(s) in MAGISK are not backward compatible or something and Riru doesn't see that there is right version.
![Screenshot_20200210-174945](https://user-images.githubusercontent.com/20260224/74170971-0a1b7680-4c2e-11ea-8879-1c513ea5f2bf.jpg)
![Screenshot_20200210-174956](https://user-images.githubusercontent.com/20260224/74170978-0c7dd080-4c2e-11ea-844b-06a01726d5ad.jpg)

Log from MAGISK:
- Copying zip to temp directory
- Installing Riru_-_Core-v19.7(29).zip
update-binary[56]: [: 18100: unexpected operator/operand
*******************************
 Please install Magisk v19.0+! 
*******************************
! Installation failed

**Comment by RikkaW** [comment]
The error didn't happened in module itself.
The error happened in `update-binary` and `update-binary` is replaced by Magisk on install.
IMO, maybe `update-binary` or `/data/adb/magisk/util_functions.sh` is broken, you may get this error for all modules.

**Comment by ch3mn3y** [comment]
Seems You're right as MAGISK Manager update fixed this error, but created another one... Haha

- Copying zip to temp directory
- Installing Riru_-_Core-v19.7(29).zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: /dev/tmp/module.prop
*************
 Riru - Core 
*************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: /data/adb/modules_update/riru-core/customize.sh
- Device sdk: 28
- Device platform: arm64
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: /dev/tmp/verify.sh
- Extracting Magisk files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: /data/adb/modules_update/riru-core/module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: /dev/tmp/.vunzip/module.prop.sha256sum
sha256sum: -s: No such file or directory
sha256sum: -s: no lines
*********************************************************
! Failed to verify module.prop
! This zip may be corrupted, please try downloading again
*********************************************************
! Installation failed

Will waiy to the next one :)
