### ISSUE TITLE
riru core今天无法通过SafetyNet

### ISSUE THREAD

**Issue by njtony11** [RikkaApps/Riru#90]
今天ctsprofile和basicintegrity都是false了，打开magisk核心模式后检查两者为true，然后一个模块一个模块禁用后发现是riru core加载后就为false了，取消后又为true了，用的最新的19.7，最怕google开始限制edxposed了。。。。。。。。

**Comment by kevin01523** [comment]
Yes riru core causes safety net to trip and sadetynet passes if riru core is not loaded

**Comment by njtony11** [comment]
今天发现单独加载riru core或edxposed，safetynet都通过，两者同时加载后就无法通过了。

**Comment by RikkaW** [comment]
说明应该查的是 xposed 吧（
