### ISSUE TITLE
error: use of undeclared identifier 'ARG_MAX'

### ISSUE THREAD

**Issue by soleebook** [RikkaApps/Riru#94]
编译不能通过。出现如下错误：

/Riru/module/src/main/cpp/misc.cpp:40:35: error: use of undeclared identifier 'ARG_MAX'
      if ((size = read(fd, cmdline, ARG_MAX)) > 0) {
                                    ^
  1 error generated.

**Comment by RikkaW** [comment]
What version of NDK you are using?

**Comment by soleebook** [comment]
Thanks for your tips, I changed to the latest version of NDK. 
Can be compiled and passed.
