### ISSUE TITLE
SafetyNet failing due to Riru

### ISSUE THREAD

**Issue by Mygod** [RikkaApps/Riru#96]
Magisk 20.4, Riru core 21.0. As soon as Riru core is enabled, ctsProfile and basicIntegrity goes to false. Related: #89.

Current status: 21.1 passes SafetyNet as of May 3rd.

**Comment by dr4go** [comment]
Same problem over here... Additionally the SafetyNet's advice mentions: "RESTORE_TO_FACTORY_ROM"

**Comment by cscomic** [comment]
same problem here, it seems gms detect riru component now.

**Comment by Holdmyhand** [comment]
I've had the same problem.

**Comment by RikkaW** [comment]
Added random name, makes SafetyNet happy for now.

**Comment by TheStrixCoder** [comment]
It started failing again..

**Comment by ElPelocho** [comment]
It worked for a while but it's failing again

**Comment by EhsanYE** [comment]
i Tried New Riru But Still All False Here...

**Comment by user22555** [comment]
maybe an idea: make it possible somehow to enable and disable riru without rebooting so people can enable it just in time when its needed and disable it for certain scenarios where they use Apps which need to pass safetynet, maybe even automate this process like the magisk hide list.

i guess the limitation here is the concept of the way how magisk works which needs by design a reboot for every new module that is installed or are there modules out there which work without reboot?

**Comment by ffsec** [comment]
The latest version (21.1) is still working fine for me. Are you sure, there is nothing else causing the issues?

**Comment by ElPelocho** [comment]
> The latest version (21.1) is still working fine for me. Are you sure, there is nothing else causing the issues?

Yes, if I only install Magisk it works, once I install riru it stops working.Without having anything else installed.

**Comment by LDKLucifer** [comment]
> The latest version (21.1) is still working fine for me. Are you sure, there is nothing else causing the issues?

It used to work for me too but I don't know, Google pushed out some update maybe.

**Comment by cscomic** [comment]
> Added random name, makes SafetyNet happy for now.

Thanks Rikka, riru work fine now

**Comment by ElPelocho** [comment]
> > Added random name, makes SafetyNet happy for now.
> 
> Thanks Rikka, riru work fine now

But have you tried it now? How is it possible that it works for you if I am in contact with 3 people who are experiencing the same thing as me. And before that, did that stop working for you?

**Comment by S-U-M-1** [comment]
Riru v21.1 fails SafetyNet for me on my ZenFone 6 with the latest Magisk 20.4. The previous versions also failed for me. In fact it's the only thing that's ever failed SafetyNet on this phone.

**Comment by TitusLabienus** [comment]
> > The latest version (21.1) is still working fine for me. Are you sure, there is nothing else causing the issues?
> 
> Yes, if I only install Magisk it works, once I install riru it stops working.Without having anything else installed.

I can confirm this too.

**Comment by TitusLabienus** [comment]
> > > Added random name, makes SafetyNet happy for now.
> > 
> > Thanks Rikka, riru work fine now
> 
> But have you tried it now? How is it possible that it works for you if I am in contact with 3 people who are experiencing the same thing as me. And before that, did that stop working for you?

For me, renaming Magisk doesn't help either.

**Comment by unl0cks** [comment]
> 
> 
> maybe an idea: make it possible somehow to enable and disable riru without rebooting so people can enable it just in time when its needed and disable it for certain scenarios where they use Apps which need to pass safetynet, maybe even automate this process like the magisk hide list.
> 
> i guess the limitation here is the concept of the way how magisk works which needs by design a reboot for every new module that is installed or are there modules out there which work without reboot?

Or let us whitelist and/or blacklist which apps should have it enabled. I.e. blacklist SnapChat so Riru Core gets disabled if SnapChat is started.
