### ISSUE TITLE
Google Chrome cannot be opened

### ISSUE THREAD

**Issue by CROW-14** [RikkaApps/Riru#97]
If I unfortunately activate EdXposed and Google Chrome, it can't be opened, if I turn off the duplicate module and edxposed Google Chrome can be opened again, thanks

**Comment by RikkaW** [comment]
Sounds like an EdXposed issue.

**Comment by forliuyifei** [comment]
同样的问题，Riru 21.3，想配合 thanox magisk 补丁一起使用，结果 chrome 点开就闪退，卸载 thanox 依然闪退，卸载此模块才解决。
